// Code generated by protoc-gen-triple. DO NOT EDIT.
//
// Source: base.proto
package base

import (
	"context"
)

import (
	"dubbo.apache.org/dubbo-go/v3"
	"dubbo.apache.org/dubbo-go/v3/client"
	"dubbo.apache.org/dubbo-go/v3/common"
	"dubbo.apache.org/dubbo-go/v3/common/constant"
	"dubbo.apache.org/dubbo-go/v3/protocol/triple/triple_protocol"
	"dubbo.apache.org/dubbo-go/v3/server"
)

// This is a compile-time assertion to ensure that this generated file and the Triple package
// are compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of Triple newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of Triple or updating the Triple
// version compiled into your binary.
const _ = triple_protocol.IsAtLeastVersion0_1_0

const (
	// BaseServiceName is the fully-qualified name of the BaseService service.
	BaseServiceName = "base.BaseService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BaseServiceGetFeeToleranceProcedure is the fully-qualified name of the BaseService's GetFeeTolerance RPC.
	BaseServiceGetFeeToleranceProcedure = "/base.BaseService/GetFeeTolerance"
	// BaseServiceGetPriorityFeeProcedure is the fully-qualified name of the BaseService's GetPriorityFee RPC.
	BaseServiceGetPriorityFeeProcedure = "/base.BaseService/GetPriorityFee"
	// BaseServiceGetInstUnitsProcedure is the fully-qualified name of the BaseService's GetInstUnits RPC.
	BaseServiceGetInstUnitsProcedure = "/base.BaseService/GetInstUnits"
	// BaseServiceGetTokenQuoteSOLPriceProcedure is the fully-qualified name of the BaseService's GetTokenQuoteSOLPrice RPC.
	BaseServiceGetTokenQuoteSOLPriceProcedure = "/base.BaseService/GetTokenQuoteSOLPrice"
	// BaseServiceGetTokenQuoteUSDTPriceProcedure is the fully-qualified name of the BaseService's GetTokenQuoteUSDTPrice RPC.
	BaseServiceGetTokenQuoteUSDTPriceProcedure = "/base.BaseService/GetTokenQuoteUSDTPrice"
	// BaseServiceGetUSDTQuoteSOLPriceProcedure is the fully-qualified name of the BaseService's GetUSDTQuoteSOLPrice RPC.
	BaseServiceGetUSDTQuoteSOLPriceProcedure = "/base.BaseService/GetUSDTQuoteSOLPrice"
	// BaseServiceSendTransactionProcedure is the fully-qualified name of the BaseService's SendTransaction RPC.
	BaseServiceSendTransactionProcedure = "/base.BaseService/SendTransaction"
)

var (
	_ BaseService = (*BaseServiceImpl)(nil)
)

// BaseService is a client for the base.BaseService service.
type BaseService interface {
	GetFeeTolerance(ctx context.Context, req *GetFeeToleranceReq, opts ...client.CallOption) (*GetFeeToleranceRsp, error)
	GetPriorityFee(ctx context.Context, req *GetPriorityFeeReq, opts ...client.CallOption) (*GetPriorityFeeRsp, error)
	GetInstUnits(ctx context.Context, req *GetInstUnitsReq, opts ...client.CallOption) (*GetInstUnitsRsp, error)
	GetTokenQuoteSOLPrice(ctx context.Context, req *GetTokenQuoteSOLPriceReq, opts ...client.CallOption) (*PriceQuoteRsp, error)
	GetTokenQuoteUSDTPrice(ctx context.Context, req *GetTokenQuoteUSDTPriceReq, opts ...client.CallOption) (*PriceQuoteRsp, error)
	GetUSDTQuoteSOLPrice(ctx context.Context, req *GetUSDTQuoteSOLPriceReq, opts ...client.CallOption) (*PriceQuoteRsp, error)
	SendTransaction(ctx context.Context, req *SendTransactionReq, opts ...client.CallOption) (*SendTransactionRsp, error)
}

// NewBaseService constructs a client for the base.BaseService service.
func NewBaseService(cli *client.Client, opts ...client.ReferenceOption) (BaseService, error) {
	conn, err := cli.DialWithInfo("base.BaseService", &BaseService_ClientInfo, opts...)
	if err != nil {
		return nil, err
	}
	return &BaseServiceImpl{
		conn: conn,
	}, nil
}

func SetConsumerBaseService(srv common.RPCService) {
	dubbo.SetConsumerServiceWithInfo(srv, &BaseService_ClientInfo)
}

// BaseServiceImpl implements BaseService.
type BaseServiceImpl struct {
	conn *client.Connection
}

func (c *BaseServiceImpl) GetFeeTolerance(ctx context.Context, req *GetFeeToleranceReq, opts ...client.CallOption) (*GetFeeToleranceRsp, error) {
	resp := new(GetFeeToleranceRsp)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "GetFeeTolerance", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *BaseServiceImpl) GetPriorityFee(ctx context.Context, req *GetPriorityFeeReq, opts ...client.CallOption) (*GetPriorityFeeRsp, error) {
	resp := new(GetPriorityFeeRsp)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "GetPriorityFee", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *BaseServiceImpl) GetInstUnits(ctx context.Context, req *GetInstUnitsReq, opts ...client.CallOption) (*GetInstUnitsRsp, error) {
	resp := new(GetInstUnitsRsp)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "GetInstUnits", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *BaseServiceImpl) GetTokenQuoteSOLPrice(ctx context.Context, req *GetTokenQuoteSOLPriceReq, opts ...client.CallOption) (*PriceQuoteRsp, error) {
	resp := new(PriceQuoteRsp)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "GetTokenQuoteSOLPrice", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *BaseServiceImpl) GetTokenQuoteUSDTPrice(ctx context.Context, req *GetTokenQuoteUSDTPriceReq, opts ...client.CallOption) (*PriceQuoteRsp, error) {
	resp := new(PriceQuoteRsp)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "GetTokenQuoteUSDTPrice", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *BaseServiceImpl) GetUSDTQuoteSOLPrice(ctx context.Context, req *GetUSDTQuoteSOLPriceReq, opts ...client.CallOption) (*PriceQuoteRsp, error) {
	resp := new(PriceQuoteRsp)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "GetUSDTQuoteSOLPrice", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *BaseServiceImpl) SendTransaction(ctx context.Context, req *SendTransactionReq, opts ...client.CallOption) (*SendTransactionRsp, error) {
	resp := new(SendTransactionRsp)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "SendTransaction", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

var BaseService_ClientInfo = client.ClientInfo{
	InterfaceName: "base.BaseService",
	MethodNames:   []string{"GetFeeTolerance", "GetPriorityFee", "GetInstUnits", "GetTokenQuoteSOLPrice", "GetTokenQuoteUSDTPrice", "GetUSDTQuoteSOLPrice", "SendTransaction"},
	ConnectionInjectFunc: func(dubboCliRaw interface{}, conn *client.Connection) {
		dubboCli := dubboCliRaw.(*BaseServiceImpl)
		dubboCli.conn = conn
	},
}

// BaseServiceHandler is an implementation of the base.BaseService service.
type BaseServiceHandler interface {
	GetFeeTolerance(context.Context, *GetFeeToleranceReq) (*GetFeeToleranceRsp, error)
	GetPriorityFee(context.Context, *GetPriorityFeeReq) (*GetPriorityFeeRsp, error)
	GetInstUnits(context.Context, *GetInstUnitsReq) (*GetInstUnitsRsp, error)
	GetTokenQuoteSOLPrice(context.Context, *GetTokenQuoteSOLPriceReq) (*PriceQuoteRsp, error)
	GetTokenQuoteUSDTPrice(context.Context, *GetTokenQuoteUSDTPriceReq) (*PriceQuoteRsp, error)
	GetUSDTQuoteSOLPrice(context.Context, *GetUSDTQuoteSOLPriceReq) (*PriceQuoteRsp, error)
	SendTransaction(context.Context, *SendTransactionReq) (*SendTransactionRsp, error)
}

func RegisterBaseServiceHandler(srv *server.Server, hdlr BaseServiceHandler, opts ...server.ServiceOption) error {
	return srv.Register(hdlr, &BaseService_ServiceInfo, opts...)
}

func SetProviderBaseService(srv common.RPCService) {
	dubbo.SetProviderServiceWithInfo(srv, &BaseService_ServiceInfo)
}

var BaseService_ServiceInfo = server.ServiceInfo{
	InterfaceName: "base.BaseService",
	ServiceType:   (*BaseServiceHandler)(nil),
	Methods: []server.MethodInfo{
		{
			Name: "GetFeeTolerance",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(GetFeeToleranceReq)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*GetFeeToleranceReq)
				res, err := handler.(BaseServiceHandler).GetFeeTolerance(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
		{
			Name: "GetPriorityFee",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(GetPriorityFeeReq)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*GetPriorityFeeReq)
				res, err := handler.(BaseServiceHandler).GetPriorityFee(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
		{
			Name: "GetInstUnits",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(GetInstUnitsReq)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*GetInstUnitsReq)
				res, err := handler.(BaseServiceHandler).GetInstUnits(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
		{
			Name: "GetTokenQuoteSOLPrice",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(GetTokenQuoteSOLPriceReq)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*GetTokenQuoteSOLPriceReq)
				res, err := handler.(BaseServiceHandler).GetTokenQuoteSOLPrice(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
		{
			Name: "GetTokenQuoteUSDTPrice",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(GetTokenQuoteUSDTPriceReq)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*GetTokenQuoteUSDTPriceReq)
				res, err := handler.(BaseServiceHandler).GetTokenQuoteUSDTPrice(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
		{
			Name: "GetUSDTQuoteSOLPrice",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(GetUSDTQuoteSOLPriceReq)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*GetUSDTQuoteSOLPriceReq)
				res, err := handler.(BaseServiceHandler).GetUSDTQuoteSOLPrice(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
		{
			Name: "SendTransaction",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(SendTransactionReq)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*SendTransactionReq)
				res, err := handler.(BaseServiceHandler).SendTransaction(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
	},
}
