// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTxScanInfo = "public.t_tx_scan_info"

// TxScanInfo mapped from table <public.t_tx_scan_info>
type TxScanInfo struct {
	Service       string  `gorm:"column:service;not null" json:"service"`
	SubService    string  `gorm:"column:sub_service;not null" json:"sub_service"`
	NativeAccount string  `gorm:"column:native_account;not null" json:"native_account"`
	PdaAccount    string  `gorm:"column:pda_account;not null" json:"pda_account"`
	UntilTxID     string  `gorm:"column:until_tx_id;not null" json:"until_tx_id"`
	BeforeTxID    string  `gorm:"column:before_tx_id" json:"before_tx_id"`
	Slot          float64 `gorm:"column:slot;not null" json:"slot"`
}

// TableName TxScanInfo's table name
func (*TxScanInfo) TableName() string {
	return TableNameTxScanInfo
}
