// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCampaignQuoteLimit = "t_campaign_quote_limit"

// CampaignQuoteLimit mapped from table <t_campaign_quote_limit>
type CampaignQuoteLimit struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	DailyLimit float64   `gorm:"column:daily_limit;not null;default:500000000" json:"dailyLimit"`
	QuotaDate  time.Time `gorm:"column:quota_date;not null;default:CURRENT_DATE" json:"quotaDate"`
	Session    int16     `gorm:"column:session;not null" json:"session"`
	CreatedAt  time.Time `gorm:"column:created_at;default:now()" json:"createdAt"`
	UpdatedAt  time.Time `gorm:"column:updated_at;default:now()" json:"updatedAt"`
}

// TableName CampaignQuoteLimit's table name
func (*CampaignQuoteLimit) TableName() string {
	return TableNameCampaignQuoteLimit
}
