// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameExcludeAccount = "t_exclude_account"

// ExcludeAccount mapped from table <t_exclude_account>
type ExcludeAccount struct {
	RecordID      string    `gorm:"column:record_id;not null;default:gen_ulid()" json:"recordId"`
	NativeAccount string    `gorm:"column:native_account;not null" json:"nativeAccount"`
	Remark        string    `gorm:"column:remark" json:"remark"`
	CreatedAt     time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt     time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updatedAt"`
}

// TableName ExcludeAccount's table name
func (*ExcludeAccount) TableName() string {
	return TableNameExcludeAccount
}
