// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFeeTolerance = "t_fee_tolerance"

// FeeTolerance mapped from table <t_fee_tolerance>
type FeeTolerance struct {
	MaxLessRate float64   `gorm:"column:max_less_rate;not null" json:"maxLessRate"`
	CreatedAt   time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt   time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updatedAt"`
}

// TableName FeeTolerance's table name
func (*FeeTolerance) TableName() string {
	return TableNameFeeTolerance
}
