// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameHackerAccount = "t_hacker_account"

// HackerAccount mapped from table <t_hacker_account>
type HackerAccount struct {
	RecordID      string    `gorm:"column:record_id;not null;default:gen_ulid()" json:"recordId"`
	NativeAccount string    `gorm:"column:native_account;not null" json:"nativeAccount"`
	CreatedAt     time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt     time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updatedAt"`
}

// TableName HackerAccount's table name
func (*HackerAccount) TableName() string {
	return TableNameHackerAccount
}
