// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLevelDist = "t_level_dist"

// LevelDist mapped from table <t_level_dist>
type LevelDist struct {
	Level int32 `gorm:"column:level;not null" json:"level"`
}

// TableName LevelDist's table name
func (*LevelDist) TableName() string {
	return TableNameLevelDist
}
