// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLevelDist = "t_level_dist"

// LevelDist mapped from table <t_level_dist>
type LevelDist struct {
	DistLevel int32 `gorm:"column:dist_level;not null" json:"distLevel"`
}

// TableName LevelDist's table name
func (*LevelDist) TableName() string {
	return TableNameLevelDist
}
