// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLevelRatio = "t_level_ratio"

// LevelRatio mapped from table <t_level_ratio>
type LevelRatio struct {
	DistLevel int32   `gorm:"column:dist_level;not null" json:"dist_level"`
	Ratio     float64 `gorm:"column:ratio;not null" json:"ratio"`
}

// TableName LevelRatio's table name
func (*LevelRatio) TableName() string {
	return TableNameLevelRatio
}
