// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLotteryClaimRecord = "t_lottery_claim_record"

// LotteryClaimRecord mapped from table <t_lottery_claim_record>
type LotteryClaimRecord struct {
	RecordID  string    `gorm:"column:record_id;not null;default:gen_ulid()" json:"record_id"`
	RewardIds string    `gorm:"column:reward_ids;not null" json:"reward_ids"`
	TxID      string    `gorm:"column:tx_id" json:"tx_id"`
	State     int32     `gorm:"column:state" json:"state"`
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName LotteryClaimRecord's table name
func (*LotteryClaimRecord) TableName() string {
	return TableNameLotteryClaimRecord
}
