// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMainnetRpcConfig = "t_mainnet_rpc_config"

// MainnetRpcConfig mapped from table <t_mainnet_rpc_config>
type MainnetRpcConfig struct {
	RecordID  string    `gorm:"column:record_id;not null;default:gen_ulid()" json:"recordId"`
	ChainName string    `gorm:"column:chain_name;not null" json:"chainName"`
	RPCURL    string    `gorm:"column:rpc_url;not null" json:"rpcUrl"`
	WssURL    string    `gorm:"column:wss_url;not null" json:"wssUrl"`
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updatedAt"`
}

// TableName MainnetRpcConfig's table name
func (*MainnetRpcConfig) TableName() string {
	return TableNameMainnetRpcConfig
}
