// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePosMissionConfig = "t_pos_mission_config"

// PosMissionConfig mapped from table <t_pos_mission_config>
type PosMissionConfig struct {
	RecordID   string    `gorm:"column:record_id;primaryKey;default:gen_ulid()" json:"record_id"`
	RewardType int32     `gorm:"column:reward_type;not null" json:"reward_type"`
	Starred    bool      `gorm:"column:starred;not null" json:"starred"`
	Rate       float64   `gorm:"column:rate" json:"rate"`
	CreatedAt  time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName PosMissionConfig's table name
func (*PosMissionConfig) TableName() string {
	return TableNamePosMissionConfig
}
