// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePosStarWhitelist = "t_pos_star_whitelist"

// PosStarWhitelist mapped from table <t_pos_star_whitelist>
type PosStarWhitelist struct {
	RecordID      string    `gorm:"column:record_id;primaryKey;default:gen_ulid()" json:"recordId"`
	NativeAccount string    `gorm:"column:native_account;not null" json:"nativeAccount"`
	StarLevel     int32     `gorm:"column:star_level;not null" json:"starLevel"`
	Rate          float64   `gorm:"column:rate" json:"rate"`
	CreatedAt     time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt     time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updatedAt"`
}

// TableName PosStarWhitelist's table name
func (*PosStarWhitelist) TableName() string {
	return TableNamePosStarWhitelist
}
