// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePosReward = "t_pos_reward"

// PosReward mapped from table <t_pos_reward>
type PosReward struct {
	RecordID      string    `gorm:"column:record_id;primaryKey;default:gen_ulid()" json:"record_id"`
	GroupID       string    `gorm:"column:group_id;not null" json:"group_id"`
	NativeAccount string    `gorm:"column:native_account;not null" json:"native_account"`
	StarLevel     int32     `gorm:"column:star_level" json:"star_level"`
	Base          float64   `gorm:"column:base" json:"base"`
	Rate          float64   `gorm:"column:rate" json:"rate"`
	RewardAmount  float64   `gorm:"column:reward_amount" json:"reward_amount"`
	RewardType    int32     `gorm:"column:reward_type" json:"reward_type"`
	RewardState   int32     `gorm:"column:reward_state" json:"reward_state"`
	Starred       bool      `gorm:"column:starred;not null" json:"starred"`
	Pending       bool      `gorm:"column:pending" json:"pending"`
	SnapDay       time.Time `gorm:"column:snap_day;not null" json:"snap_day"`
	CreatedAt     time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName PosReward's table name
func (*PosReward) TableName() string {
	return TableNamePosReward
}
