// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameQnFeeDefault = "t_qn_fee_default"

// QnFeeDefault mapped from table <t_qn_fee_default>
type QnFeeDefault struct {
	ID        int32     `gorm:"column:id;primaryKey" json:"id"`
	Slot      int64     `gorm:"column:slot" json:"slot"`
	LowAvg    float64   `gorm:"column:low_avg" json:"lowAvg"`
	MediumAvg float64   `gorm:"column:medium_avg" json:"mediumAvg"`
	HighAvg   float64   `gorm:"column:high_avg" json:"highAvg"`
	CreatedAt time.Time `gorm:"column:created_at;primaryKey;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updatedAt"`
}

// TableName QnFeeDefault's table name
func (*QnFeeDefault) TableName() string {
	return TableNameQnFeeDefault
}
