// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRewardCodeFee = "t_reward_code_fee"

// RewardCodeFee mapped from table <t_reward_code_fee>
type RewardCodeFee struct {
	Amount    float64   `gorm:"column:amount;primaryKey" json:"amount"`
	CostRate  float64   `gorm:"column:cost_rate;not null" json:"cost_rate"`
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName RewardCodeFee's table name
func (*RewardCodeFee) TableName() string {
	return TableNameRewardCodeFee
}
