// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRewardCodeConfig = "t_reward_code_config"

// RewardCodeConfig mapped from table <t_reward_code_config>
type RewardCodeConfig struct {
	RecordID      string    `gorm:"column:record_id;primaryKey;default:gen_ulid()" json:"recordId"`
	RewardAccount string    `gorm:"column:reward_account;not null" json:"rewardAccount"`
	CostAccount   string    `gorm:"column:cost_account;not null" json:"costAccount"`
	CreatedAt     time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt     time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updatedAt"`
}

// TableName RewardCodeConfig's table name
func (*RewardCodeConfig) TableName() string {
	return TableNameRewardCodeConfig
}
