// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameServiceTx = "t_service_tx"

// ServiceTx mapped from table <t_service_tx>
type ServiceTx struct {
	RecordID      string    `gorm:"column:record_id;primaryKey;default:gen_ulid()" json:"recordId"`
	Service       string    `gorm:"column:service;not null" json:"service"`
	SubService    string    `gorm:"column:sub_service;not null" json:"subService"`
	TxID          string    `gorm:"column:tx_id;not null" json:"txId"`
	TxState       int32     `gorm:"column:tx_state;not null" json:"txState"`
	RetryCount    int32     `gorm:"column:retry_count;not null" json:"retryCount"`
	NextRetryTime time.Time `gorm:"column:next_retry_time;default:CURRENT_TIMESTAMP" json:"nextRetryTime"`
	MaxRetries    int32     `gorm:"column:max_retries;not null;default:5" json:"maxRetries"`
	CreatedAt     time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt     time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updatedAt"`
}

// TableName ServiceTx's table name
func (*ServiceTx) TableName() string {
	return TableNameServiceTx
}
