// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameServiceInfo = "t_service_info"

// ServiceInfo mapped from table <t_service_info>
type ServiceInfo struct {
	Service    string    `gorm:"column:service;not null" json:"service"`
	SubService string    `gorm:"column:sub_service;not null" json:"sub_service"`
	Address    string    `gorm:"column:address;not null" json:"address"`
	Webhook    string    `gorm:"column:webhook;default:NULL" json:"webhook"`
	MqGroup    string    `gorm:"column:mq_group;default:NULL" json:"mq_group"`
	MqTopic    string    `gorm:"column:mq_topic;default:NULL" json:"mq_topic"`
	HookType   int32     `gorm:"column:hook_type;not null" json:"hook_type"`
	Confirm    bool      `gorm:"column:confirm;not null;default:true" json:"confirm"`
	MultiSign  bool      `gorm:"column:multi_sign;not null;default:true" json:"multi_sign"`
	CreatedAt  time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName ServiceInfo's table name
func (*ServiceInfo) TableName() string {
	return TableNameServiceInfo
}
