// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameStakeInviteRate = "t_stake_invite_rate"

// StakeInviteRate mapped from table <t_stake_invite_rate>
type StakeInviteRate struct {
	Level int32   `gorm:"column:level;primaryKey" json:"level"`
	Rate  float64 `gorm:"column:rate;not null" json:"rate"`
}

// TableName StakeInviteRate's table name
func (*StakeInviteRate) TableName() string {
	return TableNameStakeInviteRate
}
