// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameStakeSnapShotDefault = "t_stake_snap_shot_default"

// StakeSnapShotDefault mapped from table <t_stake_snap_shot_default>
type StakeSnapShotDefault struct {
	RecordID      string    `gorm:"column:record_id;primaryKey;default:gen_ulid()" json:"recordId"`
	NativeAccount string    `gorm:"column:native_account;not null" json:"nativeAccount"`
	Amount        float64   `gorm:"column:amount" json:"amount"`
	StakeType     int32     `gorm:"column:stake_type;not null" json:"stakeType"`
	SnapDay       time.Time `gorm:"column:snap_day;primaryKey" json:"snapDay"`
	CreatedAt     time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt     time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updatedAt"`
}

// TableName StakeSnapShotDefault's table name
func (*StakeSnapShotDefault) TableName() string {
	return TableNameStakeSnapShotDefault
}
