// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameStakeLeaderRewardClaim = "t_stake_leader_reward_claim"

// StakeLeaderRewardClaim mapped from table <t_stake_leader_reward_claim>
type StakeLeaderRewardClaim struct {
	RecordID      string    `gorm:"column:record_id;primaryKey;default:gen_ulid()" json:"recordId"`
	NativeAccount string    `gorm:"column:native_account;not null" json:"nativeAccount"`
	RewardIds     string    `gorm:"column:reward_ids;not null" json:"rewardIds"`
	TxID          string    `gorm:"column:tx_id" json:"txId"`
	TxState       int32     `gorm:"column:tx_state" json:"txState"`
	CreatedAt     time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt     time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updatedAt"`
}

// TableName StakeLeaderRewardClaim's table name
func (*StakeLeaderRewardClaim) TableName() string {
	return TableNameStakeLeaderRewardClaim
}
