// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameStakeReward = "t_stake_reward"

// StakeReward mapped from table <t_stake_reward>
type StakeReward struct {
	RecordID      string    `gorm:"column:record_id;primaryKey;default:gen_ulid()" json:"recordId"`
	GroupID       string    `gorm:"column:group_id;not null" json:"groupId"`
	NativeAccount string    `gorm:"column:native_account;not null" json:"nativeAccount"`
	StarLevel     int32     `gorm:"column:star_level" json:"starLevel"`
	Base          float64   `gorm:"column:base" json:"base"`
	Rate          float64   `gorm:"column:rate" json:"rate"`
	RewardAmount  float64   `gorm:"column:reward_amount" json:"rewardAmount"`
	StakeType     int32     `gorm:"column:stake_type;not null" json:"stakeType"`
	RewardType    int32     `gorm:"column:reward_type;not null" json:"rewardType"`
	RewardState   int32     `gorm:"column:reward_state" json:"rewardState"`
	Starred       bool      `gorm:"column:starred;not null" json:"starred"`
	TxID          string    `gorm:"column:tx_id" json:"txId"`
	Pending       bool      `gorm:"column:pending" json:"pending"`
	SnapDay       time.Time `gorm:"column:snap_day;not null" json:"snapDay"`
	CreatedAt     time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt     time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updatedAt"`
}

// TableName StakeReward's table name
func (*StakeReward) TableName() string {
	return TableNameStakeReward
}
