// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameStakeTokenPool = "t_stake_token_pool"

// StakeTokenPool mapped from table <t_stake_token_pool>
type StakeTokenPool struct {
	SourceAccount    string `gorm:"column:source_account;not null" json:"source_account"`
	FromTokenAccount string `gorm:"column:from_token_account;not null" json:"from_token_account"`
}

// TableName StakeTokenPool's table name
func (*StakeTokenPool) TableName() string {
	return TableNameStakeTokenPool
}
