// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameStakeAreaLeaderRewardClaimRecord = "t_stake_area_leader_reward_claim_record"

// StakeAreaLeaderRewardClaimRecord mapped from table <t_stake_area_leader_reward_claim_record>
type StakeAreaLeaderRewardClaimRecord struct {
	RecordID             string    `gorm:"column:record_id;primaryKey;default:gen_ulid()" json:"record_id"`
	NativeAccount        string    `gorm:"column:native_account;not null" json:"native_account"`
	RewardIds            string    `gorm:"column:reward_ids;not null" json:"reward_ids"`
	TxID                 string    `gorm:"column:tx_id" json:"tx_id"`
	RefBlockHash         string    `gorm:"column:ref_block_hash" json:"ref_block_hash"`
	LastValidBlockHeight int64     `gorm:"column:last_valid_block_height" json:"last_valid_block_height"`
	State                int32     `gorm:"column:state" json:"state"`
	CreateTime           time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime           time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName StakeAreaLeaderRewardClaimRecord's table name
func (*StakeAreaLeaderRewardClaimRecord) TableName() string {
	return TableNameStakeAreaLeaderRewardClaimRecord
}
