// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameStakeBuyToken = "t_stake_buy_token"

// StakeBuyToken mapped from table <t_stake_buy_token>
type StakeBuyToken struct {
	TxID            string    `gorm:"column:tx_id;not null" json:"tx_id"`
	Slot            float64   `gorm:"column:slot;not null" json:"slot"`
	Source          string    `gorm:"column:source;not null" json:"source"`
	Destination     string    `gorm:"column:destination;not null" json:"destination"`
	Amount          float64   `gorm:"column:amount;not null" json:"amount"`
	Locked          bool      `gorm:"column:locked;not null" json:"locked"`
	LockedBy        string    `gorm:"column:locked_by" json:"locked_by"`
	LockedAt        time.Time `gorm:"column:locked_at" json:"locked_at"`
	StakedAmount    float64   `gorm:"column:staked_amount;not null" json:"staked_amount"`
	RemainingAmount float64   `gorm:"column:remaining_amount;not null" json:"remaining_amount"`
	CreatedAt       time.Time `gorm:"column:created_at;default:now()" json:"created_at"`
}

// TableName StakeBuyToken's table name
func (*StakeBuyToken) TableName() string {
	return TableNameStakeBuyToken
}
