// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTakeTokenConfig = "t_take_token_config"

// TakeTokenConfig mapped from table <t_take_token_config>
type TakeTokenConfig struct {
	RecordID      string    `gorm:"column:record_id;not null;default:gen_ulid()" json:"recordId"`
	InviteCode    string    `gorm:"column:invite_code;default:NULL" json:"inviteCode"`
	RewardAccount string    `gorm:"column:reward_account;not null" json:"rewardAccount"`
	CostAccount   string    `gorm:"column:cost_account;not null" json:"costAccount"`
	Amount        float64   `gorm:"column:amount;not null" json:"amount"`
	InviteAmount  float64   `gorm:"column:invite_amount;not null" json:"inviteAmount"`
	CostFeeRate   float64   `gorm:"column:cost_fee_rate;not null" json:"costFeeRate"`
	InvitedRate   float64   `gorm:"column:invited_rate;not null" json:"invitedRate"`
	MaxCostFee    float64   `gorm:"column:max_cost_fee;not null" json:"maxCostFee"`
	IsDefault     bool      `gorm:"column:is_default" json:"isDefault"`
	RewardInviter bool      `gorm:"column:reward_inviter;default:true" json:"rewardInviter"`
	Invited       bool      `gorm:"column:invited;default:true" json:"invited"`
	CreatedAt     time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt     time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updatedAt"`
}

// TableName TakeTokenConfig's table name
func (*TakeTokenConfig) TableName() string {
	return TableNameTakeTokenConfig
}
