CREATE EXTENSION IF NOT EXISTS ulid WITH SCHEMA public;

-- 创建通用触发器函数：实现updated_at字段自动更新（PostgreSQL替代ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
RETURN NEW;
END;
$$ LANGUAGE plpgsql;



GRANT USAGE ON SCHEMA public TO meme_server;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO meme_server;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO meme_server;
