// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTradeOrder = "exchange.t_trade_order"

// TradeOrder mapped from table <exchange.t_trade_order>
type TradeOrder struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增主键" json:"id"`             // 自增主键
	UserID    int64     `gorm:"column:user_id;not null;comment:关联account.t_user_info的id" json:"user_id"`    // 关联account.t_user_info的id
	OrderNo   string    `gorm:"column:order_no;not null;comment:订单编号（唯一）" json:"order_no"`                  // 订单编号（唯一）
	Amount    float64   `gorm:"column:amount;not null;comment:订单金额（保留2位小数）" json:"amount"`                  // 订单金额（保留2位小数）
	Status    int16     `gorm:"column:status;comment:订单状态：0-待支付 1-已支付 2-已取消 3-已完成" json:"status"`           // 订单状态：0-待支付 1-已支付 2-已取消 3-已完成
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
}

// TableName TradeOrder's table name
func (*TradeOrder) TableName() string {
	return TableNameTradeOrder
}
