app:
  name: base-api
  port: 1100
database:
  dbname: oshit_db
  host: localhost
  password: ENC~GBVqLKtpUw0RMQOo1G2YbkzcUg7Ou4Gfm0W1jZdyy32VZtP/TJetJ0hXOUasRRzb
  port: 5432
  sslmode: disable
  user: postgres
dubbo:
  port: 20880
kafka:
  brokers:
    - localhost:9092
nacos:
  host: 127.0.0.1
  username: ENC~1tIK+CyqorggOgWriIcBQtIkfzM903GHguHpQaHeihVcX7qMq4fcIH1eIcVs+mDr
  password: ENC~iUkzP43GuCeTE+NgXsOhVWhrYNla4B6scKcPx6uDUDKuCK2Vd9cNr2H0iT1Xlldx
  subscribe_configs:
    base_runtime:
      data_id: base-runtime.yaml
      group: oshit-go
    service_registry:
      data_id: base-service-registry.yaml
      group: oshit-go
redis:
  hosts: localhost:6379
  password: null