app:
  name: "base-api"
  port: 1100

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "oshit_db"
  sslmode: "disable"

redis:
  hosts: localhost:6379
  password:

#redis:
#  master-name: mymaster
#  hosts: 172.31.7.31:26379,172.31.0.184:26379,172.31.1.124:26379
#  password:

kafka:
  brokers:
    - "localhost:9092"

dubbo:
  port: 20880

nacos:
  host: "127.0.0.1"
  username: "nacos"
  password: "lJPQwjjO9k"
  subscribe_configs:
    base_runtime:
      data_id: "base-runtime.yaml"
      group: "oshit-go"
    service_registry:
      data_id: "base-service-registry.yaml"
      group: "oshit-go"
