// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                   = new(Query)
	AwsConfig           *awsConfig
	ChainConfig         *chainConfig
	DailyClaimStats     *dailyClaimStats
	DiscountRate        *discountRate
	ExcludeAccount      *excludeAccount
	FeeStatistics       *feeStatistics
	FeeTolerance        *feeTolerance
	FundFlow            *fundFlow
	GiveTokenConfig     *giveTokenConfig
	GiveTokenRecord     *giveTokenRecord
	HackerAccount       *hackerAccount
	InviteRelation      *inviteRelation
	LevelDist           *levelDist
	LevelRatio          *levelRatio
	LotteryClaimRecord  *lotteryClaimRecord
	LotteryReward       *lotteryReward
	NativeAccountInfo   *nativeAccountInfo
	QnFee               *qnFee
	RewardKeyConfig     *rewardKeyConfig
	ServiceInfo         *serviceInfo
	ServiceKey          *serviceKey
	ServiceTx           *serviceTx
	SystemConfig        *systemConfig
	TakeTokenConfig     *takeTokenConfig
	TakeTokenRecord     *takeTokenRecord
	TokenConfig         *tokenConfig
	TxScanInfo          *txScanInfo
	UserWalletRpcConfig *userWalletRpcConfig
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	AwsConfig = &Q.AwsConfig
	ChainConfig = &Q.ChainConfig
	DailyClaimStats = &Q.DailyClaimStats
	DiscountRate = &Q.DiscountRate
	ExcludeAccount = &Q.ExcludeAccount
	FeeStatistics = &Q.FeeStatistics
	FeeTolerance = &Q.FeeTolerance
	FundFlow = &Q.FundFlow
	GiveTokenConfig = &Q.GiveTokenConfig
	GiveTokenRecord = &Q.GiveTokenRecord
	HackerAccount = &Q.HackerAccount
	InviteRelation = &Q.InviteRelation
	LevelDist = &Q.LevelDist
	LevelRatio = &Q.LevelRatio
	LotteryClaimRecord = &Q.LotteryClaimRecord
	LotteryReward = &Q.LotteryReward
	NativeAccountInfo = &Q.NativeAccountInfo
	QnFee = &Q.QnFee
	RewardKeyConfig = &Q.RewardKeyConfig
	ServiceInfo = &Q.ServiceInfo
	ServiceKey = &Q.ServiceKey
	ServiceTx = &Q.ServiceTx
	SystemConfig = &Q.SystemConfig
	TakeTokenConfig = &Q.TakeTokenConfig
	TakeTokenRecord = &Q.TakeTokenRecord
	TokenConfig = &Q.TokenConfig
	TxScanInfo = &Q.TxScanInfo
	UserWalletRpcConfig = &Q.UserWalletRpcConfig
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                  db,
		AwsConfig:           newAwsConfig(db, opts...),
		ChainConfig:         newChainConfig(db, opts...),
		DailyClaimStats:     newDailyClaimStats(db, opts...),
		DiscountRate:        newDiscountRate(db, opts...),
		ExcludeAccount:      newExcludeAccount(db, opts...),
		FeeStatistics:       newFeeStatistics(db, opts...),
		FeeTolerance:        newFeeTolerance(db, opts...),
		FundFlow:            newFundFlow(db, opts...),
		GiveTokenConfig:     newGiveTokenConfig(db, opts...),
		GiveTokenRecord:     newGiveTokenRecord(db, opts...),
		HackerAccount:       newHackerAccount(db, opts...),
		InviteRelation:      newInviteRelation(db, opts...),
		LevelDist:           newLevelDist(db, opts...),
		LevelRatio:          newLevelRatio(db, opts...),
		LotteryClaimRecord:  newLotteryClaimRecord(db, opts...),
		LotteryReward:       newLotteryReward(db, opts...),
		NativeAccountInfo:   newNativeAccountInfo(db, opts...),
		QnFee:               newQnFee(db, opts...),
		RewardKeyConfig:     newRewardKeyConfig(db, opts...),
		ServiceInfo:         newServiceInfo(db, opts...),
		ServiceKey:          newServiceKey(db, opts...),
		ServiceTx:           newServiceTx(db, opts...),
		SystemConfig:        newSystemConfig(db, opts...),
		TakeTokenConfig:     newTakeTokenConfig(db, opts...),
		TakeTokenRecord:     newTakeTokenRecord(db, opts...),
		TokenConfig:         newTokenConfig(db, opts...),
		TxScanInfo:          newTxScanInfo(db, opts...),
		UserWalletRpcConfig: newUserWalletRpcConfig(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	AwsConfig           awsConfig
	ChainConfig         chainConfig
	DailyClaimStats     dailyClaimStats
	DiscountRate        discountRate
	ExcludeAccount      excludeAccount
	FeeStatistics       feeStatistics
	FeeTolerance        feeTolerance
	FundFlow            fundFlow
	GiveTokenConfig     giveTokenConfig
	GiveTokenRecord     giveTokenRecord
	HackerAccount       hackerAccount
	InviteRelation      inviteRelation
	LevelDist           levelDist
	LevelRatio          levelRatio
	LotteryClaimRecord  lotteryClaimRecord
	LotteryReward       lotteryReward
	NativeAccountInfo   nativeAccountInfo
	QnFee               qnFee
	RewardKeyConfig     rewardKeyConfig
	ServiceInfo         serviceInfo
	ServiceKey          serviceKey
	ServiceTx           serviceTx
	SystemConfig        systemConfig
	TakeTokenConfig     takeTokenConfig
	TakeTokenRecord     takeTokenRecord
	TokenConfig         tokenConfig
	TxScanInfo          txScanInfo
	UserWalletRpcConfig userWalletRpcConfig
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                  db,
		AwsConfig:           q.AwsConfig.clone(db),
		ChainConfig:         q.ChainConfig.clone(db),
		DailyClaimStats:     q.DailyClaimStats.clone(db),
		DiscountRate:        q.DiscountRate.clone(db),
		ExcludeAccount:      q.ExcludeAccount.clone(db),
		FeeStatistics:       q.FeeStatistics.clone(db),
		FeeTolerance:        q.FeeTolerance.clone(db),
		FundFlow:            q.FundFlow.clone(db),
		GiveTokenConfig:     q.GiveTokenConfig.clone(db),
		GiveTokenRecord:     q.GiveTokenRecord.clone(db),
		HackerAccount:       q.HackerAccount.clone(db),
		InviteRelation:      q.InviteRelation.clone(db),
		LevelDist:           q.LevelDist.clone(db),
		LevelRatio:          q.LevelRatio.clone(db),
		LotteryClaimRecord:  q.LotteryClaimRecord.clone(db),
		LotteryReward:       q.LotteryReward.clone(db),
		NativeAccountInfo:   q.NativeAccountInfo.clone(db),
		QnFee:               q.QnFee.clone(db),
		RewardKeyConfig:     q.RewardKeyConfig.clone(db),
		ServiceInfo:         q.ServiceInfo.clone(db),
		ServiceKey:          q.ServiceKey.clone(db),
		ServiceTx:           q.ServiceTx.clone(db),
		SystemConfig:        q.SystemConfig.clone(db),
		TakeTokenConfig:     q.TakeTokenConfig.clone(db),
		TakeTokenRecord:     q.TakeTokenRecord.clone(db),
		TokenConfig:         q.TokenConfig.clone(db),
		TxScanInfo:          q.TxScanInfo.clone(db),
		UserWalletRpcConfig: q.UserWalletRpcConfig.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                  db,
		AwsConfig:           q.AwsConfig.replaceDB(db),
		ChainConfig:         q.ChainConfig.replaceDB(db),
		DailyClaimStats:     q.DailyClaimStats.replaceDB(db),
		DiscountRate:        q.DiscountRate.replaceDB(db),
		ExcludeAccount:      q.ExcludeAccount.replaceDB(db),
		FeeStatistics:       q.FeeStatistics.replaceDB(db),
		FeeTolerance:        q.FeeTolerance.replaceDB(db),
		FundFlow:            q.FundFlow.replaceDB(db),
		GiveTokenConfig:     q.GiveTokenConfig.replaceDB(db),
		GiveTokenRecord:     q.GiveTokenRecord.replaceDB(db),
		HackerAccount:       q.HackerAccount.replaceDB(db),
		InviteRelation:      q.InviteRelation.replaceDB(db),
		LevelDist:           q.LevelDist.replaceDB(db),
		LevelRatio:          q.LevelRatio.replaceDB(db),
		LotteryClaimRecord:  q.LotteryClaimRecord.replaceDB(db),
		LotteryReward:       q.LotteryReward.replaceDB(db),
		NativeAccountInfo:   q.NativeAccountInfo.replaceDB(db),
		QnFee:               q.QnFee.replaceDB(db),
		RewardKeyConfig:     q.RewardKeyConfig.replaceDB(db),
		ServiceInfo:         q.ServiceInfo.replaceDB(db),
		ServiceKey:          q.ServiceKey.replaceDB(db),
		ServiceTx:           q.ServiceTx.replaceDB(db),
		SystemConfig:        q.SystemConfig.replaceDB(db),
		TakeTokenConfig:     q.TakeTokenConfig.replaceDB(db),
		TakeTokenRecord:     q.TakeTokenRecord.replaceDB(db),
		TokenConfig:         q.TokenConfig.replaceDB(db),
		TxScanInfo:          q.TxScanInfo.replaceDB(db),
		UserWalletRpcConfig: q.UserWalletRpcConfig.replaceDB(db),
	}
}

type queryCtx struct {
	AwsConfig           IAwsConfigDo
	ChainConfig         IChainConfigDo
	DailyClaimStats     IDailyClaimStatsDo
	DiscountRate        IDiscountRateDo
	ExcludeAccount      IExcludeAccountDo
	FeeStatistics       IFeeStatisticsDo
	FeeTolerance        IFeeToleranceDo
	FundFlow            IFundFlowDo
	GiveTokenConfig     IGiveTokenConfigDo
	GiveTokenRecord     IGiveTokenRecordDo
	HackerAccount       IHackerAccountDo
	InviteRelation      IInviteRelationDo
	LevelDist           ILevelDistDo
	LevelRatio          ILevelRatioDo
	LotteryClaimRecord  ILotteryClaimRecordDo
	LotteryReward       ILotteryRewardDo
	NativeAccountInfo   INativeAccountInfoDo
	QnFee               IQnFeeDo
	RewardKeyConfig     IRewardKeyConfigDo
	ServiceInfo         IServiceInfoDo
	ServiceKey          IServiceKeyDo
	ServiceTx           IServiceTxDo
	SystemConfig        ISystemConfigDo
	TakeTokenConfig     ITakeTokenConfigDo
	TakeTokenRecord     ITakeTokenRecordDo
	TokenConfig         ITokenConfigDo
	TxScanInfo          ITxScanInfoDo
	UserWalletRpcConfig IUserWalletRpcConfigDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		AwsConfig:           q.AwsConfig.WithContext(ctx),
		ChainConfig:         q.ChainConfig.WithContext(ctx),
		DailyClaimStats:     q.DailyClaimStats.WithContext(ctx),
		DiscountRate:        q.DiscountRate.WithContext(ctx),
		ExcludeAccount:      q.ExcludeAccount.WithContext(ctx),
		FeeStatistics:       q.FeeStatistics.WithContext(ctx),
		FeeTolerance:        q.FeeTolerance.WithContext(ctx),
		FundFlow:            q.FundFlow.WithContext(ctx),
		GiveTokenConfig:     q.GiveTokenConfig.WithContext(ctx),
		GiveTokenRecord:     q.GiveTokenRecord.WithContext(ctx),
		HackerAccount:       q.HackerAccount.WithContext(ctx),
		InviteRelation:      q.InviteRelation.WithContext(ctx),
		LevelDist:           q.LevelDist.WithContext(ctx),
		LevelRatio:          q.LevelRatio.WithContext(ctx),
		LotteryClaimRecord:  q.LotteryClaimRecord.WithContext(ctx),
		LotteryReward:       q.LotteryReward.WithContext(ctx),
		NativeAccountInfo:   q.NativeAccountInfo.WithContext(ctx),
		QnFee:               q.QnFee.WithContext(ctx),
		RewardKeyConfig:     q.RewardKeyConfig.WithContext(ctx),
		ServiceInfo:         q.ServiceInfo.WithContext(ctx),
		ServiceKey:          q.ServiceKey.WithContext(ctx),
		ServiceTx:           q.ServiceTx.WithContext(ctx),
		SystemConfig:        q.SystemConfig.WithContext(ctx),
		TakeTokenConfig:     q.TakeTokenConfig.WithContext(ctx),
		TakeTokenRecord:     q.TakeTokenRecord.WithContext(ctx),
		TokenConfig:         q.TokenConfig.WithContext(ctx),
		TxScanInfo:          q.TxScanInfo.WithContext(ctx),
		UserWalletRpcConfig: q.UserWalletRpcConfig.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
