// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                        = new(Query)
	AwsConfig                *awsConfig
	CampaignExchangeConfig   *campaignExchangeConfig
	CampaignExchangeRecord   *campaignExchangeRecord
	ChainConfig              *chainConfig
	DailyClaimStats          *dailyClaimStats
	DiscountRate             *discountRate
	ExcludeAccount           *excludeAccount
	FeeStatistics            *feeStatistics
	FeeTolerance             *feeTolerance
	FundFlow                 *fundFlow
	GiveTokenConfig          *giveTokenConfig
	GiveTokenRecord          *giveTokenRecord
	GlobalDailyExchangeLimit *globalDailyExchangeLimit
	HackerAccount            *hackerAccount
	InviteRelation           *inviteRelation
	LevelDist                *levelDist
	LevelRatio               *levelRatio
	LotteryClaimRecord       *lotteryClaimRecord
	LotteryReward            *lotteryReward
	MainnetRpcConfig         *mainnetRpcConfig
	NativeAccountInfo        *nativeAccountInfo
	PosMissionConfig         *posMissionConfig
	PosReward                *posReward
	PosRewardClaimRecord     *posRewardClaimRecord
	PosRewardConfig          *posRewardConfig
	PosRpcConfig             *posRpcConfig
	PosSnapShot              *posSnapShot
	PosStarLevelRule         *posStarLevelRule
	PosStarWhitelist         *posStarWhitelist
	QnFee                    *qnFee
	RewardCode               *rewardCode
	RewardCodeConfig         *rewardCodeConfig
	RewardCodeFee            *rewardCodeFee
	RewardKeyConfig          *rewardKeyConfig
	ServiceInfo              *serviceInfo
	ServiceKey               *serviceKey
	ServiceTx                *serviceTx
	StakeAmmConfig           *stakeAmmConfig
	StakeBuyToken            *stakeBuyToken
	StakeFixRateConfig       *stakeFixRateConfig
	StakeInviteDist          *stakeInviteDist
	StakeInviteRate          *stakeInviteRate
	StakeLeader              *stakeLeader
	StakeLeaderReward        *stakeLeaderReward
	StakeLeaderRewardClaim   *stakeLeaderRewardClaim
	StakeLeaderRewardConfig  *stakeLeaderRewardConfig
	StakeRecord              *stakeRecord
	StakeReward              *stakeReward
	StakeRewardClaim         *stakeRewardClaim
	StakeRewardConfig        *stakeRewardConfig
	StakeSnapShot            *stakeSnapShot
	StakeStarLevelRule       *stakeStarLevelRule
	StakeStarWhitelist       *stakeStarWhitelist
	StakeTokenPool           *stakeTokenPool
	StakeTotalLeader         *stakeTotalLeader
	SystemConfig             *systemConfig
	TakeTokenConfig          *takeTokenConfig
	TakeTokenRecord          *takeTokenRecord
	TokenConfig              *tokenConfig
	TxScanInfo               *txScanInfo
	UserDailyExchangeQuota   *userDailyExchangeQuota
	UserWalletRpcConfig      *userWalletRpcConfig
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	AwsConfig = &Q.AwsConfig
	CampaignExchangeConfig = &Q.CampaignExchangeConfig
	CampaignExchangeRecord = &Q.CampaignExchangeRecord
	ChainConfig = &Q.ChainConfig
	DailyClaimStats = &Q.DailyClaimStats
	DiscountRate = &Q.DiscountRate
	ExcludeAccount = &Q.ExcludeAccount
	FeeStatistics = &Q.FeeStatistics
	FeeTolerance = &Q.FeeTolerance
	FundFlow = &Q.FundFlow
	GiveTokenConfig = &Q.GiveTokenConfig
	GiveTokenRecord = &Q.GiveTokenRecord
	GlobalDailyExchangeLimit = &Q.GlobalDailyExchangeLimit
	HackerAccount = &Q.HackerAccount
	InviteRelation = &Q.InviteRelation
	LevelDist = &Q.LevelDist
	LevelRatio = &Q.LevelRatio
	LotteryClaimRecord = &Q.LotteryClaimRecord
	LotteryReward = &Q.LotteryReward
	MainnetRpcConfig = &Q.MainnetRpcConfig
	NativeAccountInfo = &Q.NativeAccountInfo
	PosMissionConfig = &Q.PosMissionConfig
	PosReward = &Q.PosReward
	PosRewardClaimRecord = &Q.PosRewardClaimRecord
	PosRewardConfig = &Q.PosRewardConfig
	PosRpcConfig = &Q.PosRpcConfig
	PosSnapShot = &Q.PosSnapShot
	PosStarLevelRule = &Q.PosStarLevelRule
	PosStarWhitelist = &Q.PosStarWhitelist
	QnFee = &Q.QnFee
	RewardCode = &Q.RewardCode
	RewardCodeConfig = &Q.RewardCodeConfig
	RewardCodeFee = &Q.RewardCodeFee
	RewardKeyConfig = &Q.RewardKeyConfig
	ServiceInfo = &Q.ServiceInfo
	ServiceKey = &Q.ServiceKey
	ServiceTx = &Q.ServiceTx
	StakeAmmConfig = &Q.StakeAmmConfig
	StakeBuyToken = &Q.StakeBuyToken
	StakeFixRateConfig = &Q.StakeFixRateConfig
	StakeInviteDist = &Q.StakeInviteDist
	StakeInviteRate = &Q.StakeInviteRate
	StakeLeader = &Q.StakeLeader
	StakeLeaderReward = &Q.StakeLeaderReward
	StakeLeaderRewardClaim = &Q.StakeLeaderRewardClaim
	StakeLeaderRewardConfig = &Q.StakeLeaderRewardConfig
	StakeRecord = &Q.StakeRecord
	StakeReward = &Q.StakeReward
	StakeRewardClaim = &Q.StakeRewardClaim
	StakeRewardConfig = &Q.StakeRewardConfig
	StakeSnapShot = &Q.StakeSnapShot
	StakeStarLevelRule = &Q.StakeStarLevelRule
	StakeStarWhitelist = &Q.StakeStarWhitelist
	StakeTokenPool = &Q.StakeTokenPool
	StakeTotalLeader = &Q.StakeTotalLeader
	SystemConfig = &Q.SystemConfig
	TakeTokenConfig = &Q.TakeTokenConfig
	TakeTokenRecord = &Q.TakeTokenRecord
	TokenConfig = &Q.TokenConfig
	TxScanInfo = &Q.TxScanInfo
	UserDailyExchangeQuota = &Q.UserDailyExchangeQuota
	UserWalletRpcConfig = &Q.UserWalletRpcConfig
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                       db,
		AwsConfig:                newAwsConfig(db, opts...),
		CampaignExchangeConfig:   newCampaignExchangeConfig(db, opts...),
		CampaignExchangeRecord:   newCampaignExchangeRecord(db, opts...),
		ChainConfig:              newChainConfig(db, opts...),
		DailyClaimStats:          newDailyClaimStats(db, opts...),
		DiscountRate:             newDiscountRate(db, opts...),
		ExcludeAccount:           newExcludeAccount(db, opts...),
		FeeStatistics:            newFeeStatistics(db, opts...),
		FeeTolerance:             newFeeTolerance(db, opts...),
		FundFlow:                 newFundFlow(db, opts...),
		GiveTokenConfig:          newGiveTokenConfig(db, opts...),
		GiveTokenRecord:          newGiveTokenRecord(db, opts...),
		GlobalDailyExchangeLimit: newGlobalDailyExchangeLimit(db, opts...),
		HackerAccount:            newHackerAccount(db, opts...),
		InviteRelation:           newInviteRelation(db, opts...),
		LevelDist:                newLevelDist(db, opts...),
		LevelRatio:               newLevelRatio(db, opts...),
		LotteryClaimRecord:       newLotteryClaimRecord(db, opts...),
		LotteryReward:            newLotteryReward(db, opts...),
		MainnetRpcConfig:         newMainnetRpcConfig(db, opts...),
		NativeAccountInfo:        newNativeAccountInfo(db, opts...),
		PosMissionConfig:         newPosMissionConfig(db, opts...),
		PosReward:                newPosReward(db, opts...),
		PosRewardClaimRecord:     newPosRewardClaimRecord(db, opts...),
		PosRewardConfig:          newPosRewardConfig(db, opts...),
		PosRpcConfig:             newPosRpcConfig(db, opts...),
		PosSnapShot:              newPosSnapShot(db, opts...),
		PosStarLevelRule:         newPosStarLevelRule(db, opts...),
		PosStarWhitelist:         newPosStarWhitelist(db, opts...),
		QnFee:                    newQnFee(db, opts...),
		RewardCode:               newRewardCode(db, opts...),
		RewardCodeConfig:         newRewardCodeConfig(db, opts...),
		RewardCodeFee:            newRewardCodeFee(db, opts...),
		RewardKeyConfig:          newRewardKeyConfig(db, opts...),
		ServiceInfo:              newServiceInfo(db, opts...),
		ServiceKey:               newServiceKey(db, opts...),
		ServiceTx:                newServiceTx(db, opts...),
		StakeAmmConfig:           newStakeAmmConfig(db, opts...),
		StakeBuyToken:            newStakeBuyToken(db, opts...),
		StakeFixRateConfig:       newStakeFixRateConfig(db, opts...),
		StakeInviteDist:          newStakeInviteDist(db, opts...),
		StakeInviteRate:          newStakeInviteRate(db, opts...),
		StakeLeader:              newStakeLeader(db, opts...),
		StakeLeaderReward:        newStakeLeaderReward(db, opts...),
		StakeLeaderRewardClaim:   newStakeLeaderRewardClaim(db, opts...),
		StakeLeaderRewardConfig:  newStakeLeaderRewardConfig(db, opts...),
		StakeRecord:              newStakeRecord(db, opts...),
		StakeReward:              newStakeReward(db, opts...),
		StakeRewardClaim:         newStakeRewardClaim(db, opts...),
		StakeRewardConfig:        newStakeRewardConfig(db, opts...),
		StakeSnapShot:            newStakeSnapShot(db, opts...),
		StakeStarLevelRule:       newStakeStarLevelRule(db, opts...),
		StakeStarWhitelist:       newStakeStarWhitelist(db, opts...),
		StakeTokenPool:           newStakeTokenPool(db, opts...),
		StakeTotalLeader:         newStakeTotalLeader(db, opts...),
		SystemConfig:             newSystemConfig(db, opts...),
		TakeTokenConfig:          newTakeTokenConfig(db, opts...),
		TakeTokenRecord:          newTakeTokenRecord(db, opts...),
		TokenConfig:              newTokenConfig(db, opts...),
		TxScanInfo:               newTxScanInfo(db, opts...),
		UserDailyExchangeQuota:   newUserDailyExchangeQuota(db, opts...),
		UserWalletRpcConfig:      newUserWalletRpcConfig(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	AwsConfig                awsConfig
	CampaignExchangeConfig   campaignExchangeConfig
	CampaignExchangeRecord   campaignExchangeRecord
	ChainConfig              chainConfig
	DailyClaimStats          dailyClaimStats
	DiscountRate             discountRate
	ExcludeAccount           excludeAccount
	FeeStatistics            feeStatistics
	FeeTolerance             feeTolerance
	FundFlow                 fundFlow
	GiveTokenConfig          giveTokenConfig
	GiveTokenRecord          giveTokenRecord
	GlobalDailyExchangeLimit globalDailyExchangeLimit
	HackerAccount            hackerAccount
	InviteRelation           inviteRelation
	LevelDist                levelDist
	LevelRatio               levelRatio
	LotteryClaimRecord       lotteryClaimRecord
	LotteryReward            lotteryReward
	MainnetRpcConfig         mainnetRpcConfig
	NativeAccountInfo        nativeAccountInfo
	PosMissionConfig         posMissionConfig
	PosReward                posReward
	PosRewardClaimRecord     posRewardClaimRecord
	PosRewardConfig          posRewardConfig
	PosRpcConfig             posRpcConfig
	PosSnapShot              posSnapShot
	PosStarLevelRule         posStarLevelRule
	PosStarWhitelist         posStarWhitelist
	QnFee                    qnFee
	RewardCode               rewardCode
	RewardCodeConfig         rewardCodeConfig
	RewardCodeFee            rewardCodeFee
	RewardKeyConfig          rewardKeyConfig
	ServiceInfo              serviceInfo
	ServiceKey               serviceKey
	ServiceTx                serviceTx
	StakeAmmConfig           stakeAmmConfig
	StakeBuyToken            stakeBuyToken
	StakeFixRateConfig       stakeFixRateConfig
	StakeInviteDist          stakeInviteDist
	StakeInviteRate          stakeInviteRate
	StakeLeader              stakeLeader
	StakeLeaderReward        stakeLeaderReward
	StakeLeaderRewardClaim   stakeLeaderRewardClaim
	StakeLeaderRewardConfig  stakeLeaderRewardConfig
	StakeRecord              stakeRecord
	StakeReward              stakeReward
	StakeRewardClaim         stakeRewardClaim
	StakeRewardConfig        stakeRewardConfig
	StakeSnapShot            stakeSnapShot
	StakeStarLevelRule       stakeStarLevelRule
	StakeStarWhitelist       stakeStarWhitelist
	StakeTokenPool           stakeTokenPool
	StakeTotalLeader         stakeTotalLeader
	SystemConfig             systemConfig
	TakeTokenConfig          takeTokenConfig
	TakeTokenRecord          takeTokenRecord
	TokenConfig              tokenConfig
	TxScanInfo               txScanInfo
	UserDailyExchangeQuota   userDailyExchangeQuota
	UserWalletRpcConfig      userWalletRpcConfig
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                       db,
		AwsConfig:                q.AwsConfig.clone(db),
		CampaignExchangeConfig:   q.CampaignExchangeConfig.clone(db),
		CampaignExchangeRecord:   q.CampaignExchangeRecord.clone(db),
		ChainConfig:              q.ChainConfig.clone(db),
		DailyClaimStats:          q.DailyClaimStats.clone(db),
		DiscountRate:             q.DiscountRate.clone(db),
		ExcludeAccount:           q.ExcludeAccount.clone(db),
		FeeStatistics:            q.FeeStatistics.clone(db),
		FeeTolerance:             q.FeeTolerance.clone(db),
		FundFlow:                 q.FundFlow.clone(db),
		GiveTokenConfig:          q.GiveTokenConfig.clone(db),
		GiveTokenRecord:          q.GiveTokenRecord.clone(db),
		GlobalDailyExchangeLimit: q.GlobalDailyExchangeLimit.clone(db),
		HackerAccount:            q.HackerAccount.clone(db),
		InviteRelation:           q.InviteRelation.clone(db),
		LevelDist:                q.LevelDist.clone(db),
		LevelRatio:               q.LevelRatio.clone(db),
		LotteryClaimRecord:       q.LotteryClaimRecord.clone(db),
		LotteryReward:            q.LotteryReward.clone(db),
		MainnetRpcConfig:         q.MainnetRpcConfig.clone(db),
		NativeAccountInfo:        q.NativeAccountInfo.clone(db),
		PosMissionConfig:         q.PosMissionConfig.clone(db),
		PosReward:                q.PosReward.clone(db),
		PosRewardClaimRecord:     q.PosRewardClaimRecord.clone(db),
		PosRewardConfig:          q.PosRewardConfig.clone(db),
		PosRpcConfig:             q.PosRpcConfig.clone(db),
		PosSnapShot:              q.PosSnapShot.clone(db),
		PosStarLevelRule:         q.PosStarLevelRule.clone(db),
		PosStarWhitelist:         q.PosStarWhitelist.clone(db),
		QnFee:                    q.QnFee.clone(db),
		RewardCode:               q.RewardCode.clone(db),
		RewardCodeConfig:         q.RewardCodeConfig.clone(db),
		RewardCodeFee:            q.RewardCodeFee.clone(db),
		RewardKeyConfig:          q.RewardKeyConfig.clone(db),
		ServiceInfo:              q.ServiceInfo.clone(db),
		ServiceKey:               q.ServiceKey.clone(db),
		ServiceTx:                q.ServiceTx.clone(db),
		StakeAmmConfig:           q.StakeAmmConfig.clone(db),
		StakeBuyToken:            q.StakeBuyToken.clone(db),
		StakeFixRateConfig:       q.StakeFixRateConfig.clone(db),
		StakeInviteDist:          q.StakeInviteDist.clone(db),
		StakeInviteRate:          q.StakeInviteRate.clone(db),
		StakeLeader:              q.StakeLeader.clone(db),
		StakeLeaderReward:        q.StakeLeaderReward.clone(db),
		StakeLeaderRewardClaim:   q.StakeLeaderRewardClaim.clone(db),
		StakeLeaderRewardConfig:  q.StakeLeaderRewardConfig.clone(db),
		StakeRecord:              q.StakeRecord.clone(db),
		StakeReward:              q.StakeReward.clone(db),
		StakeRewardClaim:         q.StakeRewardClaim.clone(db),
		StakeRewardConfig:        q.StakeRewardConfig.clone(db),
		StakeSnapShot:            q.StakeSnapShot.clone(db),
		StakeStarLevelRule:       q.StakeStarLevelRule.clone(db),
		StakeStarWhitelist:       q.StakeStarWhitelist.clone(db),
		StakeTokenPool:           q.StakeTokenPool.clone(db),
		StakeTotalLeader:         q.StakeTotalLeader.clone(db),
		SystemConfig:             q.SystemConfig.clone(db),
		TakeTokenConfig:          q.TakeTokenConfig.clone(db),
		TakeTokenRecord:          q.TakeTokenRecord.clone(db),
		TokenConfig:              q.TokenConfig.clone(db),
		TxScanInfo:               q.TxScanInfo.clone(db),
		UserDailyExchangeQuota:   q.UserDailyExchangeQuota.clone(db),
		UserWalletRpcConfig:      q.UserWalletRpcConfig.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                       db,
		AwsConfig:                q.AwsConfig.replaceDB(db),
		CampaignExchangeConfig:   q.CampaignExchangeConfig.replaceDB(db),
		CampaignExchangeRecord:   q.CampaignExchangeRecord.replaceDB(db),
		ChainConfig:              q.ChainConfig.replaceDB(db),
		DailyClaimStats:          q.DailyClaimStats.replaceDB(db),
		DiscountRate:             q.DiscountRate.replaceDB(db),
		ExcludeAccount:           q.ExcludeAccount.replaceDB(db),
		FeeStatistics:            q.FeeStatistics.replaceDB(db),
		FeeTolerance:             q.FeeTolerance.replaceDB(db),
		FundFlow:                 q.FundFlow.replaceDB(db),
		GiveTokenConfig:          q.GiveTokenConfig.replaceDB(db),
		GiveTokenRecord:          q.GiveTokenRecord.replaceDB(db),
		GlobalDailyExchangeLimit: q.GlobalDailyExchangeLimit.replaceDB(db),
		HackerAccount:            q.HackerAccount.replaceDB(db),
		InviteRelation:           q.InviteRelation.replaceDB(db),
		LevelDist:                q.LevelDist.replaceDB(db),
		LevelRatio:               q.LevelRatio.replaceDB(db),
		LotteryClaimRecord:       q.LotteryClaimRecord.replaceDB(db),
		LotteryReward:            q.LotteryReward.replaceDB(db),
		MainnetRpcConfig:         q.MainnetRpcConfig.replaceDB(db),
		NativeAccountInfo:        q.NativeAccountInfo.replaceDB(db),
		PosMissionConfig:         q.PosMissionConfig.replaceDB(db),
		PosReward:                q.PosReward.replaceDB(db),
		PosRewardClaimRecord:     q.PosRewardClaimRecord.replaceDB(db),
		PosRewardConfig:          q.PosRewardConfig.replaceDB(db),
		PosRpcConfig:             q.PosRpcConfig.replaceDB(db),
		PosSnapShot:              q.PosSnapShot.replaceDB(db),
		PosStarLevelRule:         q.PosStarLevelRule.replaceDB(db),
		PosStarWhitelist:         q.PosStarWhitelist.replaceDB(db),
		QnFee:                    q.QnFee.replaceDB(db),
		RewardCode:               q.RewardCode.replaceDB(db),
		RewardCodeConfig:         q.RewardCodeConfig.replaceDB(db),
		RewardCodeFee:            q.RewardCodeFee.replaceDB(db),
		RewardKeyConfig:          q.RewardKeyConfig.replaceDB(db),
		ServiceInfo:              q.ServiceInfo.replaceDB(db),
		ServiceKey:               q.ServiceKey.replaceDB(db),
		ServiceTx:                q.ServiceTx.replaceDB(db),
		StakeAmmConfig:           q.StakeAmmConfig.replaceDB(db),
		StakeBuyToken:            q.StakeBuyToken.replaceDB(db),
		StakeFixRateConfig:       q.StakeFixRateConfig.replaceDB(db),
		StakeInviteDist:          q.StakeInviteDist.replaceDB(db),
		StakeInviteRate:          q.StakeInviteRate.replaceDB(db),
		StakeLeader:              q.StakeLeader.replaceDB(db),
		StakeLeaderReward:        q.StakeLeaderReward.replaceDB(db),
		StakeLeaderRewardClaim:   q.StakeLeaderRewardClaim.replaceDB(db),
		StakeLeaderRewardConfig:  q.StakeLeaderRewardConfig.replaceDB(db),
		StakeRecord:              q.StakeRecord.replaceDB(db),
		StakeReward:              q.StakeReward.replaceDB(db),
		StakeRewardClaim:         q.StakeRewardClaim.replaceDB(db),
		StakeRewardConfig:        q.StakeRewardConfig.replaceDB(db),
		StakeSnapShot:            q.StakeSnapShot.replaceDB(db),
		StakeStarLevelRule:       q.StakeStarLevelRule.replaceDB(db),
		StakeStarWhitelist:       q.StakeStarWhitelist.replaceDB(db),
		StakeTokenPool:           q.StakeTokenPool.replaceDB(db),
		StakeTotalLeader:         q.StakeTotalLeader.replaceDB(db),
		SystemConfig:             q.SystemConfig.replaceDB(db),
		TakeTokenConfig:          q.TakeTokenConfig.replaceDB(db),
		TakeTokenRecord:          q.TakeTokenRecord.replaceDB(db),
		TokenConfig:              q.TokenConfig.replaceDB(db),
		TxScanInfo:               q.TxScanInfo.replaceDB(db),
		UserDailyExchangeQuota:   q.UserDailyExchangeQuota.replaceDB(db),
		UserWalletRpcConfig:      q.UserWalletRpcConfig.replaceDB(db),
	}
}

type queryCtx struct {
	AwsConfig                IAwsConfigDo
	CampaignExchangeConfig   ICampaignExchangeConfigDo
	CampaignExchangeRecord   ICampaignExchangeRecordDo
	ChainConfig              IChainConfigDo
	DailyClaimStats          IDailyClaimStatsDo
	DiscountRate             IDiscountRateDo
	ExcludeAccount           IExcludeAccountDo
	FeeStatistics            IFeeStatisticsDo
	FeeTolerance             IFeeToleranceDo
	FundFlow                 IFundFlowDo
	GiveTokenConfig          IGiveTokenConfigDo
	GiveTokenRecord          IGiveTokenRecordDo
	GlobalDailyExchangeLimit IGlobalDailyExchangeLimitDo
	HackerAccount            IHackerAccountDo
	InviteRelation           IInviteRelationDo
	LevelDist                ILevelDistDo
	LevelRatio               ILevelRatioDo
	LotteryClaimRecord       ILotteryClaimRecordDo
	LotteryReward            ILotteryRewardDo
	MainnetRpcConfig         IMainnetRpcConfigDo
	NativeAccountInfo        INativeAccountInfoDo
	PosMissionConfig         IPosMissionConfigDo
	PosReward                IPosRewardDo
	PosRewardClaimRecord     IPosRewardClaimRecordDo
	PosRewardConfig          IPosRewardConfigDo
	PosRpcConfig             IPosRpcConfigDo
	PosSnapShot              IPosSnapShotDo
	PosStarLevelRule         IPosStarLevelRuleDo
	PosStarWhitelist         IPosStarWhitelistDo
	QnFee                    IQnFeeDo
	RewardCode               IRewardCodeDo
	RewardCodeConfig         IRewardCodeConfigDo
	RewardCodeFee            IRewardCodeFeeDo
	RewardKeyConfig          IRewardKeyConfigDo
	ServiceInfo              IServiceInfoDo
	ServiceKey               IServiceKeyDo
	ServiceTx                IServiceTxDo
	StakeAmmConfig           IStakeAmmConfigDo
	StakeBuyToken            IStakeBuyTokenDo
	StakeFixRateConfig       IStakeFixRateConfigDo
	StakeInviteDist          IStakeInviteDistDo
	StakeInviteRate          IStakeInviteRateDo
	StakeLeader              IStakeLeaderDo
	StakeLeaderReward        IStakeLeaderRewardDo
	StakeLeaderRewardClaim   IStakeLeaderRewardClaimDo
	StakeLeaderRewardConfig  IStakeLeaderRewardConfigDo
	StakeRecord              IStakeRecordDo
	StakeReward              IStakeRewardDo
	StakeRewardClaim         IStakeRewardClaimDo
	StakeRewardConfig        IStakeRewardConfigDo
	StakeSnapShot            IStakeSnapShotDo
	StakeStarLevelRule       IStakeStarLevelRuleDo
	StakeStarWhitelist       IStakeStarWhitelistDo
	StakeTokenPool           IStakeTokenPoolDo
	StakeTotalLeader         IStakeTotalLeaderDo
	SystemConfig             ISystemConfigDo
	TakeTokenConfig          ITakeTokenConfigDo
	TakeTokenRecord          ITakeTokenRecordDo
	TokenConfig              ITokenConfigDo
	TxScanInfo               ITxScanInfoDo
	UserDailyExchangeQuota   IUserDailyExchangeQuotaDo
	UserWalletRpcConfig      IUserWalletRpcConfigDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		AwsConfig:                q.AwsConfig.WithContext(ctx),
		CampaignExchangeConfig:   q.CampaignExchangeConfig.WithContext(ctx),
		CampaignExchangeRecord:   q.CampaignExchangeRecord.WithContext(ctx),
		ChainConfig:              q.ChainConfig.WithContext(ctx),
		DailyClaimStats:          q.DailyClaimStats.WithContext(ctx),
		DiscountRate:             q.DiscountRate.WithContext(ctx),
		ExcludeAccount:           q.ExcludeAccount.WithContext(ctx),
		FeeStatistics:            q.FeeStatistics.WithContext(ctx),
		FeeTolerance:             q.FeeTolerance.WithContext(ctx),
		FundFlow:                 q.FundFlow.WithContext(ctx),
		GiveTokenConfig:          q.GiveTokenConfig.WithContext(ctx),
		GiveTokenRecord:          q.GiveTokenRecord.WithContext(ctx),
		GlobalDailyExchangeLimit: q.GlobalDailyExchangeLimit.WithContext(ctx),
		HackerAccount:            q.HackerAccount.WithContext(ctx),
		InviteRelation:           q.InviteRelation.WithContext(ctx),
		LevelDist:                q.LevelDist.WithContext(ctx),
		LevelRatio:               q.LevelRatio.WithContext(ctx),
		LotteryClaimRecord:       q.LotteryClaimRecord.WithContext(ctx),
		LotteryReward:            q.LotteryReward.WithContext(ctx),
		MainnetRpcConfig:         q.MainnetRpcConfig.WithContext(ctx),
		NativeAccountInfo:        q.NativeAccountInfo.WithContext(ctx),
		PosMissionConfig:         q.PosMissionConfig.WithContext(ctx),
		PosReward:                q.PosReward.WithContext(ctx),
		PosRewardClaimRecord:     q.PosRewardClaimRecord.WithContext(ctx),
		PosRewardConfig:          q.PosRewardConfig.WithContext(ctx),
		PosRpcConfig:             q.PosRpcConfig.WithContext(ctx),
		PosSnapShot:              q.PosSnapShot.WithContext(ctx),
		PosStarLevelRule:         q.PosStarLevelRule.WithContext(ctx),
		PosStarWhitelist:         q.PosStarWhitelist.WithContext(ctx),
		QnFee:                    q.QnFee.WithContext(ctx),
		RewardCode:               q.RewardCode.WithContext(ctx),
		RewardCodeConfig:         q.RewardCodeConfig.WithContext(ctx),
		RewardCodeFee:            q.RewardCodeFee.WithContext(ctx),
		RewardKeyConfig:          q.RewardKeyConfig.WithContext(ctx),
		ServiceInfo:              q.ServiceInfo.WithContext(ctx),
		ServiceKey:               q.ServiceKey.WithContext(ctx),
		ServiceTx:                q.ServiceTx.WithContext(ctx),
		StakeAmmConfig:           q.StakeAmmConfig.WithContext(ctx),
		StakeBuyToken:            q.StakeBuyToken.WithContext(ctx),
		StakeFixRateConfig:       q.StakeFixRateConfig.WithContext(ctx),
		StakeInviteDist:          q.StakeInviteDist.WithContext(ctx),
		StakeInviteRate:          q.StakeInviteRate.WithContext(ctx),
		StakeLeader:              q.StakeLeader.WithContext(ctx),
		StakeLeaderReward:        q.StakeLeaderReward.WithContext(ctx),
		StakeLeaderRewardClaim:   q.StakeLeaderRewardClaim.WithContext(ctx),
		StakeLeaderRewardConfig:  q.StakeLeaderRewardConfig.WithContext(ctx),
		StakeRecord:              q.StakeRecord.WithContext(ctx),
		StakeReward:              q.StakeReward.WithContext(ctx),
		StakeRewardClaim:         q.StakeRewardClaim.WithContext(ctx),
		StakeRewardConfig:        q.StakeRewardConfig.WithContext(ctx),
		StakeSnapShot:            q.StakeSnapShot.WithContext(ctx),
		StakeStarLevelRule:       q.StakeStarLevelRule.WithContext(ctx),
		StakeStarWhitelist:       q.StakeStarWhitelist.WithContext(ctx),
		StakeTokenPool:           q.StakeTokenPool.WithContext(ctx),
		StakeTotalLeader:         q.StakeTotalLeader.WithContext(ctx),
		SystemConfig:             q.SystemConfig.WithContext(ctx),
		TakeTokenConfig:          q.TakeTokenConfig.WithContext(ctx),
		TakeTokenRecord:          q.TakeTokenRecord.WithContext(ctx),
		TokenConfig:              q.TokenConfig.WithContext(ctx),
		TxScanInfo:               q.TxScanInfo.WithContext(ctx),
		UserDailyExchangeQuota:   q.UserDailyExchangeQuota.WithContext(ctx),
		UserWalletRpcConfig:      q.UserWalletRpcConfig.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
