// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"oshit-go/common/pkg/dal/model"
)

func newCampaignQuoteConfig(db *gorm.DB, opts ...gen.DOOption) campaignQuoteConfig {
	_campaignQuoteConfig := campaignQuoteConfig{}

	_campaignQuoteConfig.campaignQuoteConfigDo.UseDB(db, opts...)
	_campaignQuoteConfig.campaignQuoteConfigDo.UseModel(&model.CampaignQuoteConfig{})

	tableName := _campaignQuoteConfig.campaignQuoteConfigDo.TableName()
	_campaignQuoteConfig.ALL = field.NewAsterisk(tableName)
	_campaignQuoteConfig.RecordID = field.NewString(tableName, "record_id")
	_campaignQuoteConfig.RewardAccount = field.NewString(tableName, "reward_account")
	_campaignQuoteConfig.CostAccount = field.NewString(tableName, "cost_account")
	_campaignQuoteConfig.QuoteRate = field.NewFloat64(tableName, "quote_rate")
	_campaignQuoteConfig.CostRate = field.NewFloat64(tableName, "cost_rate")
	_campaignQuoteConfig.CreatedAt = field.NewTime(tableName, "created_at")
	_campaignQuoteConfig.UpdatedAt = field.NewTime(tableName, "updated_at")

	_campaignQuoteConfig.fillFieldMap()

	return _campaignQuoteConfig
}

type campaignQuoteConfig struct {
	campaignQuoteConfigDo campaignQuoteConfigDo

	ALL           field.Asterisk
	RecordID      field.String
	RewardAccount field.String
	CostAccount   field.String
	QuoteRate     field.Float64
	CostRate      field.Float64
	CreatedAt     field.Time
	UpdatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (c campaignQuoteConfig) Table(newTableName string) *campaignQuoteConfig {
	c.campaignQuoteConfigDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c campaignQuoteConfig) As(alias string) *campaignQuoteConfig {
	c.campaignQuoteConfigDo.DO = *(c.campaignQuoteConfigDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *campaignQuoteConfig) updateTableName(table string) *campaignQuoteConfig {
	c.ALL = field.NewAsterisk(table)
	c.RecordID = field.NewString(table, "record_id")
	c.RewardAccount = field.NewString(table, "reward_account")
	c.CostAccount = field.NewString(table, "cost_account")
	c.QuoteRate = field.NewFloat64(table, "quote_rate")
	c.CostRate = field.NewFloat64(table, "cost_rate")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")

	c.fillFieldMap()

	return c
}

func (c *campaignQuoteConfig) WithContext(ctx context.Context) ICampaignQuoteConfigDo {
	return c.campaignQuoteConfigDo.WithContext(ctx)
}

func (c campaignQuoteConfig) TableName() string { return c.campaignQuoteConfigDo.TableName() }

func (c campaignQuoteConfig) Alias() string { return c.campaignQuoteConfigDo.Alias() }

func (c campaignQuoteConfig) Columns(cols ...field.Expr) gen.Columns {
	return c.campaignQuoteConfigDo.Columns(cols...)
}

func (c *campaignQuoteConfig) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *campaignQuoteConfig) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 7)
	c.fieldMap["record_id"] = c.RecordID
	c.fieldMap["reward_account"] = c.RewardAccount
	c.fieldMap["cost_account"] = c.CostAccount
	c.fieldMap["quote_rate"] = c.QuoteRate
	c.fieldMap["cost_rate"] = c.CostRate
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
}

func (c campaignQuoteConfig) clone(db *gorm.DB) campaignQuoteConfig {
	c.campaignQuoteConfigDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c campaignQuoteConfig) replaceDB(db *gorm.DB) campaignQuoteConfig {
	c.campaignQuoteConfigDo.ReplaceDB(db)
	return c
}

type campaignQuoteConfigDo struct{ gen.DO }

type ICampaignQuoteConfigDo interface {
	gen.SubQuery
	Debug() ICampaignQuoteConfigDo
	WithContext(ctx context.Context) ICampaignQuoteConfigDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICampaignQuoteConfigDo
	WriteDB() ICampaignQuoteConfigDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICampaignQuoteConfigDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICampaignQuoteConfigDo
	Not(conds ...gen.Condition) ICampaignQuoteConfigDo
	Or(conds ...gen.Condition) ICampaignQuoteConfigDo
	Select(conds ...field.Expr) ICampaignQuoteConfigDo
	Where(conds ...gen.Condition) ICampaignQuoteConfigDo
	Order(conds ...field.Expr) ICampaignQuoteConfigDo
	Distinct(cols ...field.Expr) ICampaignQuoteConfigDo
	Omit(cols ...field.Expr) ICampaignQuoteConfigDo
	Join(table schema.Tabler, on ...field.Expr) ICampaignQuoteConfigDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICampaignQuoteConfigDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICampaignQuoteConfigDo
	Group(cols ...field.Expr) ICampaignQuoteConfigDo
	Having(conds ...gen.Condition) ICampaignQuoteConfigDo
	Limit(limit int) ICampaignQuoteConfigDo
	Offset(offset int) ICampaignQuoteConfigDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICampaignQuoteConfigDo
	Unscoped() ICampaignQuoteConfigDo
	Create(values ...*model.CampaignQuoteConfig) error
	CreateInBatches(values []*model.CampaignQuoteConfig, batchSize int) error
	Save(values ...*model.CampaignQuoteConfig) error
	First() (*model.CampaignQuoteConfig, error)
	Take() (*model.CampaignQuoteConfig, error)
	Last() (*model.CampaignQuoteConfig, error)
	Find() ([]*model.CampaignQuoteConfig, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CampaignQuoteConfig, err error)
	FindInBatches(result *[]*model.CampaignQuoteConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.CampaignQuoteConfig) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICampaignQuoteConfigDo
	Assign(attrs ...field.AssignExpr) ICampaignQuoteConfigDo
	Joins(fields ...field.RelationField) ICampaignQuoteConfigDo
	Preload(fields ...field.RelationField) ICampaignQuoteConfigDo
	FirstOrInit() (*model.CampaignQuoteConfig, error)
	FirstOrCreate() (*model.CampaignQuoteConfig, error)
	FindByPage(offset int, limit int) (result []*model.CampaignQuoteConfig, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICampaignQuoteConfigDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c campaignQuoteConfigDo) Debug() ICampaignQuoteConfigDo {
	return c.withDO(c.DO.Debug())
}

func (c campaignQuoteConfigDo) WithContext(ctx context.Context) ICampaignQuoteConfigDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c campaignQuoteConfigDo) ReadDB() ICampaignQuoteConfigDo {
	return c.Clauses(dbresolver.Read)
}

func (c campaignQuoteConfigDo) WriteDB() ICampaignQuoteConfigDo {
	return c.Clauses(dbresolver.Write)
}

func (c campaignQuoteConfigDo) Session(config *gorm.Session) ICampaignQuoteConfigDo {
	return c.withDO(c.DO.Session(config))
}

func (c campaignQuoteConfigDo) Clauses(conds ...clause.Expression) ICampaignQuoteConfigDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c campaignQuoteConfigDo) Returning(value interface{}, columns ...string) ICampaignQuoteConfigDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c campaignQuoteConfigDo) Not(conds ...gen.Condition) ICampaignQuoteConfigDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c campaignQuoteConfigDo) Or(conds ...gen.Condition) ICampaignQuoteConfigDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c campaignQuoteConfigDo) Select(conds ...field.Expr) ICampaignQuoteConfigDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c campaignQuoteConfigDo) Where(conds ...gen.Condition) ICampaignQuoteConfigDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c campaignQuoteConfigDo) Order(conds ...field.Expr) ICampaignQuoteConfigDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c campaignQuoteConfigDo) Distinct(cols ...field.Expr) ICampaignQuoteConfigDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c campaignQuoteConfigDo) Omit(cols ...field.Expr) ICampaignQuoteConfigDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c campaignQuoteConfigDo) Join(table schema.Tabler, on ...field.Expr) ICampaignQuoteConfigDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c campaignQuoteConfigDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICampaignQuoteConfigDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c campaignQuoteConfigDo) RightJoin(table schema.Tabler, on ...field.Expr) ICampaignQuoteConfigDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c campaignQuoteConfigDo) Group(cols ...field.Expr) ICampaignQuoteConfigDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c campaignQuoteConfigDo) Having(conds ...gen.Condition) ICampaignQuoteConfigDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c campaignQuoteConfigDo) Limit(limit int) ICampaignQuoteConfigDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c campaignQuoteConfigDo) Offset(offset int) ICampaignQuoteConfigDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c campaignQuoteConfigDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICampaignQuoteConfigDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c campaignQuoteConfigDo) Unscoped() ICampaignQuoteConfigDo {
	return c.withDO(c.DO.Unscoped())
}

func (c campaignQuoteConfigDo) Create(values ...*model.CampaignQuoteConfig) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c campaignQuoteConfigDo) CreateInBatches(values []*model.CampaignQuoteConfig, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c campaignQuoteConfigDo) Save(values ...*model.CampaignQuoteConfig) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c campaignQuoteConfigDo) First() (*model.CampaignQuoteConfig, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CampaignQuoteConfig), nil
	}
}

func (c campaignQuoteConfigDo) Take() (*model.CampaignQuoteConfig, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CampaignQuoteConfig), nil
	}
}

func (c campaignQuoteConfigDo) Last() (*model.CampaignQuoteConfig, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CampaignQuoteConfig), nil
	}
}

func (c campaignQuoteConfigDo) Find() ([]*model.CampaignQuoteConfig, error) {
	result, err := c.DO.Find()
	return result.([]*model.CampaignQuoteConfig), err
}

func (c campaignQuoteConfigDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CampaignQuoteConfig, err error) {
	buf := make([]*model.CampaignQuoteConfig, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c campaignQuoteConfigDo) FindInBatches(result *[]*model.CampaignQuoteConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c campaignQuoteConfigDo) Attrs(attrs ...field.AssignExpr) ICampaignQuoteConfigDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c campaignQuoteConfigDo) Assign(attrs ...field.AssignExpr) ICampaignQuoteConfigDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c campaignQuoteConfigDo) Joins(fields ...field.RelationField) ICampaignQuoteConfigDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c campaignQuoteConfigDo) Preload(fields ...field.RelationField) ICampaignQuoteConfigDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c campaignQuoteConfigDo) FirstOrInit() (*model.CampaignQuoteConfig, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CampaignQuoteConfig), nil
	}
}

func (c campaignQuoteConfigDo) FirstOrCreate() (*model.CampaignQuoteConfig, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CampaignQuoteConfig), nil
	}
}

func (c campaignQuoteConfigDo) FindByPage(offset int, limit int) (result []*model.CampaignQuoteConfig, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c campaignQuoteConfigDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c campaignQuoteConfigDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c campaignQuoteConfigDo) Delete(models ...*model.CampaignQuoteConfig) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *campaignQuoteConfigDo) withDO(do gen.Dao) *campaignQuoteConfigDo {
	c.DO = *do.(*gen.DO)
	return c
}
