// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"oshit-go/common/pkg/dal/model"
)

func newExcludeAccount(db *gorm.DB, opts ...gen.DOOption) excludeAccount {
	_excludeAccount := excludeAccount{}

	_excludeAccount.excludeAccountDo.UseDB(db, opts...)
	_excludeAccount.excludeAccountDo.UseModel(&model.ExcludeAccount{})

	tableName := _excludeAccount.excludeAccountDo.TableName()
	_excludeAccount.ALL = field.NewAsterisk(tableName)
	_excludeAccount.RecordID = field.NewString(tableName, "record_id")
	_excludeAccount.NativeAccount = field.NewString(tableName, "native_account")
	_excludeAccount.Remark = field.NewString(tableName, "remark")
	_excludeAccount.CreatedAt = field.NewTime(tableName, "created_at")
	_excludeAccount.UpdatedAt = field.NewTime(tableName, "updated_at")

	_excludeAccount.fillFieldMap()

	return _excludeAccount
}

type excludeAccount struct {
	excludeAccountDo excludeAccountDo

	ALL           field.Asterisk
	RecordID      field.String
	NativeAccount field.String
	Remark        field.String
	CreatedAt     field.Time
	UpdatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (e excludeAccount) Table(newTableName string) *excludeAccount {
	e.excludeAccountDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e excludeAccount) As(alias string) *excludeAccount {
	e.excludeAccountDo.DO = *(e.excludeAccountDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *excludeAccount) updateTableName(table string) *excludeAccount {
	e.ALL = field.NewAsterisk(table)
	e.RecordID = field.NewString(table, "record_id")
	e.NativeAccount = field.NewString(table, "native_account")
	e.Remark = field.NewString(table, "remark")
	e.CreatedAt = field.NewTime(table, "created_at")
	e.UpdatedAt = field.NewTime(table, "updated_at")

	e.fillFieldMap()

	return e
}

func (e *excludeAccount) WithContext(ctx context.Context) IExcludeAccountDo {
	return e.excludeAccountDo.WithContext(ctx)
}

func (e excludeAccount) TableName() string { return e.excludeAccountDo.TableName() }

func (e excludeAccount) Alias() string { return e.excludeAccountDo.Alias() }

func (e excludeAccount) Columns(cols ...field.Expr) gen.Columns {
	return e.excludeAccountDo.Columns(cols...)
}

func (e *excludeAccount) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *excludeAccount) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 5)
	e.fieldMap["record_id"] = e.RecordID
	e.fieldMap["native_account"] = e.NativeAccount
	e.fieldMap["remark"] = e.Remark
	e.fieldMap["created_at"] = e.CreatedAt
	e.fieldMap["updated_at"] = e.UpdatedAt
}

func (e excludeAccount) clone(db *gorm.DB) excludeAccount {
	e.excludeAccountDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e excludeAccount) replaceDB(db *gorm.DB) excludeAccount {
	e.excludeAccountDo.ReplaceDB(db)
	return e
}

type excludeAccountDo struct{ gen.DO }

type IExcludeAccountDo interface {
	gen.SubQuery
	Debug() IExcludeAccountDo
	WithContext(ctx context.Context) IExcludeAccountDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IExcludeAccountDo
	WriteDB() IExcludeAccountDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IExcludeAccountDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IExcludeAccountDo
	Not(conds ...gen.Condition) IExcludeAccountDo
	Or(conds ...gen.Condition) IExcludeAccountDo
	Select(conds ...field.Expr) IExcludeAccountDo
	Where(conds ...gen.Condition) IExcludeAccountDo
	Order(conds ...field.Expr) IExcludeAccountDo
	Distinct(cols ...field.Expr) IExcludeAccountDo
	Omit(cols ...field.Expr) IExcludeAccountDo
	Join(table schema.Tabler, on ...field.Expr) IExcludeAccountDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IExcludeAccountDo
	RightJoin(table schema.Tabler, on ...field.Expr) IExcludeAccountDo
	Group(cols ...field.Expr) IExcludeAccountDo
	Having(conds ...gen.Condition) IExcludeAccountDo
	Limit(limit int) IExcludeAccountDo
	Offset(offset int) IExcludeAccountDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IExcludeAccountDo
	Unscoped() IExcludeAccountDo
	Create(values ...*model.ExcludeAccount) error
	CreateInBatches(values []*model.ExcludeAccount, batchSize int) error
	Save(values ...*model.ExcludeAccount) error
	First() (*model.ExcludeAccount, error)
	Take() (*model.ExcludeAccount, error)
	Last() (*model.ExcludeAccount, error)
	Find() ([]*model.ExcludeAccount, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ExcludeAccount, err error)
	FindInBatches(result *[]*model.ExcludeAccount, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ExcludeAccount) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IExcludeAccountDo
	Assign(attrs ...field.AssignExpr) IExcludeAccountDo
	Joins(fields ...field.RelationField) IExcludeAccountDo
	Preload(fields ...field.RelationField) IExcludeAccountDo
	FirstOrInit() (*model.ExcludeAccount, error)
	FirstOrCreate() (*model.ExcludeAccount, error)
	FindByPage(offset int, limit int) (result []*model.ExcludeAccount, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IExcludeAccountDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (e excludeAccountDo) Debug() IExcludeAccountDo {
	return e.withDO(e.DO.Debug())
}

func (e excludeAccountDo) WithContext(ctx context.Context) IExcludeAccountDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e excludeAccountDo) ReadDB() IExcludeAccountDo {
	return e.Clauses(dbresolver.Read)
}

func (e excludeAccountDo) WriteDB() IExcludeAccountDo {
	return e.Clauses(dbresolver.Write)
}

func (e excludeAccountDo) Session(config *gorm.Session) IExcludeAccountDo {
	return e.withDO(e.DO.Session(config))
}

func (e excludeAccountDo) Clauses(conds ...clause.Expression) IExcludeAccountDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e excludeAccountDo) Returning(value interface{}, columns ...string) IExcludeAccountDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e excludeAccountDo) Not(conds ...gen.Condition) IExcludeAccountDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e excludeAccountDo) Or(conds ...gen.Condition) IExcludeAccountDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e excludeAccountDo) Select(conds ...field.Expr) IExcludeAccountDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e excludeAccountDo) Where(conds ...gen.Condition) IExcludeAccountDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e excludeAccountDo) Order(conds ...field.Expr) IExcludeAccountDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e excludeAccountDo) Distinct(cols ...field.Expr) IExcludeAccountDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e excludeAccountDo) Omit(cols ...field.Expr) IExcludeAccountDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e excludeAccountDo) Join(table schema.Tabler, on ...field.Expr) IExcludeAccountDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e excludeAccountDo) LeftJoin(table schema.Tabler, on ...field.Expr) IExcludeAccountDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e excludeAccountDo) RightJoin(table schema.Tabler, on ...field.Expr) IExcludeAccountDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e excludeAccountDo) Group(cols ...field.Expr) IExcludeAccountDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e excludeAccountDo) Having(conds ...gen.Condition) IExcludeAccountDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e excludeAccountDo) Limit(limit int) IExcludeAccountDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e excludeAccountDo) Offset(offset int) IExcludeAccountDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e excludeAccountDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IExcludeAccountDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e excludeAccountDo) Unscoped() IExcludeAccountDo {
	return e.withDO(e.DO.Unscoped())
}

func (e excludeAccountDo) Create(values ...*model.ExcludeAccount) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e excludeAccountDo) CreateInBatches(values []*model.ExcludeAccount, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e excludeAccountDo) Save(values ...*model.ExcludeAccount) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e excludeAccountDo) First() (*model.ExcludeAccount, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ExcludeAccount), nil
	}
}

func (e excludeAccountDo) Take() (*model.ExcludeAccount, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ExcludeAccount), nil
	}
}

func (e excludeAccountDo) Last() (*model.ExcludeAccount, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ExcludeAccount), nil
	}
}

func (e excludeAccountDo) Find() ([]*model.ExcludeAccount, error) {
	result, err := e.DO.Find()
	return result.([]*model.ExcludeAccount), err
}

func (e excludeAccountDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ExcludeAccount, err error) {
	buf := make([]*model.ExcludeAccount, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e excludeAccountDo) FindInBatches(result *[]*model.ExcludeAccount, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e excludeAccountDo) Attrs(attrs ...field.AssignExpr) IExcludeAccountDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e excludeAccountDo) Assign(attrs ...field.AssignExpr) IExcludeAccountDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e excludeAccountDo) Joins(fields ...field.RelationField) IExcludeAccountDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e excludeAccountDo) Preload(fields ...field.RelationField) IExcludeAccountDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e excludeAccountDo) FirstOrInit() (*model.ExcludeAccount, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ExcludeAccount), nil
	}
}

func (e excludeAccountDo) FirstOrCreate() (*model.ExcludeAccount, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ExcludeAccount), nil
	}
}

func (e excludeAccountDo) FindByPage(offset int, limit int) (result []*model.ExcludeAccount, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e excludeAccountDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e excludeAccountDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e excludeAccountDo) Delete(models ...*model.ExcludeAccount) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *excludeAccountDo) withDO(do gen.Dao) *excludeAccountDo {
	e.DO = *do.(*gen.DO)
	return e
}
