// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"oshit-go/common/pkg/dal/model"
)

func newFundFlow(db *gorm.DB, opts ...gen.DOOption) fundFlow {
	_fundFlow := fundFlow{}

	_fundFlow.fundFlowDo.UseDB(db, opts...)
	_fundFlow.fundFlowDo.UseModel(&model.FundFlow{})

	tableName := _fundFlow.fundFlowDo.TableName()
	_fundFlow.ALL = field.NewAsterisk(tableName)
	_fundFlow.RecordID = field.NewString(tableName, "record_id")
	_fundFlow.IsToken = field.NewBool(tableName, "is_token")
	_fundFlow.FromAccount = field.NewString(tableName, "from_account")
	_fundFlow.ToAccount = field.NewString(tableName, "to_account")
	_fundFlow.TxID = field.NewString(tableName, "tx_id")
	_fundFlow.Direction = field.NewString(tableName, "direction")
	_fundFlow.ServiceType = field.NewString(tableName, "service_type")
	_fundFlow.FlowType = field.NewString(tableName, "flow_type")
	_fundFlow.Decimals = field.NewInt16(tableName, "decimals")
	_fundFlow.Amount = field.NewFloat64(tableName, "amount")
	_fundFlow.CreatedAt = field.NewTime(tableName, "created_at")
	_fundFlow.UpdatedAt = field.NewTime(tableName, "updated_at")

	_fundFlow.fillFieldMap()

	return _fundFlow
}

type fundFlow struct {
	fundFlowDo fundFlowDo

	ALL         field.Asterisk
	RecordID    field.String
	IsToken     field.Bool
	FromAccount field.String
	ToAccount   field.String
	TxID        field.String
	Direction   field.String
	ServiceType field.String
	FlowType    field.String
	Decimals    field.Int16
	Amount      field.Float64
	CreatedAt   field.Time
	UpdatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (f fundFlow) Table(newTableName string) *fundFlow {
	f.fundFlowDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f fundFlow) As(alias string) *fundFlow {
	f.fundFlowDo.DO = *(f.fundFlowDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *fundFlow) updateTableName(table string) *fundFlow {
	f.ALL = field.NewAsterisk(table)
	f.RecordID = field.NewString(table, "record_id")
	f.IsToken = field.NewBool(table, "is_token")
	f.FromAccount = field.NewString(table, "from_account")
	f.ToAccount = field.NewString(table, "to_account")
	f.TxID = field.NewString(table, "tx_id")
	f.Direction = field.NewString(table, "direction")
	f.ServiceType = field.NewString(table, "service_type")
	f.FlowType = field.NewString(table, "flow_type")
	f.Decimals = field.NewInt16(table, "decimals")
	f.Amount = field.NewFloat64(table, "amount")
	f.CreatedAt = field.NewTime(table, "created_at")
	f.UpdatedAt = field.NewTime(table, "updated_at")

	f.fillFieldMap()

	return f
}

func (f *fundFlow) WithContext(ctx context.Context) IFundFlowDo { return f.fundFlowDo.WithContext(ctx) }

func (f fundFlow) TableName() string { return f.fundFlowDo.TableName() }

func (f fundFlow) Alias() string { return f.fundFlowDo.Alias() }

func (f fundFlow) Columns(cols ...field.Expr) gen.Columns { return f.fundFlowDo.Columns(cols...) }

func (f *fundFlow) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *fundFlow) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 12)
	f.fieldMap["record_id"] = f.RecordID
	f.fieldMap["is_token"] = f.IsToken
	f.fieldMap["from_account"] = f.FromAccount
	f.fieldMap["to_account"] = f.ToAccount
	f.fieldMap["tx_id"] = f.TxID
	f.fieldMap["direction"] = f.Direction
	f.fieldMap["service_type"] = f.ServiceType
	f.fieldMap["flow_type"] = f.FlowType
	f.fieldMap["decimals"] = f.Decimals
	f.fieldMap["amount"] = f.Amount
	f.fieldMap["created_at"] = f.CreatedAt
	f.fieldMap["updated_at"] = f.UpdatedAt
}

func (f fundFlow) clone(db *gorm.DB) fundFlow {
	f.fundFlowDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f fundFlow) replaceDB(db *gorm.DB) fundFlow {
	f.fundFlowDo.ReplaceDB(db)
	return f
}

type fundFlowDo struct{ gen.DO }

type IFundFlowDo interface {
	gen.SubQuery
	Debug() IFundFlowDo
	WithContext(ctx context.Context) IFundFlowDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IFundFlowDo
	WriteDB() IFundFlowDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IFundFlowDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IFundFlowDo
	Not(conds ...gen.Condition) IFundFlowDo
	Or(conds ...gen.Condition) IFundFlowDo
	Select(conds ...field.Expr) IFundFlowDo
	Where(conds ...gen.Condition) IFundFlowDo
	Order(conds ...field.Expr) IFundFlowDo
	Distinct(cols ...field.Expr) IFundFlowDo
	Omit(cols ...field.Expr) IFundFlowDo
	Join(table schema.Tabler, on ...field.Expr) IFundFlowDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IFundFlowDo
	RightJoin(table schema.Tabler, on ...field.Expr) IFundFlowDo
	Group(cols ...field.Expr) IFundFlowDo
	Having(conds ...gen.Condition) IFundFlowDo
	Limit(limit int) IFundFlowDo
	Offset(offset int) IFundFlowDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IFundFlowDo
	Unscoped() IFundFlowDo
	Create(values ...*model.FundFlow) error
	CreateInBatches(values []*model.FundFlow, batchSize int) error
	Save(values ...*model.FundFlow) error
	First() (*model.FundFlow, error)
	Take() (*model.FundFlow, error)
	Last() (*model.FundFlow, error)
	Find() ([]*model.FundFlow, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FundFlow, err error)
	FindInBatches(result *[]*model.FundFlow, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.FundFlow) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IFundFlowDo
	Assign(attrs ...field.AssignExpr) IFundFlowDo
	Joins(fields ...field.RelationField) IFundFlowDo
	Preload(fields ...field.RelationField) IFundFlowDo
	FirstOrInit() (*model.FundFlow, error)
	FirstOrCreate() (*model.FundFlow, error)
	FindByPage(offset int, limit int) (result []*model.FundFlow, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IFundFlowDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (f fundFlowDo) Debug() IFundFlowDo {
	return f.withDO(f.DO.Debug())
}

func (f fundFlowDo) WithContext(ctx context.Context) IFundFlowDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f fundFlowDo) ReadDB() IFundFlowDo {
	return f.Clauses(dbresolver.Read)
}

func (f fundFlowDo) WriteDB() IFundFlowDo {
	return f.Clauses(dbresolver.Write)
}

func (f fundFlowDo) Session(config *gorm.Session) IFundFlowDo {
	return f.withDO(f.DO.Session(config))
}

func (f fundFlowDo) Clauses(conds ...clause.Expression) IFundFlowDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f fundFlowDo) Returning(value interface{}, columns ...string) IFundFlowDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f fundFlowDo) Not(conds ...gen.Condition) IFundFlowDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f fundFlowDo) Or(conds ...gen.Condition) IFundFlowDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f fundFlowDo) Select(conds ...field.Expr) IFundFlowDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f fundFlowDo) Where(conds ...gen.Condition) IFundFlowDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f fundFlowDo) Order(conds ...field.Expr) IFundFlowDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f fundFlowDo) Distinct(cols ...field.Expr) IFundFlowDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f fundFlowDo) Omit(cols ...field.Expr) IFundFlowDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f fundFlowDo) Join(table schema.Tabler, on ...field.Expr) IFundFlowDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f fundFlowDo) LeftJoin(table schema.Tabler, on ...field.Expr) IFundFlowDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f fundFlowDo) RightJoin(table schema.Tabler, on ...field.Expr) IFundFlowDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f fundFlowDo) Group(cols ...field.Expr) IFundFlowDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f fundFlowDo) Having(conds ...gen.Condition) IFundFlowDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f fundFlowDo) Limit(limit int) IFundFlowDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f fundFlowDo) Offset(offset int) IFundFlowDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f fundFlowDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IFundFlowDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f fundFlowDo) Unscoped() IFundFlowDo {
	return f.withDO(f.DO.Unscoped())
}

func (f fundFlowDo) Create(values ...*model.FundFlow) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f fundFlowDo) CreateInBatches(values []*model.FundFlow, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f fundFlowDo) Save(values ...*model.FundFlow) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f fundFlowDo) First() (*model.FundFlow, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.FundFlow), nil
	}
}

func (f fundFlowDo) Take() (*model.FundFlow, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.FundFlow), nil
	}
}

func (f fundFlowDo) Last() (*model.FundFlow, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.FundFlow), nil
	}
}

func (f fundFlowDo) Find() ([]*model.FundFlow, error) {
	result, err := f.DO.Find()
	return result.([]*model.FundFlow), err
}

func (f fundFlowDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FundFlow, err error) {
	buf := make([]*model.FundFlow, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f fundFlowDo) FindInBatches(result *[]*model.FundFlow, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f fundFlowDo) Attrs(attrs ...field.AssignExpr) IFundFlowDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f fundFlowDo) Assign(attrs ...field.AssignExpr) IFundFlowDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f fundFlowDo) Joins(fields ...field.RelationField) IFundFlowDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f fundFlowDo) Preload(fields ...field.RelationField) IFundFlowDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f fundFlowDo) FirstOrInit() (*model.FundFlow, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.FundFlow), nil
	}
}

func (f fundFlowDo) FirstOrCreate() (*model.FundFlow, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.FundFlow), nil
	}
}

func (f fundFlowDo) FindByPage(offset int, limit int) (result []*model.FundFlow, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f fundFlowDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f fundFlowDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f fundFlowDo) Delete(models ...*model.FundFlow) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *fundFlowDo) withDO(do gen.Dao) *fundFlowDo {
	f.DO = *do.(*gen.DO)
	return f
}
