// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"oshit-go/common/pkg/dal/model"
)

func newGiveTokenRecord(db *gorm.DB, opts ...gen.DOOption) giveTokenRecord {
	_giveTokenRecord := giveTokenRecord{}

	_giveTokenRecord.giveTokenRecordDo.UseDB(db, opts...)
	_giveTokenRecord.giveTokenRecordDo.UseModel(&model.GiveTokenRecord{})

	tableName := _giveTokenRecord.giveTokenRecordDo.TableName()
	_giveTokenRecord.ALL = field.NewAsterisk(tableName)
	_giveTokenRecord.RecordID = field.NewString(tableName, "record_id")
	_giveTokenRecord.FromAccount = field.NewString(tableName, "from_account")
	_giveTokenRecord.ReceiptAccount = field.NewString(tableName, "receipt_account")
	_giveTokenRecord.TxID = field.NewString(tableName, "tx_id")
	_giveTokenRecord.Amount = field.NewFloat64(tableName, "amount")
	_giveTokenRecord.State = field.NewInt32(tableName, "state")
	_giveTokenRecord.CreatedAt = field.NewTime(tableName, "created_at")
	_giveTokenRecord.UpdatedAt = field.NewTime(tableName, "updated_at")

	_giveTokenRecord.fillFieldMap()

	return _giveTokenRecord
}

type giveTokenRecord struct {
	giveTokenRecordDo giveTokenRecordDo

	ALL            field.Asterisk
	RecordID       field.String
	FromAccount    field.String
	ReceiptAccount field.String
	TxID           field.String
	Amount         field.Float64
	State          field.Int32
	CreatedAt      field.Time
	UpdatedAt      field.Time

	fieldMap map[string]field.Expr
}

func (g giveTokenRecord) Table(newTableName string) *giveTokenRecord {
	g.giveTokenRecordDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g giveTokenRecord) As(alias string) *giveTokenRecord {
	g.giveTokenRecordDo.DO = *(g.giveTokenRecordDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *giveTokenRecord) updateTableName(table string) *giveTokenRecord {
	g.ALL = field.NewAsterisk(table)
	g.RecordID = field.NewString(table, "record_id")
	g.FromAccount = field.NewString(table, "from_account")
	g.ReceiptAccount = field.NewString(table, "receipt_account")
	g.TxID = field.NewString(table, "tx_id")
	g.Amount = field.NewFloat64(table, "amount")
	g.State = field.NewInt32(table, "state")
	g.CreatedAt = field.NewTime(table, "created_at")
	g.UpdatedAt = field.NewTime(table, "updated_at")

	g.fillFieldMap()

	return g
}

func (g *giveTokenRecord) WithContext(ctx context.Context) IGiveTokenRecordDo {
	return g.giveTokenRecordDo.WithContext(ctx)
}

func (g giveTokenRecord) TableName() string { return g.giveTokenRecordDo.TableName() }

func (g giveTokenRecord) Alias() string { return g.giveTokenRecordDo.Alias() }

func (g giveTokenRecord) Columns(cols ...field.Expr) gen.Columns {
	return g.giveTokenRecordDo.Columns(cols...)
}

func (g *giveTokenRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *giveTokenRecord) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 8)
	g.fieldMap["record_id"] = g.RecordID
	g.fieldMap["from_account"] = g.FromAccount
	g.fieldMap["receipt_account"] = g.ReceiptAccount
	g.fieldMap["tx_id"] = g.TxID
	g.fieldMap["amount"] = g.Amount
	g.fieldMap["state"] = g.State
	g.fieldMap["created_at"] = g.CreatedAt
	g.fieldMap["updated_at"] = g.UpdatedAt
}

func (g giveTokenRecord) clone(db *gorm.DB) giveTokenRecord {
	g.giveTokenRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g giveTokenRecord) replaceDB(db *gorm.DB) giveTokenRecord {
	g.giveTokenRecordDo.ReplaceDB(db)
	return g
}

type giveTokenRecordDo struct{ gen.DO }

type IGiveTokenRecordDo interface {
	gen.SubQuery
	Debug() IGiveTokenRecordDo
	WithContext(ctx context.Context) IGiveTokenRecordDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IGiveTokenRecordDo
	WriteDB() IGiveTokenRecordDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IGiveTokenRecordDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IGiveTokenRecordDo
	Not(conds ...gen.Condition) IGiveTokenRecordDo
	Or(conds ...gen.Condition) IGiveTokenRecordDo
	Select(conds ...field.Expr) IGiveTokenRecordDo
	Where(conds ...gen.Condition) IGiveTokenRecordDo
	Order(conds ...field.Expr) IGiveTokenRecordDo
	Distinct(cols ...field.Expr) IGiveTokenRecordDo
	Omit(cols ...field.Expr) IGiveTokenRecordDo
	Join(table schema.Tabler, on ...field.Expr) IGiveTokenRecordDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IGiveTokenRecordDo
	RightJoin(table schema.Tabler, on ...field.Expr) IGiveTokenRecordDo
	Group(cols ...field.Expr) IGiveTokenRecordDo
	Having(conds ...gen.Condition) IGiveTokenRecordDo
	Limit(limit int) IGiveTokenRecordDo
	Offset(offset int) IGiveTokenRecordDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IGiveTokenRecordDo
	Unscoped() IGiveTokenRecordDo
	Create(values ...*model.GiveTokenRecord) error
	CreateInBatches(values []*model.GiveTokenRecord, batchSize int) error
	Save(values ...*model.GiveTokenRecord) error
	First() (*model.GiveTokenRecord, error)
	Take() (*model.GiveTokenRecord, error)
	Last() (*model.GiveTokenRecord, error)
	Find() ([]*model.GiveTokenRecord, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GiveTokenRecord, err error)
	FindInBatches(result *[]*model.GiveTokenRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.GiveTokenRecord) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IGiveTokenRecordDo
	Assign(attrs ...field.AssignExpr) IGiveTokenRecordDo
	Joins(fields ...field.RelationField) IGiveTokenRecordDo
	Preload(fields ...field.RelationField) IGiveTokenRecordDo
	FirstOrInit() (*model.GiveTokenRecord, error)
	FirstOrCreate() (*model.GiveTokenRecord, error)
	FindByPage(offset int, limit int) (result []*model.GiveTokenRecord, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IGiveTokenRecordDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (g giveTokenRecordDo) Debug() IGiveTokenRecordDo {
	return g.withDO(g.DO.Debug())
}

func (g giveTokenRecordDo) WithContext(ctx context.Context) IGiveTokenRecordDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g giveTokenRecordDo) ReadDB() IGiveTokenRecordDo {
	return g.Clauses(dbresolver.Read)
}

func (g giveTokenRecordDo) WriteDB() IGiveTokenRecordDo {
	return g.Clauses(dbresolver.Write)
}

func (g giveTokenRecordDo) Session(config *gorm.Session) IGiveTokenRecordDo {
	return g.withDO(g.DO.Session(config))
}

func (g giveTokenRecordDo) Clauses(conds ...clause.Expression) IGiveTokenRecordDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g giveTokenRecordDo) Returning(value interface{}, columns ...string) IGiveTokenRecordDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g giveTokenRecordDo) Not(conds ...gen.Condition) IGiveTokenRecordDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g giveTokenRecordDo) Or(conds ...gen.Condition) IGiveTokenRecordDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g giveTokenRecordDo) Select(conds ...field.Expr) IGiveTokenRecordDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g giveTokenRecordDo) Where(conds ...gen.Condition) IGiveTokenRecordDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g giveTokenRecordDo) Order(conds ...field.Expr) IGiveTokenRecordDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g giveTokenRecordDo) Distinct(cols ...field.Expr) IGiveTokenRecordDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g giveTokenRecordDo) Omit(cols ...field.Expr) IGiveTokenRecordDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g giveTokenRecordDo) Join(table schema.Tabler, on ...field.Expr) IGiveTokenRecordDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g giveTokenRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) IGiveTokenRecordDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g giveTokenRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) IGiveTokenRecordDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g giveTokenRecordDo) Group(cols ...field.Expr) IGiveTokenRecordDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g giveTokenRecordDo) Having(conds ...gen.Condition) IGiveTokenRecordDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g giveTokenRecordDo) Limit(limit int) IGiveTokenRecordDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g giveTokenRecordDo) Offset(offset int) IGiveTokenRecordDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g giveTokenRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IGiveTokenRecordDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g giveTokenRecordDo) Unscoped() IGiveTokenRecordDo {
	return g.withDO(g.DO.Unscoped())
}

func (g giveTokenRecordDo) Create(values ...*model.GiveTokenRecord) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g giveTokenRecordDo) CreateInBatches(values []*model.GiveTokenRecord, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g giveTokenRecordDo) Save(values ...*model.GiveTokenRecord) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g giveTokenRecordDo) First() (*model.GiveTokenRecord, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.GiveTokenRecord), nil
	}
}

func (g giveTokenRecordDo) Take() (*model.GiveTokenRecord, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.GiveTokenRecord), nil
	}
}

func (g giveTokenRecordDo) Last() (*model.GiveTokenRecord, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.GiveTokenRecord), nil
	}
}

func (g giveTokenRecordDo) Find() ([]*model.GiveTokenRecord, error) {
	result, err := g.DO.Find()
	return result.([]*model.GiveTokenRecord), err
}

func (g giveTokenRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GiveTokenRecord, err error) {
	buf := make([]*model.GiveTokenRecord, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g giveTokenRecordDo) FindInBatches(result *[]*model.GiveTokenRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g giveTokenRecordDo) Attrs(attrs ...field.AssignExpr) IGiveTokenRecordDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g giveTokenRecordDo) Assign(attrs ...field.AssignExpr) IGiveTokenRecordDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g giveTokenRecordDo) Joins(fields ...field.RelationField) IGiveTokenRecordDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g giveTokenRecordDo) Preload(fields ...field.RelationField) IGiveTokenRecordDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g giveTokenRecordDo) FirstOrInit() (*model.GiveTokenRecord, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.GiveTokenRecord), nil
	}
}

func (g giveTokenRecordDo) FirstOrCreate() (*model.GiveTokenRecord, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.GiveTokenRecord), nil
	}
}

func (g giveTokenRecordDo) FindByPage(offset int, limit int) (result []*model.GiveTokenRecord, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g giveTokenRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g giveTokenRecordDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g giveTokenRecordDo) Delete(models ...*model.GiveTokenRecord) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *giveTokenRecordDo) withDO(do gen.Dao) *giveTokenRecordDo {
	g.DO = *do.(*gen.DO)
	return g
}
