// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"oshit-go/common/pkg/dal/model"
)

func newHackerAccount(db *gorm.DB, opts ...gen.DOOption) hackerAccount {
	_hackerAccount := hackerAccount{}

	_hackerAccount.hackerAccountDo.UseDB(db, opts...)
	_hackerAccount.hackerAccountDo.UseModel(&model.HackerAccount{})

	tableName := _hackerAccount.hackerAccountDo.TableName()
	_hackerAccount.ALL = field.NewAsterisk(tableName)
	_hackerAccount.RecordID = field.NewString(tableName, "record_id")
	_hackerAccount.NativeAccount = field.NewString(tableName, "native_account")
	_hackerAccount.CreatedAt = field.NewTime(tableName, "created_at")
	_hackerAccount.UpdatedAt = field.NewTime(tableName, "updated_at")

	_hackerAccount.fillFieldMap()

	return _hackerAccount
}

type hackerAccount struct {
	hackerAccountDo hackerAccountDo

	ALL           field.Asterisk
	RecordID      field.String
	NativeAccount field.String
	CreatedAt     field.Time
	UpdatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (h hackerAccount) Table(newTableName string) *hackerAccount {
	h.hackerAccountDo.UseTable(newTableName)
	return h.updateTableName(newTableName)
}

func (h hackerAccount) As(alias string) *hackerAccount {
	h.hackerAccountDo.DO = *(h.hackerAccountDo.As(alias).(*gen.DO))
	return h.updateTableName(alias)
}

func (h *hackerAccount) updateTableName(table string) *hackerAccount {
	h.ALL = field.NewAsterisk(table)
	h.RecordID = field.NewString(table, "record_id")
	h.NativeAccount = field.NewString(table, "native_account")
	h.CreatedAt = field.NewTime(table, "created_at")
	h.UpdatedAt = field.NewTime(table, "updated_at")

	h.fillFieldMap()

	return h
}

func (h *hackerAccount) WithContext(ctx context.Context) IHackerAccountDo {
	return h.hackerAccountDo.WithContext(ctx)
}

func (h hackerAccount) TableName() string { return h.hackerAccountDo.TableName() }

func (h hackerAccount) Alias() string { return h.hackerAccountDo.Alias() }

func (h hackerAccount) Columns(cols ...field.Expr) gen.Columns {
	return h.hackerAccountDo.Columns(cols...)
}

func (h *hackerAccount) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := h.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (h *hackerAccount) fillFieldMap() {
	h.fieldMap = make(map[string]field.Expr, 4)
	h.fieldMap["record_id"] = h.RecordID
	h.fieldMap["native_account"] = h.NativeAccount
	h.fieldMap["created_at"] = h.CreatedAt
	h.fieldMap["updated_at"] = h.UpdatedAt
}

func (h hackerAccount) clone(db *gorm.DB) hackerAccount {
	h.hackerAccountDo.ReplaceConnPool(db.Statement.ConnPool)
	return h
}

func (h hackerAccount) replaceDB(db *gorm.DB) hackerAccount {
	h.hackerAccountDo.ReplaceDB(db)
	return h
}

type hackerAccountDo struct{ gen.DO }

type IHackerAccountDo interface {
	gen.SubQuery
	Debug() IHackerAccountDo
	WithContext(ctx context.Context) IHackerAccountDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IHackerAccountDo
	WriteDB() IHackerAccountDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IHackerAccountDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IHackerAccountDo
	Not(conds ...gen.Condition) IHackerAccountDo
	Or(conds ...gen.Condition) IHackerAccountDo
	Select(conds ...field.Expr) IHackerAccountDo
	Where(conds ...gen.Condition) IHackerAccountDo
	Order(conds ...field.Expr) IHackerAccountDo
	Distinct(cols ...field.Expr) IHackerAccountDo
	Omit(cols ...field.Expr) IHackerAccountDo
	Join(table schema.Tabler, on ...field.Expr) IHackerAccountDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IHackerAccountDo
	RightJoin(table schema.Tabler, on ...field.Expr) IHackerAccountDo
	Group(cols ...field.Expr) IHackerAccountDo
	Having(conds ...gen.Condition) IHackerAccountDo
	Limit(limit int) IHackerAccountDo
	Offset(offset int) IHackerAccountDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IHackerAccountDo
	Unscoped() IHackerAccountDo
	Create(values ...*model.HackerAccount) error
	CreateInBatches(values []*model.HackerAccount, batchSize int) error
	Save(values ...*model.HackerAccount) error
	First() (*model.HackerAccount, error)
	Take() (*model.HackerAccount, error)
	Last() (*model.HackerAccount, error)
	Find() ([]*model.HackerAccount, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.HackerAccount, err error)
	FindInBatches(result *[]*model.HackerAccount, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.HackerAccount) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IHackerAccountDo
	Assign(attrs ...field.AssignExpr) IHackerAccountDo
	Joins(fields ...field.RelationField) IHackerAccountDo
	Preload(fields ...field.RelationField) IHackerAccountDo
	FirstOrInit() (*model.HackerAccount, error)
	FirstOrCreate() (*model.HackerAccount, error)
	FindByPage(offset int, limit int) (result []*model.HackerAccount, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IHackerAccountDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (h hackerAccountDo) Debug() IHackerAccountDo {
	return h.withDO(h.DO.Debug())
}

func (h hackerAccountDo) WithContext(ctx context.Context) IHackerAccountDo {
	return h.withDO(h.DO.WithContext(ctx))
}

func (h hackerAccountDo) ReadDB() IHackerAccountDo {
	return h.Clauses(dbresolver.Read)
}

func (h hackerAccountDo) WriteDB() IHackerAccountDo {
	return h.Clauses(dbresolver.Write)
}

func (h hackerAccountDo) Session(config *gorm.Session) IHackerAccountDo {
	return h.withDO(h.DO.Session(config))
}

func (h hackerAccountDo) Clauses(conds ...clause.Expression) IHackerAccountDo {
	return h.withDO(h.DO.Clauses(conds...))
}

func (h hackerAccountDo) Returning(value interface{}, columns ...string) IHackerAccountDo {
	return h.withDO(h.DO.Returning(value, columns...))
}

func (h hackerAccountDo) Not(conds ...gen.Condition) IHackerAccountDo {
	return h.withDO(h.DO.Not(conds...))
}

func (h hackerAccountDo) Or(conds ...gen.Condition) IHackerAccountDo {
	return h.withDO(h.DO.Or(conds...))
}

func (h hackerAccountDo) Select(conds ...field.Expr) IHackerAccountDo {
	return h.withDO(h.DO.Select(conds...))
}

func (h hackerAccountDo) Where(conds ...gen.Condition) IHackerAccountDo {
	return h.withDO(h.DO.Where(conds...))
}

func (h hackerAccountDo) Order(conds ...field.Expr) IHackerAccountDo {
	return h.withDO(h.DO.Order(conds...))
}

func (h hackerAccountDo) Distinct(cols ...field.Expr) IHackerAccountDo {
	return h.withDO(h.DO.Distinct(cols...))
}

func (h hackerAccountDo) Omit(cols ...field.Expr) IHackerAccountDo {
	return h.withDO(h.DO.Omit(cols...))
}

func (h hackerAccountDo) Join(table schema.Tabler, on ...field.Expr) IHackerAccountDo {
	return h.withDO(h.DO.Join(table, on...))
}

func (h hackerAccountDo) LeftJoin(table schema.Tabler, on ...field.Expr) IHackerAccountDo {
	return h.withDO(h.DO.LeftJoin(table, on...))
}

func (h hackerAccountDo) RightJoin(table schema.Tabler, on ...field.Expr) IHackerAccountDo {
	return h.withDO(h.DO.RightJoin(table, on...))
}

func (h hackerAccountDo) Group(cols ...field.Expr) IHackerAccountDo {
	return h.withDO(h.DO.Group(cols...))
}

func (h hackerAccountDo) Having(conds ...gen.Condition) IHackerAccountDo {
	return h.withDO(h.DO.Having(conds...))
}

func (h hackerAccountDo) Limit(limit int) IHackerAccountDo {
	return h.withDO(h.DO.Limit(limit))
}

func (h hackerAccountDo) Offset(offset int) IHackerAccountDo {
	return h.withDO(h.DO.Offset(offset))
}

func (h hackerAccountDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IHackerAccountDo {
	return h.withDO(h.DO.Scopes(funcs...))
}

func (h hackerAccountDo) Unscoped() IHackerAccountDo {
	return h.withDO(h.DO.Unscoped())
}

func (h hackerAccountDo) Create(values ...*model.HackerAccount) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Create(values)
}

func (h hackerAccountDo) CreateInBatches(values []*model.HackerAccount, batchSize int) error {
	return h.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (h hackerAccountDo) Save(values ...*model.HackerAccount) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Save(values)
}

func (h hackerAccountDo) First() (*model.HackerAccount, error) {
	if result, err := h.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.HackerAccount), nil
	}
}

func (h hackerAccountDo) Take() (*model.HackerAccount, error) {
	if result, err := h.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.HackerAccount), nil
	}
}

func (h hackerAccountDo) Last() (*model.HackerAccount, error) {
	if result, err := h.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.HackerAccount), nil
	}
}

func (h hackerAccountDo) Find() ([]*model.HackerAccount, error) {
	result, err := h.DO.Find()
	return result.([]*model.HackerAccount), err
}

func (h hackerAccountDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.HackerAccount, err error) {
	buf := make([]*model.HackerAccount, 0, batchSize)
	err = h.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (h hackerAccountDo) FindInBatches(result *[]*model.HackerAccount, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return h.DO.FindInBatches(result, batchSize, fc)
}

func (h hackerAccountDo) Attrs(attrs ...field.AssignExpr) IHackerAccountDo {
	return h.withDO(h.DO.Attrs(attrs...))
}

func (h hackerAccountDo) Assign(attrs ...field.AssignExpr) IHackerAccountDo {
	return h.withDO(h.DO.Assign(attrs...))
}

func (h hackerAccountDo) Joins(fields ...field.RelationField) IHackerAccountDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Joins(_f))
	}
	return &h
}

func (h hackerAccountDo) Preload(fields ...field.RelationField) IHackerAccountDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Preload(_f))
	}
	return &h
}

func (h hackerAccountDo) FirstOrInit() (*model.HackerAccount, error) {
	if result, err := h.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.HackerAccount), nil
	}
}

func (h hackerAccountDo) FirstOrCreate() (*model.HackerAccount, error) {
	if result, err := h.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.HackerAccount), nil
	}
}

func (h hackerAccountDo) FindByPage(offset int, limit int) (result []*model.HackerAccount, count int64, err error) {
	result, err = h.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = h.Offset(-1).Limit(-1).Count()
	return
}

func (h hackerAccountDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = h.Count()
	if err != nil {
		return
	}

	err = h.Offset(offset).Limit(limit).Scan(result)
	return
}

func (h hackerAccountDo) Scan(result interface{}) (err error) {
	return h.DO.Scan(result)
}

func (h hackerAccountDo) Delete(models ...*model.HackerAccount) (result gen.ResultInfo, err error) {
	return h.DO.Delete(models)
}

func (h *hackerAccountDo) withDO(do gen.Dao) *hackerAccountDo {
	h.DO = *do.(*gen.DO)
	return h
}
