// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"oshit-go/common/pkg/dal/model"
)

func newLotteryReward(db *gorm.DB, opts ...gen.DOOption) lotteryReward {
	_lotteryReward := lotteryReward{}

	_lotteryReward.lotteryRewardDo.UseDB(db, opts...)
	_lotteryReward.lotteryRewardDo.UseModel(&model.LotteryReward{})

	tableName := _lotteryReward.lotteryRewardDo.TableName()
	_lotteryReward.ALL = field.NewAsterisk(tableName)
	_lotteryReward.RecordID = field.NewString(tableName, "record_id")
	_lotteryReward.NativeAccount = field.NewString(tableName, "native_account")
	_lotteryReward.RewardAmount = field.NewFloat64(tableName, "reward_amount")
	_lotteryReward.RewardType = field.NewInt32(tableName, "reward_type")
	_lotteryReward.State = field.NewInt32(tableName, "state")
	_lotteryReward.Pending = field.NewBool(tableName, "pending")
	_lotteryReward.RewardDay = field.NewTime(tableName, "reward_day")
	_lotteryReward.CreatedAt = field.NewTime(tableName, "created_at")
	_lotteryReward.UpdatedAt = field.NewTime(tableName, "updated_at")

	_lotteryReward.fillFieldMap()

	return _lotteryReward
}

type lotteryReward struct {
	lotteryRewardDo lotteryRewardDo

	ALL           field.Asterisk
	RecordID      field.String
	NativeAccount field.String
	RewardAmount  field.Float64
	RewardType    field.Int32
	State         field.Int32
	Pending       field.Bool
	RewardDay     field.Time
	CreatedAt     field.Time
	UpdatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (l lotteryReward) Table(newTableName string) *lotteryReward {
	l.lotteryRewardDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l lotteryReward) As(alias string) *lotteryReward {
	l.lotteryRewardDo.DO = *(l.lotteryRewardDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *lotteryReward) updateTableName(table string) *lotteryReward {
	l.ALL = field.NewAsterisk(table)
	l.RecordID = field.NewString(table, "record_id")
	l.NativeAccount = field.NewString(table, "native_account")
	l.RewardAmount = field.NewFloat64(table, "reward_amount")
	l.RewardType = field.NewInt32(table, "reward_type")
	l.State = field.NewInt32(table, "state")
	l.Pending = field.NewBool(table, "pending")
	l.RewardDay = field.NewTime(table, "reward_day")
	l.CreatedAt = field.NewTime(table, "created_at")
	l.UpdatedAt = field.NewTime(table, "updated_at")

	l.fillFieldMap()

	return l
}

func (l *lotteryReward) WithContext(ctx context.Context) ILotteryRewardDo {
	return l.lotteryRewardDo.WithContext(ctx)
}

func (l lotteryReward) TableName() string { return l.lotteryRewardDo.TableName() }

func (l lotteryReward) Alias() string { return l.lotteryRewardDo.Alias() }

func (l lotteryReward) Columns(cols ...field.Expr) gen.Columns {
	return l.lotteryRewardDo.Columns(cols...)
}

func (l *lotteryReward) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *lotteryReward) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 9)
	l.fieldMap["record_id"] = l.RecordID
	l.fieldMap["native_account"] = l.NativeAccount
	l.fieldMap["reward_amount"] = l.RewardAmount
	l.fieldMap["reward_type"] = l.RewardType
	l.fieldMap["state"] = l.State
	l.fieldMap["pending"] = l.Pending
	l.fieldMap["reward_day"] = l.RewardDay
	l.fieldMap["created_at"] = l.CreatedAt
	l.fieldMap["updated_at"] = l.UpdatedAt
}

func (l lotteryReward) clone(db *gorm.DB) lotteryReward {
	l.lotteryRewardDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l lotteryReward) replaceDB(db *gorm.DB) lotteryReward {
	l.lotteryRewardDo.ReplaceDB(db)
	return l
}

type lotteryRewardDo struct{ gen.DO }

type ILotteryRewardDo interface {
	gen.SubQuery
	Debug() ILotteryRewardDo
	WithContext(ctx context.Context) ILotteryRewardDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ILotteryRewardDo
	WriteDB() ILotteryRewardDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ILotteryRewardDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ILotteryRewardDo
	Not(conds ...gen.Condition) ILotteryRewardDo
	Or(conds ...gen.Condition) ILotteryRewardDo
	Select(conds ...field.Expr) ILotteryRewardDo
	Where(conds ...gen.Condition) ILotteryRewardDo
	Order(conds ...field.Expr) ILotteryRewardDo
	Distinct(cols ...field.Expr) ILotteryRewardDo
	Omit(cols ...field.Expr) ILotteryRewardDo
	Join(table schema.Tabler, on ...field.Expr) ILotteryRewardDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ILotteryRewardDo
	RightJoin(table schema.Tabler, on ...field.Expr) ILotteryRewardDo
	Group(cols ...field.Expr) ILotteryRewardDo
	Having(conds ...gen.Condition) ILotteryRewardDo
	Limit(limit int) ILotteryRewardDo
	Offset(offset int) ILotteryRewardDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ILotteryRewardDo
	Unscoped() ILotteryRewardDo
	Create(values ...*model.LotteryReward) error
	CreateInBatches(values []*model.LotteryReward, batchSize int) error
	Save(values ...*model.LotteryReward) error
	First() (*model.LotteryReward, error)
	Take() (*model.LotteryReward, error)
	Last() (*model.LotteryReward, error)
	Find() ([]*model.LotteryReward, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LotteryReward, err error)
	FindInBatches(result *[]*model.LotteryReward, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.LotteryReward) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ILotteryRewardDo
	Assign(attrs ...field.AssignExpr) ILotteryRewardDo
	Joins(fields ...field.RelationField) ILotteryRewardDo
	Preload(fields ...field.RelationField) ILotteryRewardDo
	FirstOrInit() (*model.LotteryReward, error)
	FirstOrCreate() (*model.LotteryReward, error)
	FindByPage(offset int, limit int) (result []*model.LotteryReward, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ILotteryRewardDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (l lotteryRewardDo) Debug() ILotteryRewardDo {
	return l.withDO(l.DO.Debug())
}

func (l lotteryRewardDo) WithContext(ctx context.Context) ILotteryRewardDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l lotteryRewardDo) ReadDB() ILotteryRewardDo {
	return l.Clauses(dbresolver.Read)
}

func (l lotteryRewardDo) WriteDB() ILotteryRewardDo {
	return l.Clauses(dbresolver.Write)
}

func (l lotteryRewardDo) Session(config *gorm.Session) ILotteryRewardDo {
	return l.withDO(l.DO.Session(config))
}

func (l lotteryRewardDo) Clauses(conds ...clause.Expression) ILotteryRewardDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l lotteryRewardDo) Returning(value interface{}, columns ...string) ILotteryRewardDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l lotteryRewardDo) Not(conds ...gen.Condition) ILotteryRewardDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l lotteryRewardDo) Or(conds ...gen.Condition) ILotteryRewardDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l lotteryRewardDo) Select(conds ...field.Expr) ILotteryRewardDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l lotteryRewardDo) Where(conds ...gen.Condition) ILotteryRewardDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l lotteryRewardDo) Order(conds ...field.Expr) ILotteryRewardDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l lotteryRewardDo) Distinct(cols ...field.Expr) ILotteryRewardDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l lotteryRewardDo) Omit(cols ...field.Expr) ILotteryRewardDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l lotteryRewardDo) Join(table schema.Tabler, on ...field.Expr) ILotteryRewardDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l lotteryRewardDo) LeftJoin(table schema.Tabler, on ...field.Expr) ILotteryRewardDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l lotteryRewardDo) RightJoin(table schema.Tabler, on ...field.Expr) ILotteryRewardDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l lotteryRewardDo) Group(cols ...field.Expr) ILotteryRewardDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l lotteryRewardDo) Having(conds ...gen.Condition) ILotteryRewardDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l lotteryRewardDo) Limit(limit int) ILotteryRewardDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l lotteryRewardDo) Offset(offset int) ILotteryRewardDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l lotteryRewardDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ILotteryRewardDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l lotteryRewardDo) Unscoped() ILotteryRewardDo {
	return l.withDO(l.DO.Unscoped())
}

func (l lotteryRewardDo) Create(values ...*model.LotteryReward) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l lotteryRewardDo) CreateInBatches(values []*model.LotteryReward, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l lotteryRewardDo) Save(values ...*model.LotteryReward) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l lotteryRewardDo) First() (*model.LotteryReward, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.LotteryReward), nil
	}
}

func (l lotteryRewardDo) Take() (*model.LotteryReward, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.LotteryReward), nil
	}
}

func (l lotteryRewardDo) Last() (*model.LotteryReward, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.LotteryReward), nil
	}
}

func (l lotteryRewardDo) Find() ([]*model.LotteryReward, error) {
	result, err := l.DO.Find()
	return result.([]*model.LotteryReward), err
}

func (l lotteryRewardDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LotteryReward, err error) {
	buf := make([]*model.LotteryReward, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l lotteryRewardDo) FindInBatches(result *[]*model.LotteryReward, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l lotteryRewardDo) Attrs(attrs ...field.AssignExpr) ILotteryRewardDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l lotteryRewardDo) Assign(attrs ...field.AssignExpr) ILotteryRewardDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l lotteryRewardDo) Joins(fields ...field.RelationField) ILotteryRewardDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l lotteryRewardDo) Preload(fields ...field.RelationField) ILotteryRewardDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l lotteryRewardDo) FirstOrInit() (*model.LotteryReward, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.LotteryReward), nil
	}
}

func (l lotteryRewardDo) FirstOrCreate() (*model.LotteryReward, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.LotteryReward), nil
	}
}

func (l lotteryRewardDo) FindByPage(offset int, limit int) (result []*model.LotteryReward, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l lotteryRewardDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l lotteryRewardDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l lotteryRewardDo) Delete(models ...*model.LotteryReward) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *lotteryRewardDo) withDO(do gen.Dao) *lotteryRewardDo {
	l.DO = *do.(*gen.DO)
	return l
}
