// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"oshit-go/common/pkg/dal/model"
)

func newPosReward(db *gorm.DB, opts ...gen.DOOption) posReward {
	_posReward := posReward{}

	_posReward.posRewardDo.UseDB(db, opts...)
	_posReward.posRewardDo.UseModel(&model.PosReward{})

	tableName := _posReward.posRewardDo.TableName()
	_posReward.ALL = field.NewAsterisk(tableName)
	_posReward.RecordID = field.NewString(tableName, "record_id")
	_posReward.GroupID = field.NewString(tableName, "group_id")
	_posReward.NativeAccount = field.NewString(tableName, "native_account")
	_posReward.StarLevel = field.NewInt32(tableName, "star_level")
	_posReward.Base = field.NewFloat64(tableName, "base")
	_posReward.Rate = field.NewFloat64(tableName, "rate")
	_posReward.RewardAmount = field.NewFloat64(tableName, "reward_amount")
	_posReward.RewardType = field.NewInt32(tableName, "reward_type")
	_posReward.RewardState = field.NewInt32(tableName, "reward_state")
	_posReward.Starred = field.NewBool(tableName, "starred")
	_posReward.Pending = field.NewBool(tableName, "pending")
	_posReward.SnapDay = field.NewTime(tableName, "snap_day")
	_posReward.CreatedAt = field.NewTime(tableName, "created_at")
	_posReward.UpdatedAt = field.NewTime(tableName, "updated_at")

	_posReward.fillFieldMap()

	return _posReward
}

type posReward struct {
	posRewardDo posRewardDo

	ALL           field.Asterisk
	RecordID      field.String
	GroupID       field.String
	NativeAccount field.String
	StarLevel     field.Int32
	Base          field.Float64
	Rate          field.Float64
	RewardAmount  field.Float64
	RewardType    field.Int32
	RewardState   field.Int32
	Starred       field.Bool
	Pending       field.Bool
	SnapDay       field.Time
	CreatedAt     field.Time
	UpdatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (p posReward) Table(newTableName string) *posReward {
	p.posRewardDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p posReward) As(alias string) *posReward {
	p.posRewardDo.DO = *(p.posRewardDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *posReward) updateTableName(table string) *posReward {
	p.ALL = field.NewAsterisk(table)
	p.RecordID = field.NewString(table, "record_id")
	p.GroupID = field.NewString(table, "group_id")
	p.NativeAccount = field.NewString(table, "native_account")
	p.StarLevel = field.NewInt32(table, "star_level")
	p.Base = field.NewFloat64(table, "base")
	p.Rate = field.NewFloat64(table, "rate")
	p.RewardAmount = field.NewFloat64(table, "reward_amount")
	p.RewardType = field.NewInt32(table, "reward_type")
	p.RewardState = field.NewInt32(table, "reward_state")
	p.Starred = field.NewBool(table, "starred")
	p.Pending = field.NewBool(table, "pending")
	p.SnapDay = field.NewTime(table, "snap_day")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")

	p.fillFieldMap()

	return p
}

func (p *posReward) WithContext(ctx context.Context) IPosRewardDo {
	return p.posRewardDo.WithContext(ctx)
}

func (p posReward) TableName() string { return p.posRewardDo.TableName() }

func (p posReward) Alias() string { return p.posRewardDo.Alias() }

func (p posReward) Columns(cols ...field.Expr) gen.Columns { return p.posRewardDo.Columns(cols...) }

func (p *posReward) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *posReward) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 14)
	p.fieldMap["record_id"] = p.RecordID
	p.fieldMap["group_id"] = p.GroupID
	p.fieldMap["native_account"] = p.NativeAccount
	p.fieldMap["star_level"] = p.StarLevel
	p.fieldMap["base"] = p.Base
	p.fieldMap["rate"] = p.Rate
	p.fieldMap["reward_amount"] = p.RewardAmount
	p.fieldMap["reward_type"] = p.RewardType
	p.fieldMap["reward_state"] = p.RewardState
	p.fieldMap["starred"] = p.Starred
	p.fieldMap["pending"] = p.Pending
	p.fieldMap["snap_day"] = p.SnapDay
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
}

func (p posReward) clone(db *gorm.DB) posReward {
	p.posRewardDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p posReward) replaceDB(db *gorm.DB) posReward {
	p.posRewardDo.ReplaceDB(db)
	return p
}

type posRewardDo struct{ gen.DO }

type IPosRewardDo interface {
	gen.SubQuery
	Debug() IPosRewardDo
	WithContext(ctx context.Context) IPosRewardDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPosRewardDo
	WriteDB() IPosRewardDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPosRewardDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPosRewardDo
	Not(conds ...gen.Condition) IPosRewardDo
	Or(conds ...gen.Condition) IPosRewardDo
	Select(conds ...field.Expr) IPosRewardDo
	Where(conds ...gen.Condition) IPosRewardDo
	Order(conds ...field.Expr) IPosRewardDo
	Distinct(cols ...field.Expr) IPosRewardDo
	Omit(cols ...field.Expr) IPosRewardDo
	Join(table schema.Tabler, on ...field.Expr) IPosRewardDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPosRewardDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPosRewardDo
	Group(cols ...field.Expr) IPosRewardDo
	Having(conds ...gen.Condition) IPosRewardDo
	Limit(limit int) IPosRewardDo
	Offset(offset int) IPosRewardDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPosRewardDo
	Unscoped() IPosRewardDo
	Create(values ...*model.PosReward) error
	CreateInBatches(values []*model.PosReward, batchSize int) error
	Save(values ...*model.PosReward) error
	First() (*model.PosReward, error)
	Take() (*model.PosReward, error)
	Last() (*model.PosReward, error)
	Find() ([]*model.PosReward, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PosReward, err error)
	FindInBatches(result *[]*model.PosReward, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PosReward) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPosRewardDo
	Assign(attrs ...field.AssignExpr) IPosRewardDo
	Joins(fields ...field.RelationField) IPosRewardDo
	Preload(fields ...field.RelationField) IPosRewardDo
	FirstOrInit() (*model.PosReward, error)
	FirstOrCreate() (*model.PosReward, error)
	FindByPage(offset int, limit int) (result []*model.PosReward, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPosRewardDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p posRewardDo) Debug() IPosRewardDo {
	return p.withDO(p.DO.Debug())
}

func (p posRewardDo) WithContext(ctx context.Context) IPosRewardDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p posRewardDo) ReadDB() IPosRewardDo {
	return p.Clauses(dbresolver.Read)
}

func (p posRewardDo) WriteDB() IPosRewardDo {
	return p.Clauses(dbresolver.Write)
}

func (p posRewardDo) Session(config *gorm.Session) IPosRewardDo {
	return p.withDO(p.DO.Session(config))
}

func (p posRewardDo) Clauses(conds ...clause.Expression) IPosRewardDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p posRewardDo) Returning(value interface{}, columns ...string) IPosRewardDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p posRewardDo) Not(conds ...gen.Condition) IPosRewardDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p posRewardDo) Or(conds ...gen.Condition) IPosRewardDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p posRewardDo) Select(conds ...field.Expr) IPosRewardDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p posRewardDo) Where(conds ...gen.Condition) IPosRewardDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p posRewardDo) Order(conds ...field.Expr) IPosRewardDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p posRewardDo) Distinct(cols ...field.Expr) IPosRewardDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p posRewardDo) Omit(cols ...field.Expr) IPosRewardDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p posRewardDo) Join(table schema.Tabler, on ...field.Expr) IPosRewardDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p posRewardDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPosRewardDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p posRewardDo) RightJoin(table schema.Tabler, on ...field.Expr) IPosRewardDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p posRewardDo) Group(cols ...field.Expr) IPosRewardDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p posRewardDo) Having(conds ...gen.Condition) IPosRewardDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p posRewardDo) Limit(limit int) IPosRewardDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p posRewardDo) Offset(offset int) IPosRewardDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p posRewardDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPosRewardDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p posRewardDo) Unscoped() IPosRewardDo {
	return p.withDO(p.DO.Unscoped())
}

func (p posRewardDo) Create(values ...*model.PosReward) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p posRewardDo) CreateInBatches(values []*model.PosReward, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p posRewardDo) Save(values ...*model.PosReward) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p posRewardDo) First() (*model.PosReward, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PosReward), nil
	}
}

func (p posRewardDo) Take() (*model.PosReward, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PosReward), nil
	}
}

func (p posRewardDo) Last() (*model.PosReward, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PosReward), nil
	}
}

func (p posRewardDo) Find() ([]*model.PosReward, error) {
	result, err := p.DO.Find()
	return result.([]*model.PosReward), err
}

func (p posRewardDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PosReward, err error) {
	buf := make([]*model.PosReward, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p posRewardDo) FindInBatches(result *[]*model.PosReward, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p posRewardDo) Attrs(attrs ...field.AssignExpr) IPosRewardDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p posRewardDo) Assign(attrs ...field.AssignExpr) IPosRewardDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p posRewardDo) Joins(fields ...field.RelationField) IPosRewardDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p posRewardDo) Preload(fields ...field.RelationField) IPosRewardDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p posRewardDo) FirstOrInit() (*model.PosReward, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PosReward), nil
	}
}

func (p posRewardDo) FirstOrCreate() (*model.PosReward, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PosReward), nil
	}
}

func (p posRewardDo) FindByPage(offset int, limit int) (result []*model.PosReward, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p posRewardDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p posRewardDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p posRewardDo) Delete(models ...*model.PosReward) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *posRewardDo) withDO(do gen.Dao) *posRewardDo {
	p.DO = *do.(*gen.DO)
	return p
}
