// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"oshit-go/common/pkg/dal/model"
)

func newPosRpcConfig(db *gorm.DB, opts ...gen.DOOption) posRpcConfig {
	_posRpcConfig := posRpcConfig{}

	_posRpcConfig.posRpcConfigDo.UseDB(db, opts...)
	_posRpcConfig.posRpcConfigDo.UseModel(&model.PosRpcConfig{})

	tableName := _posRpcConfig.posRpcConfigDo.TableName()
	_posRpcConfig.ALL = field.NewAsterisk(tableName)
	_posRpcConfig.RecordID = field.NewString(tableName, "record_id")
	_posRpcConfig.RPCURL = field.NewString(tableName, "rpc_url")
	_posRpcConfig.WssURL = field.NewString(tableName, "wss_url")
	_posRpcConfig.CreatedAt = field.NewTime(tableName, "created_at")
	_posRpcConfig.UpdatedAt = field.NewTime(tableName, "updated_at")

	_posRpcConfig.fillFieldMap()

	return _posRpcConfig
}

type posRpcConfig struct {
	posRpcConfigDo posRpcConfigDo

	ALL       field.Asterisk
	RecordID  field.String
	RPCURL    field.String
	WssURL    field.String
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (p posRpcConfig) Table(newTableName string) *posRpcConfig {
	p.posRpcConfigDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p posRpcConfig) As(alias string) *posRpcConfig {
	p.posRpcConfigDo.DO = *(p.posRpcConfigDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *posRpcConfig) updateTableName(table string) *posRpcConfig {
	p.ALL = field.NewAsterisk(table)
	p.RecordID = field.NewString(table, "record_id")
	p.RPCURL = field.NewString(table, "rpc_url")
	p.WssURL = field.NewString(table, "wss_url")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")

	p.fillFieldMap()

	return p
}

func (p *posRpcConfig) WithContext(ctx context.Context) IPosRpcConfigDo {
	return p.posRpcConfigDo.WithContext(ctx)
}

func (p posRpcConfig) TableName() string { return p.posRpcConfigDo.TableName() }

func (p posRpcConfig) Alias() string { return p.posRpcConfigDo.Alias() }

func (p posRpcConfig) Columns(cols ...field.Expr) gen.Columns {
	return p.posRpcConfigDo.Columns(cols...)
}

func (p *posRpcConfig) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *posRpcConfig) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 5)
	p.fieldMap["record_id"] = p.RecordID
	p.fieldMap["rpc_url"] = p.RPCURL
	p.fieldMap["wss_url"] = p.WssURL
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
}

func (p posRpcConfig) clone(db *gorm.DB) posRpcConfig {
	p.posRpcConfigDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p posRpcConfig) replaceDB(db *gorm.DB) posRpcConfig {
	p.posRpcConfigDo.ReplaceDB(db)
	return p
}

type posRpcConfigDo struct{ gen.DO }

type IPosRpcConfigDo interface {
	gen.SubQuery
	Debug() IPosRpcConfigDo
	WithContext(ctx context.Context) IPosRpcConfigDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPosRpcConfigDo
	WriteDB() IPosRpcConfigDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPosRpcConfigDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPosRpcConfigDo
	Not(conds ...gen.Condition) IPosRpcConfigDo
	Or(conds ...gen.Condition) IPosRpcConfigDo
	Select(conds ...field.Expr) IPosRpcConfigDo
	Where(conds ...gen.Condition) IPosRpcConfigDo
	Order(conds ...field.Expr) IPosRpcConfigDo
	Distinct(cols ...field.Expr) IPosRpcConfigDo
	Omit(cols ...field.Expr) IPosRpcConfigDo
	Join(table schema.Tabler, on ...field.Expr) IPosRpcConfigDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPosRpcConfigDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPosRpcConfigDo
	Group(cols ...field.Expr) IPosRpcConfigDo
	Having(conds ...gen.Condition) IPosRpcConfigDo
	Limit(limit int) IPosRpcConfigDo
	Offset(offset int) IPosRpcConfigDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPosRpcConfigDo
	Unscoped() IPosRpcConfigDo
	Create(values ...*model.PosRpcConfig) error
	CreateInBatches(values []*model.PosRpcConfig, batchSize int) error
	Save(values ...*model.PosRpcConfig) error
	First() (*model.PosRpcConfig, error)
	Take() (*model.PosRpcConfig, error)
	Last() (*model.PosRpcConfig, error)
	Find() ([]*model.PosRpcConfig, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PosRpcConfig, err error)
	FindInBatches(result *[]*model.PosRpcConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PosRpcConfig) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPosRpcConfigDo
	Assign(attrs ...field.AssignExpr) IPosRpcConfigDo
	Joins(fields ...field.RelationField) IPosRpcConfigDo
	Preload(fields ...field.RelationField) IPosRpcConfigDo
	FirstOrInit() (*model.PosRpcConfig, error)
	FirstOrCreate() (*model.PosRpcConfig, error)
	FindByPage(offset int, limit int) (result []*model.PosRpcConfig, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPosRpcConfigDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p posRpcConfigDo) Debug() IPosRpcConfigDo {
	return p.withDO(p.DO.Debug())
}

func (p posRpcConfigDo) WithContext(ctx context.Context) IPosRpcConfigDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p posRpcConfigDo) ReadDB() IPosRpcConfigDo {
	return p.Clauses(dbresolver.Read)
}

func (p posRpcConfigDo) WriteDB() IPosRpcConfigDo {
	return p.Clauses(dbresolver.Write)
}

func (p posRpcConfigDo) Session(config *gorm.Session) IPosRpcConfigDo {
	return p.withDO(p.DO.Session(config))
}

func (p posRpcConfigDo) Clauses(conds ...clause.Expression) IPosRpcConfigDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p posRpcConfigDo) Returning(value interface{}, columns ...string) IPosRpcConfigDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p posRpcConfigDo) Not(conds ...gen.Condition) IPosRpcConfigDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p posRpcConfigDo) Or(conds ...gen.Condition) IPosRpcConfigDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p posRpcConfigDo) Select(conds ...field.Expr) IPosRpcConfigDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p posRpcConfigDo) Where(conds ...gen.Condition) IPosRpcConfigDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p posRpcConfigDo) Order(conds ...field.Expr) IPosRpcConfigDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p posRpcConfigDo) Distinct(cols ...field.Expr) IPosRpcConfigDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p posRpcConfigDo) Omit(cols ...field.Expr) IPosRpcConfigDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p posRpcConfigDo) Join(table schema.Tabler, on ...field.Expr) IPosRpcConfigDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p posRpcConfigDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPosRpcConfigDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p posRpcConfigDo) RightJoin(table schema.Tabler, on ...field.Expr) IPosRpcConfigDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p posRpcConfigDo) Group(cols ...field.Expr) IPosRpcConfigDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p posRpcConfigDo) Having(conds ...gen.Condition) IPosRpcConfigDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p posRpcConfigDo) Limit(limit int) IPosRpcConfigDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p posRpcConfigDo) Offset(offset int) IPosRpcConfigDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p posRpcConfigDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPosRpcConfigDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p posRpcConfigDo) Unscoped() IPosRpcConfigDo {
	return p.withDO(p.DO.Unscoped())
}

func (p posRpcConfigDo) Create(values ...*model.PosRpcConfig) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p posRpcConfigDo) CreateInBatches(values []*model.PosRpcConfig, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p posRpcConfigDo) Save(values ...*model.PosRpcConfig) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p posRpcConfigDo) First() (*model.PosRpcConfig, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PosRpcConfig), nil
	}
}

func (p posRpcConfigDo) Take() (*model.PosRpcConfig, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PosRpcConfig), nil
	}
}

func (p posRpcConfigDo) Last() (*model.PosRpcConfig, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PosRpcConfig), nil
	}
}

func (p posRpcConfigDo) Find() ([]*model.PosRpcConfig, error) {
	result, err := p.DO.Find()
	return result.([]*model.PosRpcConfig), err
}

func (p posRpcConfigDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PosRpcConfig, err error) {
	buf := make([]*model.PosRpcConfig, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p posRpcConfigDo) FindInBatches(result *[]*model.PosRpcConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p posRpcConfigDo) Attrs(attrs ...field.AssignExpr) IPosRpcConfigDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p posRpcConfigDo) Assign(attrs ...field.AssignExpr) IPosRpcConfigDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p posRpcConfigDo) Joins(fields ...field.RelationField) IPosRpcConfigDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p posRpcConfigDo) Preload(fields ...field.RelationField) IPosRpcConfigDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p posRpcConfigDo) FirstOrInit() (*model.PosRpcConfig, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PosRpcConfig), nil
	}
}

func (p posRpcConfigDo) FirstOrCreate() (*model.PosRpcConfig, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PosRpcConfig), nil
	}
}

func (p posRpcConfigDo) FindByPage(offset int, limit int) (result []*model.PosRpcConfig, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p posRpcConfigDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p posRpcConfigDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p posRpcConfigDo) Delete(models ...*model.PosRpcConfig) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *posRpcConfigDo) withDO(do gen.Dao) *posRpcConfigDo {
	p.DO = *do.(*gen.DO)
	return p
}
