// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"oshit-go/common/pkg/dal/model"
)

func newRewardCodeConfig(db *gorm.DB, opts ...gen.DOOption) rewardCodeConfig {
	_rewardCodeConfig := rewardCodeConfig{}

	_rewardCodeConfig.rewardCodeConfigDo.UseDB(db, opts...)
	_rewardCodeConfig.rewardCodeConfigDo.UseModel(&model.RewardCodeConfig{})

	tableName := _rewardCodeConfig.rewardCodeConfigDo.TableName()
	_rewardCodeConfig.ALL = field.NewAsterisk(tableName)
	_rewardCodeConfig.RecordID = field.NewString(tableName, "record_id")
	_rewardCodeConfig.RewardAccount = field.NewString(tableName, "reward_account")
	_rewardCodeConfig.CostAccount = field.NewString(tableName, "cost_account")
	_rewardCodeConfig.CreatedAt = field.NewTime(tableName, "created_at")
	_rewardCodeConfig.UpdatedAt = field.NewTime(tableName, "updated_at")

	_rewardCodeConfig.fillFieldMap()

	return _rewardCodeConfig
}

type rewardCodeConfig struct {
	rewardCodeConfigDo rewardCodeConfigDo

	ALL           field.Asterisk
	RecordID      field.String
	RewardAccount field.String
	CostAccount   field.String
	CreatedAt     field.Time
	UpdatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (r rewardCodeConfig) Table(newTableName string) *rewardCodeConfig {
	r.rewardCodeConfigDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r rewardCodeConfig) As(alias string) *rewardCodeConfig {
	r.rewardCodeConfigDo.DO = *(r.rewardCodeConfigDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *rewardCodeConfig) updateTableName(table string) *rewardCodeConfig {
	r.ALL = field.NewAsterisk(table)
	r.RecordID = field.NewString(table, "record_id")
	r.RewardAccount = field.NewString(table, "reward_account")
	r.CostAccount = field.NewString(table, "cost_account")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")

	r.fillFieldMap()

	return r
}

func (r *rewardCodeConfig) WithContext(ctx context.Context) IRewardCodeConfigDo {
	return r.rewardCodeConfigDo.WithContext(ctx)
}

func (r rewardCodeConfig) TableName() string { return r.rewardCodeConfigDo.TableName() }

func (r rewardCodeConfig) Alias() string { return r.rewardCodeConfigDo.Alias() }

func (r rewardCodeConfig) Columns(cols ...field.Expr) gen.Columns {
	return r.rewardCodeConfigDo.Columns(cols...)
}

func (r *rewardCodeConfig) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *rewardCodeConfig) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 5)
	r.fieldMap["record_id"] = r.RecordID
	r.fieldMap["reward_account"] = r.RewardAccount
	r.fieldMap["cost_account"] = r.CostAccount
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
}

func (r rewardCodeConfig) clone(db *gorm.DB) rewardCodeConfig {
	r.rewardCodeConfigDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r rewardCodeConfig) replaceDB(db *gorm.DB) rewardCodeConfig {
	r.rewardCodeConfigDo.ReplaceDB(db)
	return r
}

type rewardCodeConfigDo struct{ gen.DO }

type IRewardCodeConfigDo interface {
	gen.SubQuery
	Debug() IRewardCodeConfigDo
	WithContext(ctx context.Context) IRewardCodeConfigDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRewardCodeConfigDo
	WriteDB() IRewardCodeConfigDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRewardCodeConfigDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRewardCodeConfigDo
	Not(conds ...gen.Condition) IRewardCodeConfigDo
	Or(conds ...gen.Condition) IRewardCodeConfigDo
	Select(conds ...field.Expr) IRewardCodeConfigDo
	Where(conds ...gen.Condition) IRewardCodeConfigDo
	Order(conds ...field.Expr) IRewardCodeConfigDo
	Distinct(cols ...field.Expr) IRewardCodeConfigDo
	Omit(cols ...field.Expr) IRewardCodeConfigDo
	Join(table schema.Tabler, on ...field.Expr) IRewardCodeConfigDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRewardCodeConfigDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRewardCodeConfigDo
	Group(cols ...field.Expr) IRewardCodeConfigDo
	Having(conds ...gen.Condition) IRewardCodeConfigDo
	Limit(limit int) IRewardCodeConfigDo
	Offset(offset int) IRewardCodeConfigDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRewardCodeConfigDo
	Unscoped() IRewardCodeConfigDo
	Create(values ...*model.RewardCodeConfig) error
	CreateInBatches(values []*model.RewardCodeConfig, batchSize int) error
	Save(values ...*model.RewardCodeConfig) error
	First() (*model.RewardCodeConfig, error)
	Take() (*model.RewardCodeConfig, error)
	Last() (*model.RewardCodeConfig, error)
	Find() ([]*model.RewardCodeConfig, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RewardCodeConfig, err error)
	FindInBatches(result *[]*model.RewardCodeConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RewardCodeConfig) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRewardCodeConfigDo
	Assign(attrs ...field.AssignExpr) IRewardCodeConfigDo
	Joins(fields ...field.RelationField) IRewardCodeConfigDo
	Preload(fields ...field.RelationField) IRewardCodeConfigDo
	FirstOrInit() (*model.RewardCodeConfig, error)
	FirstOrCreate() (*model.RewardCodeConfig, error)
	FindByPage(offset int, limit int) (result []*model.RewardCodeConfig, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRewardCodeConfigDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r rewardCodeConfigDo) Debug() IRewardCodeConfigDo {
	return r.withDO(r.DO.Debug())
}

func (r rewardCodeConfigDo) WithContext(ctx context.Context) IRewardCodeConfigDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r rewardCodeConfigDo) ReadDB() IRewardCodeConfigDo {
	return r.Clauses(dbresolver.Read)
}

func (r rewardCodeConfigDo) WriteDB() IRewardCodeConfigDo {
	return r.Clauses(dbresolver.Write)
}

func (r rewardCodeConfigDo) Session(config *gorm.Session) IRewardCodeConfigDo {
	return r.withDO(r.DO.Session(config))
}

func (r rewardCodeConfigDo) Clauses(conds ...clause.Expression) IRewardCodeConfigDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r rewardCodeConfigDo) Returning(value interface{}, columns ...string) IRewardCodeConfigDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r rewardCodeConfigDo) Not(conds ...gen.Condition) IRewardCodeConfigDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r rewardCodeConfigDo) Or(conds ...gen.Condition) IRewardCodeConfigDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r rewardCodeConfigDo) Select(conds ...field.Expr) IRewardCodeConfigDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r rewardCodeConfigDo) Where(conds ...gen.Condition) IRewardCodeConfigDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r rewardCodeConfigDo) Order(conds ...field.Expr) IRewardCodeConfigDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r rewardCodeConfigDo) Distinct(cols ...field.Expr) IRewardCodeConfigDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r rewardCodeConfigDo) Omit(cols ...field.Expr) IRewardCodeConfigDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r rewardCodeConfigDo) Join(table schema.Tabler, on ...field.Expr) IRewardCodeConfigDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r rewardCodeConfigDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRewardCodeConfigDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r rewardCodeConfigDo) RightJoin(table schema.Tabler, on ...field.Expr) IRewardCodeConfigDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r rewardCodeConfigDo) Group(cols ...field.Expr) IRewardCodeConfigDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r rewardCodeConfigDo) Having(conds ...gen.Condition) IRewardCodeConfigDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r rewardCodeConfigDo) Limit(limit int) IRewardCodeConfigDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r rewardCodeConfigDo) Offset(offset int) IRewardCodeConfigDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r rewardCodeConfigDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRewardCodeConfigDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r rewardCodeConfigDo) Unscoped() IRewardCodeConfigDo {
	return r.withDO(r.DO.Unscoped())
}

func (r rewardCodeConfigDo) Create(values ...*model.RewardCodeConfig) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r rewardCodeConfigDo) CreateInBatches(values []*model.RewardCodeConfig, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r rewardCodeConfigDo) Save(values ...*model.RewardCodeConfig) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r rewardCodeConfigDo) First() (*model.RewardCodeConfig, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RewardCodeConfig), nil
	}
}

func (r rewardCodeConfigDo) Take() (*model.RewardCodeConfig, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RewardCodeConfig), nil
	}
}

func (r rewardCodeConfigDo) Last() (*model.RewardCodeConfig, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RewardCodeConfig), nil
	}
}

func (r rewardCodeConfigDo) Find() ([]*model.RewardCodeConfig, error) {
	result, err := r.DO.Find()
	return result.([]*model.RewardCodeConfig), err
}

func (r rewardCodeConfigDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RewardCodeConfig, err error) {
	buf := make([]*model.RewardCodeConfig, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r rewardCodeConfigDo) FindInBatches(result *[]*model.RewardCodeConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r rewardCodeConfigDo) Attrs(attrs ...field.AssignExpr) IRewardCodeConfigDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r rewardCodeConfigDo) Assign(attrs ...field.AssignExpr) IRewardCodeConfigDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r rewardCodeConfigDo) Joins(fields ...field.RelationField) IRewardCodeConfigDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r rewardCodeConfigDo) Preload(fields ...field.RelationField) IRewardCodeConfigDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r rewardCodeConfigDo) FirstOrInit() (*model.RewardCodeConfig, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RewardCodeConfig), nil
	}
}

func (r rewardCodeConfigDo) FirstOrCreate() (*model.RewardCodeConfig, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RewardCodeConfig), nil
	}
}

func (r rewardCodeConfigDo) FindByPage(offset int, limit int) (result []*model.RewardCodeConfig, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r rewardCodeConfigDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r rewardCodeConfigDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r rewardCodeConfigDo) Delete(models ...*model.RewardCodeConfig) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *rewardCodeConfigDo) withDO(do gen.Dao) *rewardCodeConfigDo {
	r.DO = *do.(*gen.DO)
	return r
}
