// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"oshit-go/common/pkg/dal/model"
)

func newRewardKeyConfig(db *gorm.DB, opts ...gen.DOOption) rewardKeyConfig {
	_rewardKeyConfig := rewardKeyConfig{}

	_rewardKeyConfig.rewardKeyConfigDo.UseDB(db, opts...)
	_rewardKeyConfig.rewardKeyConfigDo.UseModel(&model.RewardKeyConfig{})

	tableName := _rewardKeyConfig.rewardKeyConfigDo.TableName()
	_rewardKeyConfig.ALL = field.NewAsterisk(tableName)
	_rewardKeyConfig.Service = field.NewString(tableName, "service")
	_rewardKeyConfig.EncryptedKey = field.NewString(tableName, "encrypted_key")
	_rewardKeyConfig.CreatedAt = field.NewTime(tableName, "created_at")
	_rewardKeyConfig.UpdatedAt = field.NewTime(tableName, "updated_at")

	_rewardKeyConfig.fillFieldMap()

	return _rewardKeyConfig
}

type rewardKeyConfig struct {
	rewardKeyConfigDo rewardKeyConfigDo

	ALL          field.Asterisk
	Service      field.String
	EncryptedKey field.String
	CreatedAt    field.Time
	UpdatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (r rewardKeyConfig) Table(newTableName string) *rewardKeyConfig {
	r.rewardKeyConfigDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r rewardKeyConfig) As(alias string) *rewardKeyConfig {
	r.rewardKeyConfigDo.DO = *(r.rewardKeyConfigDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *rewardKeyConfig) updateTableName(table string) *rewardKeyConfig {
	r.ALL = field.NewAsterisk(table)
	r.Service = field.NewString(table, "service")
	r.EncryptedKey = field.NewString(table, "encrypted_key")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")

	r.fillFieldMap()

	return r
}

func (r *rewardKeyConfig) WithContext(ctx context.Context) IRewardKeyConfigDo {
	return r.rewardKeyConfigDo.WithContext(ctx)
}

func (r rewardKeyConfig) TableName() string { return r.rewardKeyConfigDo.TableName() }

func (r rewardKeyConfig) Alias() string { return r.rewardKeyConfigDo.Alias() }

func (r rewardKeyConfig) Columns(cols ...field.Expr) gen.Columns {
	return r.rewardKeyConfigDo.Columns(cols...)
}

func (r *rewardKeyConfig) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *rewardKeyConfig) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 4)
	r.fieldMap["service"] = r.Service
	r.fieldMap["encrypted_key"] = r.EncryptedKey
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
}

func (r rewardKeyConfig) clone(db *gorm.DB) rewardKeyConfig {
	r.rewardKeyConfigDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r rewardKeyConfig) replaceDB(db *gorm.DB) rewardKeyConfig {
	r.rewardKeyConfigDo.ReplaceDB(db)
	return r
}

type rewardKeyConfigDo struct{ gen.DO }

type IRewardKeyConfigDo interface {
	gen.SubQuery
	Debug() IRewardKeyConfigDo
	WithContext(ctx context.Context) IRewardKeyConfigDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRewardKeyConfigDo
	WriteDB() IRewardKeyConfigDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRewardKeyConfigDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRewardKeyConfigDo
	Not(conds ...gen.Condition) IRewardKeyConfigDo
	Or(conds ...gen.Condition) IRewardKeyConfigDo
	Select(conds ...field.Expr) IRewardKeyConfigDo
	Where(conds ...gen.Condition) IRewardKeyConfigDo
	Order(conds ...field.Expr) IRewardKeyConfigDo
	Distinct(cols ...field.Expr) IRewardKeyConfigDo
	Omit(cols ...field.Expr) IRewardKeyConfigDo
	Join(table schema.Tabler, on ...field.Expr) IRewardKeyConfigDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRewardKeyConfigDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRewardKeyConfigDo
	Group(cols ...field.Expr) IRewardKeyConfigDo
	Having(conds ...gen.Condition) IRewardKeyConfigDo
	Limit(limit int) IRewardKeyConfigDo
	Offset(offset int) IRewardKeyConfigDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRewardKeyConfigDo
	Unscoped() IRewardKeyConfigDo
	Create(values ...*model.RewardKeyConfig) error
	CreateInBatches(values []*model.RewardKeyConfig, batchSize int) error
	Save(values ...*model.RewardKeyConfig) error
	First() (*model.RewardKeyConfig, error)
	Take() (*model.RewardKeyConfig, error)
	Last() (*model.RewardKeyConfig, error)
	Find() ([]*model.RewardKeyConfig, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RewardKeyConfig, err error)
	FindInBatches(result *[]*model.RewardKeyConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RewardKeyConfig) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRewardKeyConfigDo
	Assign(attrs ...field.AssignExpr) IRewardKeyConfigDo
	Joins(fields ...field.RelationField) IRewardKeyConfigDo
	Preload(fields ...field.RelationField) IRewardKeyConfigDo
	FirstOrInit() (*model.RewardKeyConfig, error)
	FirstOrCreate() (*model.RewardKeyConfig, error)
	FindByPage(offset int, limit int) (result []*model.RewardKeyConfig, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRewardKeyConfigDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r rewardKeyConfigDo) Debug() IRewardKeyConfigDo {
	return r.withDO(r.DO.Debug())
}

func (r rewardKeyConfigDo) WithContext(ctx context.Context) IRewardKeyConfigDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r rewardKeyConfigDo) ReadDB() IRewardKeyConfigDo {
	return r.Clauses(dbresolver.Read)
}

func (r rewardKeyConfigDo) WriteDB() IRewardKeyConfigDo {
	return r.Clauses(dbresolver.Write)
}

func (r rewardKeyConfigDo) Session(config *gorm.Session) IRewardKeyConfigDo {
	return r.withDO(r.DO.Session(config))
}

func (r rewardKeyConfigDo) Clauses(conds ...clause.Expression) IRewardKeyConfigDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r rewardKeyConfigDo) Returning(value interface{}, columns ...string) IRewardKeyConfigDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r rewardKeyConfigDo) Not(conds ...gen.Condition) IRewardKeyConfigDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r rewardKeyConfigDo) Or(conds ...gen.Condition) IRewardKeyConfigDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r rewardKeyConfigDo) Select(conds ...field.Expr) IRewardKeyConfigDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r rewardKeyConfigDo) Where(conds ...gen.Condition) IRewardKeyConfigDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r rewardKeyConfigDo) Order(conds ...field.Expr) IRewardKeyConfigDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r rewardKeyConfigDo) Distinct(cols ...field.Expr) IRewardKeyConfigDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r rewardKeyConfigDo) Omit(cols ...field.Expr) IRewardKeyConfigDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r rewardKeyConfigDo) Join(table schema.Tabler, on ...field.Expr) IRewardKeyConfigDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r rewardKeyConfigDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRewardKeyConfigDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r rewardKeyConfigDo) RightJoin(table schema.Tabler, on ...field.Expr) IRewardKeyConfigDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r rewardKeyConfigDo) Group(cols ...field.Expr) IRewardKeyConfigDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r rewardKeyConfigDo) Having(conds ...gen.Condition) IRewardKeyConfigDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r rewardKeyConfigDo) Limit(limit int) IRewardKeyConfigDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r rewardKeyConfigDo) Offset(offset int) IRewardKeyConfigDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r rewardKeyConfigDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRewardKeyConfigDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r rewardKeyConfigDo) Unscoped() IRewardKeyConfigDo {
	return r.withDO(r.DO.Unscoped())
}

func (r rewardKeyConfigDo) Create(values ...*model.RewardKeyConfig) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r rewardKeyConfigDo) CreateInBatches(values []*model.RewardKeyConfig, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r rewardKeyConfigDo) Save(values ...*model.RewardKeyConfig) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r rewardKeyConfigDo) First() (*model.RewardKeyConfig, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RewardKeyConfig), nil
	}
}

func (r rewardKeyConfigDo) Take() (*model.RewardKeyConfig, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RewardKeyConfig), nil
	}
}

func (r rewardKeyConfigDo) Last() (*model.RewardKeyConfig, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RewardKeyConfig), nil
	}
}

func (r rewardKeyConfigDo) Find() ([]*model.RewardKeyConfig, error) {
	result, err := r.DO.Find()
	return result.([]*model.RewardKeyConfig), err
}

func (r rewardKeyConfigDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RewardKeyConfig, err error) {
	buf := make([]*model.RewardKeyConfig, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r rewardKeyConfigDo) FindInBatches(result *[]*model.RewardKeyConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r rewardKeyConfigDo) Attrs(attrs ...field.AssignExpr) IRewardKeyConfigDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r rewardKeyConfigDo) Assign(attrs ...field.AssignExpr) IRewardKeyConfigDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r rewardKeyConfigDo) Joins(fields ...field.RelationField) IRewardKeyConfigDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r rewardKeyConfigDo) Preload(fields ...field.RelationField) IRewardKeyConfigDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r rewardKeyConfigDo) FirstOrInit() (*model.RewardKeyConfig, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RewardKeyConfig), nil
	}
}

func (r rewardKeyConfigDo) FirstOrCreate() (*model.RewardKeyConfig, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RewardKeyConfig), nil
	}
}

func (r rewardKeyConfigDo) FindByPage(offset int, limit int) (result []*model.RewardKeyConfig, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r rewardKeyConfigDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r rewardKeyConfigDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r rewardKeyConfigDo) Delete(models ...*model.RewardKeyConfig) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *rewardKeyConfigDo) withDO(do gen.Dao) *rewardKeyConfigDo {
	r.DO = *do.(*gen.DO)
	return r
}
