// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"oshit-go/common/pkg/dal/model"
)

func newStakeBuyTokenDefault(db *gorm.DB, opts ...gen.DOOption) stakeBuyTokenDefault {
	_stakeBuyTokenDefault := stakeBuyTokenDefault{}

	_stakeBuyTokenDefault.stakeBuyTokenDefaultDo.UseDB(db, opts...)
	_stakeBuyTokenDefault.stakeBuyTokenDefaultDo.UseModel(&model.StakeBuyTokenDefault{})

	tableName := _stakeBuyTokenDefault.stakeBuyTokenDefaultDo.TableName()
	_stakeBuyTokenDefault.ALL = field.NewAsterisk(tableName)
	_stakeBuyTokenDefault.TxID = field.NewString(tableName, "tx_id")
	_stakeBuyTokenDefault.Slot = field.NewFloat64(tableName, "slot")
	_stakeBuyTokenDefault.FromAccount = field.NewString(tableName, "from_account")
	_stakeBuyTokenDefault.ToAccount = field.NewString(tableName, "to_account")
	_stakeBuyTokenDefault.Amount = field.NewFloat64(tableName, "amount")
	_stakeBuyTokenDefault.Locked = field.NewBool(tableName, "locked")
	_stakeBuyTokenDefault.LockedBy = field.NewString(tableName, "locked_by")
	_stakeBuyTokenDefault.LockedAt = field.NewTime(tableName, "locked_at")
	_stakeBuyTokenDefault.StakedAmount = field.NewFloat64(tableName, "staked_amount")
	_stakeBuyTokenDefault.RemainingAmount = field.NewFloat64(tableName, "remaining_amount")
	_stakeBuyTokenDefault.Expired = field.NewBool(tableName, "expired")
	_stakeBuyTokenDefault.CreatedAt = field.NewTime(tableName, "created_at")
	_stakeBuyTokenDefault.ExpiredAt = field.NewTime(tableName, "expired_at")

	_stakeBuyTokenDefault.fillFieldMap()

	return _stakeBuyTokenDefault
}

type stakeBuyTokenDefault struct {
	stakeBuyTokenDefaultDo stakeBuyTokenDefaultDo

	ALL             field.Asterisk
	TxID            field.String
	Slot            field.Float64
	FromAccount     field.String
	ToAccount       field.String
	Amount          field.Float64
	Locked          field.Bool
	LockedBy        field.String
	LockedAt        field.Time
	StakedAmount    field.Float64
	RemainingAmount field.Float64
	Expired         field.Bool
	CreatedAt       field.Time
	ExpiredAt       field.Time

	fieldMap map[string]field.Expr
}

func (s stakeBuyTokenDefault) Table(newTableName string) *stakeBuyTokenDefault {
	s.stakeBuyTokenDefaultDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s stakeBuyTokenDefault) As(alias string) *stakeBuyTokenDefault {
	s.stakeBuyTokenDefaultDo.DO = *(s.stakeBuyTokenDefaultDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *stakeBuyTokenDefault) updateTableName(table string) *stakeBuyTokenDefault {
	s.ALL = field.NewAsterisk(table)
	s.TxID = field.NewString(table, "tx_id")
	s.Slot = field.NewFloat64(table, "slot")
	s.FromAccount = field.NewString(table, "from_account")
	s.ToAccount = field.NewString(table, "to_account")
	s.Amount = field.NewFloat64(table, "amount")
	s.Locked = field.NewBool(table, "locked")
	s.LockedBy = field.NewString(table, "locked_by")
	s.LockedAt = field.NewTime(table, "locked_at")
	s.StakedAmount = field.NewFloat64(table, "staked_amount")
	s.RemainingAmount = field.NewFloat64(table, "remaining_amount")
	s.Expired = field.NewBool(table, "expired")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.ExpiredAt = field.NewTime(table, "expired_at")

	s.fillFieldMap()

	return s
}

func (s *stakeBuyTokenDefault) WithContext(ctx context.Context) IStakeBuyTokenDefaultDo {
	return s.stakeBuyTokenDefaultDo.WithContext(ctx)
}

func (s stakeBuyTokenDefault) TableName() string { return s.stakeBuyTokenDefaultDo.TableName() }

func (s stakeBuyTokenDefault) Alias() string { return s.stakeBuyTokenDefaultDo.Alias() }

func (s stakeBuyTokenDefault) Columns(cols ...field.Expr) gen.Columns {
	return s.stakeBuyTokenDefaultDo.Columns(cols...)
}

func (s *stakeBuyTokenDefault) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *stakeBuyTokenDefault) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 13)
	s.fieldMap["tx_id"] = s.TxID
	s.fieldMap["slot"] = s.Slot
	s.fieldMap["from_account"] = s.FromAccount
	s.fieldMap["to_account"] = s.ToAccount
	s.fieldMap["amount"] = s.Amount
	s.fieldMap["locked"] = s.Locked
	s.fieldMap["locked_by"] = s.LockedBy
	s.fieldMap["locked_at"] = s.LockedAt
	s.fieldMap["staked_amount"] = s.StakedAmount
	s.fieldMap["remaining_amount"] = s.RemainingAmount
	s.fieldMap["expired"] = s.Expired
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["expired_at"] = s.ExpiredAt
}

func (s stakeBuyTokenDefault) clone(db *gorm.DB) stakeBuyTokenDefault {
	s.stakeBuyTokenDefaultDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s stakeBuyTokenDefault) replaceDB(db *gorm.DB) stakeBuyTokenDefault {
	s.stakeBuyTokenDefaultDo.ReplaceDB(db)
	return s
}

type stakeBuyTokenDefaultDo struct{ gen.DO }

type IStakeBuyTokenDefaultDo interface {
	gen.SubQuery
	Debug() IStakeBuyTokenDefaultDo
	WithContext(ctx context.Context) IStakeBuyTokenDefaultDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IStakeBuyTokenDefaultDo
	WriteDB() IStakeBuyTokenDefaultDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IStakeBuyTokenDefaultDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IStakeBuyTokenDefaultDo
	Not(conds ...gen.Condition) IStakeBuyTokenDefaultDo
	Or(conds ...gen.Condition) IStakeBuyTokenDefaultDo
	Select(conds ...field.Expr) IStakeBuyTokenDefaultDo
	Where(conds ...gen.Condition) IStakeBuyTokenDefaultDo
	Order(conds ...field.Expr) IStakeBuyTokenDefaultDo
	Distinct(cols ...field.Expr) IStakeBuyTokenDefaultDo
	Omit(cols ...field.Expr) IStakeBuyTokenDefaultDo
	Join(table schema.Tabler, on ...field.Expr) IStakeBuyTokenDefaultDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IStakeBuyTokenDefaultDo
	RightJoin(table schema.Tabler, on ...field.Expr) IStakeBuyTokenDefaultDo
	Group(cols ...field.Expr) IStakeBuyTokenDefaultDo
	Having(conds ...gen.Condition) IStakeBuyTokenDefaultDo
	Limit(limit int) IStakeBuyTokenDefaultDo
	Offset(offset int) IStakeBuyTokenDefaultDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IStakeBuyTokenDefaultDo
	Unscoped() IStakeBuyTokenDefaultDo
	Create(values ...*model.StakeBuyTokenDefault) error
	CreateInBatches(values []*model.StakeBuyTokenDefault, batchSize int) error
	Save(values ...*model.StakeBuyTokenDefault) error
	First() (*model.StakeBuyTokenDefault, error)
	Take() (*model.StakeBuyTokenDefault, error)
	Last() (*model.StakeBuyTokenDefault, error)
	Find() ([]*model.StakeBuyTokenDefault, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.StakeBuyTokenDefault, err error)
	FindInBatches(result *[]*model.StakeBuyTokenDefault, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.StakeBuyTokenDefault) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IStakeBuyTokenDefaultDo
	Assign(attrs ...field.AssignExpr) IStakeBuyTokenDefaultDo
	Joins(fields ...field.RelationField) IStakeBuyTokenDefaultDo
	Preload(fields ...field.RelationField) IStakeBuyTokenDefaultDo
	FirstOrInit() (*model.StakeBuyTokenDefault, error)
	FirstOrCreate() (*model.StakeBuyTokenDefault, error)
	FindByPage(offset int, limit int) (result []*model.StakeBuyTokenDefault, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IStakeBuyTokenDefaultDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s stakeBuyTokenDefaultDo) Debug() IStakeBuyTokenDefaultDo {
	return s.withDO(s.DO.Debug())
}

func (s stakeBuyTokenDefaultDo) WithContext(ctx context.Context) IStakeBuyTokenDefaultDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s stakeBuyTokenDefaultDo) ReadDB() IStakeBuyTokenDefaultDo {
	return s.Clauses(dbresolver.Read)
}

func (s stakeBuyTokenDefaultDo) WriteDB() IStakeBuyTokenDefaultDo {
	return s.Clauses(dbresolver.Write)
}

func (s stakeBuyTokenDefaultDo) Session(config *gorm.Session) IStakeBuyTokenDefaultDo {
	return s.withDO(s.DO.Session(config))
}

func (s stakeBuyTokenDefaultDo) Clauses(conds ...clause.Expression) IStakeBuyTokenDefaultDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s stakeBuyTokenDefaultDo) Returning(value interface{}, columns ...string) IStakeBuyTokenDefaultDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s stakeBuyTokenDefaultDo) Not(conds ...gen.Condition) IStakeBuyTokenDefaultDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s stakeBuyTokenDefaultDo) Or(conds ...gen.Condition) IStakeBuyTokenDefaultDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s stakeBuyTokenDefaultDo) Select(conds ...field.Expr) IStakeBuyTokenDefaultDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s stakeBuyTokenDefaultDo) Where(conds ...gen.Condition) IStakeBuyTokenDefaultDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s stakeBuyTokenDefaultDo) Order(conds ...field.Expr) IStakeBuyTokenDefaultDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s stakeBuyTokenDefaultDo) Distinct(cols ...field.Expr) IStakeBuyTokenDefaultDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s stakeBuyTokenDefaultDo) Omit(cols ...field.Expr) IStakeBuyTokenDefaultDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s stakeBuyTokenDefaultDo) Join(table schema.Tabler, on ...field.Expr) IStakeBuyTokenDefaultDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s stakeBuyTokenDefaultDo) LeftJoin(table schema.Tabler, on ...field.Expr) IStakeBuyTokenDefaultDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s stakeBuyTokenDefaultDo) RightJoin(table schema.Tabler, on ...field.Expr) IStakeBuyTokenDefaultDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s stakeBuyTokenDefaultDo) Group(cols ...field.Expr) IStakeBuyTokenDefaultDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s stakeBuyTokenDefaultDo) Having(conds ...gen.Condition) IStakeBuyTokenDefaultDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s stakeBuyTokenDefaultDo) Limit(limit int) IStakeBuyTokenDefaultDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s stakeBuyTokenDefaultDo) Offset(offset int) IStakeBuyTokenDefaultDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s stakeBuyTokenDefaultDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IStakeBuyTokenDefaultDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s stakeBuyTokenDefaultDo) Unscoped() IStakeBuyTokenDefaultDo {
	return s.withDO(s.DO.Unscoped())
}

func (s stakeBuyTokenDefaultDo) Create(values ...*model.StakeBuyTokenDefault) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s stakeBuyTokenDefaultDo) CreateInBatches(values []*model.StakeBuyTokenDefault, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s stakeBuyTokenDefaultDo) Save(values ...*model.StakeBuyTokenDefault) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s stakeBuyTokenDefaultDo) First() (*model.StakeBuyTokenDefault, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.StakeBuyTokenDefault), nil
	}
}

func (s stakeBuyTokenDefaultDo) Take() (*model.StakeBuyTokenDefault, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.StakeBuyTokenDefault), nil
	}
}

func (s stakeBuyTokenDefaultDo) Last() (*model.StakeBuyTokenDefault, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.StakeBuyTokenDefault), nil
	}
}

func (s stakeBuyTokenDefaultDo) Find() ([]*model.StakeBuyTokenDefault, error) {
	result, err := s.DO.Find()
	return result.([]*model.StakeBuyTokenDefault), err
}

func (s stakeBuyTokenDefaultDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.StakeBuyTokenDefault, err error) {
	buf := make([]*model.StakeBuyTokenDefault, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s stakeBuyTokenDefaultDo) FindInBatches(result *[]*model.StakeBuyTokenDefault, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s stakeBuyTokenDefaultDo) Attrs(attrs ...field.AssignExpr) IStakeBuyTokenDefaultDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s stakeBuyTokenDefaultDo) Assign(attrs ...field.AssignExpr) IStakeBuyTokenDefaultDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s stakeBuyTokenDefaultDo) Joins(fields ...field.RelationField) IStakeBuyTokenDefaultDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s stakeBuyTokenDefaultDo) Preload(fields ...field.RelationField) IStakeBuyTokenDefaultDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s stakeBuyTokenDefaultDo) FirstOrInit() (*model.StakeBuyTokenDefault, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.StakeBuyTokenDefault), nil
	}
}

func (s stakeBuyTokenDefaultDo) FirstOrCreate() (*model.StakeBuyTokenDefault, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.StakeBuyTokenDefault), nil
	}
}

func (s stakeBuyTokenDefaultDo) FindByPage(offset int, limit int) (result []*model.StakeBuyTokenDefault, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s stakeBuyTokenDefaultDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s stakeBuyTokenDefaultDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s stakeBuyTokenDefaultDo) Delete(models ...*model.StakeBuyTokenDefault) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *stakeBuyTokenDefaultDo) withDO(do gen.Dao) *stakeBuyTokenDefaultDo {
	s.DO = *do.(*gen.DO)
	return s
}
