// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"oshit-go/common/pkg/dal/model"
)

func newStakeSnapShotDefault(db *gorm.DB, opts ...gen.DOOption) stakeSnapShotDefault {
	_stakeSnapShotDefault := stakeSnapShotDefault{}

	_stakeSnapShotDefault.stakeSnapShotDefaultDo.UseDB(db, opts...)
	_stakeSnapShotDefault.stakeSnapShotDefaultDo.UseModel(&model.StakeSnapShotDefault{})

	tableName := _stakeSnapShotDefault.stakeSnapShotDefaultDo.TableName()
	_stakeSnapShotDefault.ALL = field.NewAsterisk(tableName)
	_stakeSnapShotDefault.RecordID = field.NewString(tableName, "record_id")
	_stakeSnapShotDefault.NativeAccount = field.NewString(tableName, "native_account")
	_stakeSnapShotDefault.Amount = field.NewFloat64(tableName, "amount")
	_stakeSnapShotDefault.StakeType = field.NewInt32(tableName, "stake_type")
	_stakeSnapShotDefault.SnapDay = field.NewTime(tableName, "snap_day")
	_stakeSnapShotDefault.CreatedAt = field.NewTime(tableName, "created_at")
	_stakeSnapShotDefault.UpdatedAt = field.NewTime(tableName, "updated_at")

	_stakeSnapShotDefault.fillFieldMap()

	return _stakeSnapShotDefault
}

type stakeSnapShotDefault struct {
	stakeSnapShotDefaultDo stakeSnapShotDefaultDo

	ALL           field.Asterisk
	RecordID      field.String
	NativeAccount field.String
	Amount        field.Float64
	StakeType     field.Int32
	SnapDay       field.Time
	CreatedAt     field.Time
	UpdatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (s stakeSnapShotDefault) Table(newTableName string) *stakeSnapShotDefault {
	s.stakeSnapShotDefaultDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s stakeSnapShotDefault) As(alias string) *stakeSnapShotDefault {
	s.stakeSnapShotDefaultDo.DO = *(s.stakeSnapShotDefaultDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *stakeSnapShotDefault) updateTableName(table string) *stakeSnapShotDefault {
	s.ALL = field.NewAsterisk(table)
	s.RecordID = field.NewString(table, "record_id")
	s.NativeAccount = field.NewString(table, "native_account")
	s.Amount = field.NewFloat64(table, "amount")
	s.StakeType = field.NewInt32(table, "stake_type")
	s.SnapDay = field.NewTime(table, "snap_day")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")

	s.fillFieldMap()

	return s
}

func (s *stakeSnapShotDefault) WithContext(ctx context.Context) IStakeSnapShotDefaultDo {
	return s.stakeSnapShotDefaultDo.WithContext(ctx)
}

func (s stakeSnapShotDefault) TableName() string { return s.stakeSnapShotDefaultDo.TableName() }

func (s stakeSnapShotDefault) Alias() string { return s.stakeSnapShotDefaultDo.Alias() }

func (s stakeSnapShotDefault) Columns(cols ...field.Expr) gen.Columns {
	return s.stakeSnapShotDefaultDo.Columns(cols...)
}

func (s *stakeSnapShotDefault) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *stakeSnapShotDefault) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 7)
	s.fieldMap["record_id"] = s.RecordID
	s.fieldMap["native_account"] = s.NativeAccount
	s.fieldMap["amount"] = s.Amount
	s.fieldMap["stake_type"] = s.StakeType
	s.fieldMap["snap_day"] = s.SnapDay
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
}

func (s stakeSnapShotDefault) clone(db *gorm.DB) stakeSnapShotDefault {
	s.stakeSnapShotDefaultDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s stakeSnapShotDefault) replaceDB(db *gorm.DB) stakeSnapShotDefault {
	s.stakeSnapShotDefaultDo.ReplaceDB(db)
	return s
}

type stakeSnapShotDefaultDo struct{ gen.DO }

type IStakeSnapShotDefaultDo interface {
	gen.SubQuery
	Debug() IStakeSnapShotDefaultDo
	WithContext(ctx context.Context) IStakeSnapShotDefaultDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IStakeSnapShotDefaultDo
	WriteDB() IStakeSnapShotDefaultDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IStakeSnapShotDefaultDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IStakeSnapShotDefaultDo
	Not(conds ...gen.Condition) IStakeSnapShotDefaultDo
	Or(conds ...gen.Condition) IStakeSnapShotDefaultDo
	Select(conds ...field.Expr) IStakeSnapShotDefaultDo
	Where(conds ...gen.Condition) IStakeSnapShotDefaultDo
	Order(conds ...field.Expr) IStakeSnapShotDefaultDo
	Distinct(cols ...field.Expr) IStakeSnapShotDefaultDo
	Omit(cols ...field.Expr) IStakeSnapShotDefaultDo
	Join(table schema.Tabler, on ...field.Expr) IStakeSnapShotDefaultDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IStakeSnapShotDefaultDo
	RightJoin(table schema.Tabler, on ...field.Expr) IStakeSnapShotDefaultDo
	Group(cols ...field.Expr) IStakeSnapShotDefaultDo
	Having(conds ...gen.Condition) IStakeSnapShotDefaultDo
	Limit(limit int) IStakeSnapShotDefaultDo
	Offset(offset int) IStakeSnapShotDefaultDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IStakeSnapShotDefaultDo
	Unscoped() IStakeSnapShotDefaultDo
	Create(values ...*model.StakeSnapShotDefault) error
	CreateInBatches(values []*model.StakeSnapShotDefault, batchSize int) error
	Save(values ...*model.StakeSnapShotDefault) error
	First() (*model.StakeSnapShotDefault, error)
	Take() (*model.StakeSnapShotDefault, error)
	Last() (*model.StakeSnapShotDefault, error)
	Find() ([]*model.StakeSnapShotDefault, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.StakeSnapShotDefault, err error)
	FindInBatches(result *[]*model.StakeSnapShotDefault, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.StakeSnapShotDefault) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IStakeSnapShotDefaultDo
	Assign(attrs ...field.AssignExpr) IStakeSnapShotDefaultDo
	Joins(fields ...field.RelationField) IStakeSnapShotDefaultDo
	Preload(fields ...field.RelationField) IStakeSnapShotDefaultDo
	FirstOrInit() (*model.StakeSnapShotDefault, error)
	FirstOrCreate() (*model.StakeSnapShotDefault, error)
	FindByPage(offset int, limit int) (result []*model.StakeSnapShotDefault, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IStakeSnapShotDefaultDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s stakeSnapShotDefaultDo) Debug() IStakeSnapShotDefaultDo {
	return s.withDO(s.DO.Debug())
}

func (s stakeSnapShotDefaultDo) WithContext(ctx context.Context) IStakeSnapShotDefaultDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s stakeSnapShotDefaultDo) ReadDB() IStakeSnapShotDefaultDo {
	return s.Clauses(dbresolver.Read)
}

func (s stakeSnapShotDefaultDo) WriteDB() IStakeSnapShotDefaultDo {
	return s.Clauses(dbresolver.Write)
}

func (s stakeSnapShotDefaultDo) Session(config *gorm.Session) IStakeSnapShotDefaultDo {
	return s.withDO(s.DO.Session(config))
}

func (s stakeSnapShotDefaultDo) Clauses(conds ...clause.Expression) IStakeSnapShotDefaultDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s stakeSnapShotDefaultDo) Returning(value interface{}, columns ...string) IStakeSnapShotDefaultDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s stakeSnapShotDefaultDo) Not(conds ...gen.Condition) IStakeSnapShotDefaultDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s stakeSnapShotDefaultDo) Or(conds ...gen.Condition) IStakeSnapShotDefaultDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s stakeSnapShotDefaultDo) Select(conds ...field.Expr) IStakeSnapShotDefaultDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s stakeSnapShotDefaultDo) Where(conds ...gen.Condition) IStakeSnapShotDefaultDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s stakeSnapShotDefaultDo) Order(conds ...field.Expr) IStakeSnapShotDefaultDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s stakeSnapShotDefaultDo) Distinct(cols ...field.Expr) IStakeSnapShotDefaultDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s stakeSnapShotDefaultDo) Omit(cols ...field.Expr) IStakeSnapShotDefaultDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s stakeSnapShotDefaultDo) Join(table schema.Tabler, on ...field.Expr) IStakeSnapShotDefaultDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s stakeSnapShotDefaultDo) LeftJoin(table schema.Tabler, on ...field.Expr) IStakeSnapShotDefaultDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s stakeSnapShotDefaultDo) RightJoin(table schema.Tabler, on ...field.Expr) IStakeSnapShotDefaultDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s stakeSnapShotDefaultDo) Group(cols ...field.Expr) IStakeSnapShotDefaultDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s stakeSnapShotDefaultDo) Having(conds ...gen.Condition) IStakeSnapShotDefaultDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s stakeSnapShotDefaultDo) Limit(limit int) IStakeSnapShotDefaultDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s stakeSnapShotDefaultDo) Offset(offset int) IStakeSnapShotDefaultDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s stakeSnapShotDefaultDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IStakeSnapShotDefaultDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s stakeSnapShotDefaultDo) Unscoped() IStakeSnapShotDefaultDo {
	return s.withDO(s.DO.Unscoped())
}

func (s stakeSnapShotDefaultDo) Create(values ...*model.StakeSnapShotDefault) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s stakeSnapShotDefaultDo) CreateInBatches(values []*model.StakeSnapShotDefault, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s stakeSnapShotDefaultDo) Save(values ...*model.StakeSnapShotDefault) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s stakeSnapShotDefaultDo) First() (*model.StakeSnapShotDefault, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.StakeSnapShotDefault), nil
	}
}

func (s stakeSnapShotDefaultDo) Take() (*model.StakeSnapShotDefault, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.StakeSnapShotDefault), nil
	}
}

func (s stakeSnapShotDefaultDo) Last() (*model.StakeSnapShotDefault, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.StakeSnapShotDefault), nil
	}
}

func (s stakeSnapShotDefaultDo) Find() ([]*model.StakeSnapShotDefault, error) {
	result, err := s.DO.Find()
	return result.([]*model.StakeSnapShotDefault), err
}

func (s stakeSnapShotDefaultDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.StakeSnapShotDefault, err error) {
	buf := make([]*model.StakeSnapShotDefault, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s stakeSnapShotDefaultDo) FindInBatches(result *[]*model.StakeSnapShotDefault, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s stakeSnapShotDefaultDo) Attrs(attrs ...field.AssignExpr) IStakeSnapShotDefaultDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s stakeSnapShotDefaultDo) Assign(attrs ...field.AssignExpr) IStakeSnapShotDefaultDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s stakeSnapShotDefaultDo) Joins(fields ...field.RelationField) IStakeSnapShotDefaultDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s stakeSnapShotDefaultDo) Preload(fields ...field.RelationField) IStakeSnapShotDefaultDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s stakeSnapShotDefaultDo) FirstOrInit() (*model.StakeSnapShotDefault, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.StakeSnapShotDefault), nil
	}
}

func (s stakeSnapShotDefaultDo) FirstOrCreate() (*model.StakeSnapShotDefault, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.StakeSnapShotDefault), nil
	}
}

func (s stakeSnapShotDefaultDo) FindByPage(offset int, limit int) (result []*model.StakeSnapShotDefault, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s stakeSnapShotDefaultDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s stakeSnapShotDefaultDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s stakeSnapShotDefaultDo) Delete(models ...*model.StakeSnapShotDefault) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *stakeSnapShotDefaultDo) withDO(do gen.Dao) *stakeSnapShotDefaultDo {
	s.DO = *do.(*gen.DO)
	return s
}
