// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"oshit-go/common/pkg/dal/model"
)

func newStakeAmmConfig(db *gorm.DB, opts ...gen.DOOption) stakeAmmConfig {
	_stakeAmmConfig := stakeAmmConfig{}

	_stakeAmmConfig.stakeAmmConfigDo.UseDB(db, opts...)
	_stakeAmmConfig.stakeAmmConfigDo.UseModel(&model.StakeAmmConfig{})

	tableName := _stakeAmmConfig.stakeAmmConfigDo.TableName()
	_stakeAmmConfig.ALL = field.NewAsterisk(tableName)
	_stakeAmmConfig.QuoteToken = field.NewString(tableName, "quote_token")
	_stakeAmmConfig.PublicKey = field.NewString(tableName, "public_key")

	_stakeAmmConfig.fillFieldMap()

	return _stakeAmmConfig
}

type stakeAmmConfig struct {
	stakeAmmConfigDo stakeAmmConfigDo

	ALL        field.Asterisk
	QuoteToken field.String
	PublicKey  field.String

	fieldMap map[string]field.Expr
}

func (s stakeAmmConfig) Table(newTableName string) *stakeAmmConfig {
	s.stakeAmmConfigDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s stakeAmmConfig) As(alias string) *stakeAmmConfig {
	s.stakeAmmConfigDo.DO = *(s.stakeAmmConfigDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *stakeAmmConfig) updateTableName(table string) *stakeAmmConfig {
	s.ALL = field.NewAsterisk(table)
	s.QuoteToken = field.NewString(table, "quote_token")
	s.PublicKey = field.NewString(table, "public_key")

	s.fillFieldMap()

	return s
}

func (s *stakeAmmConfig) WithContext(ctx context.Context) IStakeAmmConfigDo {
	return s.stakeAmmConfigDo.WithContext(ctx)
}

func (s stakeAmmConfig) TableName() string { return s.stakeAmmConfigDo.TableName() }

func (s stakeAmmConfig) Alias() string { return s.stakeAmmConfigDo.Alias() }

func (s stakeAmmConfig) Columns(cols ...field.Expr) gen.Columns {
	return s.stakeAmmConfigDo.Columns(cols...)
}

func (s *stakeAmmConfig) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *stakeAmmConfig) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 2)
	s.fieldMap["quote_token"] = s.QuoteToken
	s.fieldMap["public_key"] = s.PublicKey
}

func (s stakeAmmConfig) clone(db *gorm.DB) stakeAmmConfig {
	s.stakeAmmConfigDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s stakeAmmConfig) replaceDB(db *gorm.DB) stakeAmmConfig {
	s.stakeAmmConfigDo.ReplaceDB(db)
	return s
}

type stakeAmmConfigDo struct{ gen.DO }

type IStakeAmmConfigDo interface {
	gen.SubQuery
	Debug() IStakeAmmConfigDo
	WithContext(ctx context.Context) IStakeAmmConfigDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IStakeAmmConfigDo
	WriteDB() IStakeAmmConfigDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IStakeAmmConfigDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IStakeAmmConfigDo
	Not(conds ...gen.Condition) IStakeAmmConfigDo
	Or(conds ...gen.Condition) IStakeAmmConfigDo
	Select(conds ...field.Expr) IStakeAmmConfigDo
	Where(conds ...gen.Condition) IStakeAmmConfigDo
	Order(conds ...field.Expr) IStakeAmmConfigDo
	Distinct(cols ...field.Expr) IStakeAmmConfigDo
	Omit(cols ...field.Expr) IStakeAmmConfigDo
	Join(table schema.Tabler, on ...field.Expr) IStakeAmmConfigDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IStakeAmmConfigDo
	RightJoin(table schema.Tabler, on ...field.Expr) IStakeAmmConfigDo
	Group(cols ...field.Expr) IStakeAmmConfigDo
	Having(conds ...gen.Condition) IStakeAmmConfigDo
	Limit(limit int) IStakeAmmConfigDo
	Offset(offset int) IStakeAmmConfigDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IStakeAmmConfigDo
	Unscoped() IStakeAmmConfigDo
	Create(values ...*model.StakeAmmConfig) error
	CreateInBatches(values []*model.StakeAmmConfig, batchSize int) error
	Save(values ...*model.StakeAmmConfig) error
	First() (*model.StakeAmmConfig, error)
	Take() (*model.StakeAmmConfig, error)
	Last() (*model.StakeAmmConfig, error)
	Find() ([]*model.StakeAmmConfig, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.StakeAmmConfig, err error)
	FindInBatches(result *[]*model.StakeAmmConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.StakeAmmConfig) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IStakeAmmConfigDo
	Assign(attrs ...field.AssignExpr) IStakeAmmConfigDo
	Joins(fields ...field.RelationField) IStakeAmmConfigDo
	Preload(fields ...field.RelationField) IStakeAmmConfigDo
	FirstOrInit() (*model.StakeAmmConfig, error)
	FirstOrCreate() (*model.StakeAmmConfig, error)
	FindByPage(offset int, limit int) (result []*model.StakeAmmConfig, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IStakeAmmConfigDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s stakeAmmConfigDo) Debug() IStakeAmmConfigDo {
	return s.withDO(s.DO.Debug())
}

func (s stakeAmmConfigDo) WithContext(ctx context.Context) IStakeAmmConfigDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s stakeAmmConfigDo) ReadDB() IStakeAmmConfigDo {
	return s.Clauses(dbresolver.Read)
}

func (s stakeAmmConfigDo) WriteDB() IStakeAmmConfigDo {
	return s.Clauses(dbresolver.Write)
}

func (s stakeAmmConfigDo) Session(config *gorm.Session) IStakeAmmConfigDo {
	return s.withDO(s.DO.Session(config))
}

func (s stakeAmmConfigDo) Clauses(conds ...clause.Expression) IStakeAmmConfigDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s stakeAmmConfigDo) Returning(value interface{}, columns ...string) IStakeAmmConfigDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s stakeAmmConfigDo) Not(conds ...gen.Condition) IStakeAmmConfigDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s stakeAmmConfigDo) Or(conds ...gen.Condition) IStakeAmmConfigDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s stakeAmmConfigDo) Select(conds ...field.Expr) IStakeAmmConfigDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s stakeAmmConfigDo) Where(conds ...gen.Condition) IStakeAmmConfigDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s stakeAmmConfigDo) Order(conds ...field.Expr) IStakeAmmConfigDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s stakeAmmConfigDo) Distinct(cols ...field.Expr) IStakeAmmConfigDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s stakeAmmConfigDo) Omit(cols ...field.Expr) IStakeAmmConfigDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s stakeAmmConfigDo) Join(table schema.Tabler, on ...field.Expr) IStakeAmmConfigDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s stakeAmmConfigDo) LeftJoin(table schema.Tabler, on ...field.Expr) IStakeAmmConfigDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s stakeAmmConfigDo) RightJoin(table schema.Tabler, on ...field.Expr) IStakeAmmConfigDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s stakeAmmConfigDo) Group(cols ...field.Expr) IStakeAmmConfigDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s stakeAmmConfigDo) Having(conds ...gen.Condition) IStakeAmmConfigDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s stakeAmmConfigDo) Limit(limit int) IStakeAmmConfigDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s stakeAmmConfigDo) Offset(offset int) IStakeAmmConfigDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s stakeAmmConfigDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IStakeAmmConfigDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s stakeAmmConfigDo) Unscoped() IStakeAmmConfigDo {
	return s.withDO(s.DO.Unscoped())
}

func (s stakeAmmConfigDo) Create(values ...*model.StakeAmmConfig) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s stakeAmmConfigDo) CreateInBatches(values []*model.StakeAmmConfig, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s stakeAmmConfigDo) Save(values ...*model.StakeAmmConfig) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s stakeAmmConfigDo) First() (*model.StakeAmmConfig, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.StakeAmmConfig), nil
	}
}

func (s stakeAmmConfigDo) Take() (*model.StakeAmmConfig, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.StakeAmmConfig), nil
	}
}

func (s stakeAmmConfigDo) Last() (*model.StakeAmmConfig, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.StakeAmmConfig), nil
	}
}

func (s stakeAmmConfigDo) Find() ([]*model.StakeAmmConfig, error) {
	result, err := s.DO.Find()
	return result.([]*model.StakeAmmConfig), err
}

func (s stakeAmmConfigDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.StakeAmmConfig, err error) {
	buf := make([]*model.StakeAmmConfig, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s stakeAmmConfigDo) FindInBatches(result *[]*model.StakeAmmConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s stakeAmmConfigDo) Attrs(attrs ...field.AssignExpr) IStakeAmmConfigDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s stakeAmmConfigDo) Assign(attrs ...field.AssignExpr) IStakeAmmConfigDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s stakeAmmConfigDo) Joins(fields ...field.RelationField) IStakeAmmConfigDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s stakeAmmConfigDo) Preload(fields ...field.RelationField) IStakeAmmConfigDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s stakeAmmConfigDo) FirstOrInit() (*model.StakeAmmConfig, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.StakeAmmConfig), nil
	}
}

func (s stakeAmmConfigDo) FirstOrCreate() (*model.StakeAmmConfig, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.StakeAmmConfig), nil
	}
}

func (s stakeAmmConfigDo) FindByPage(offset int, limit int) (result []*model.StakeAmmConfig, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s stakeAmmConfigDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s stakeAmmConfigDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s stakeAmmConfigDo) Delete(models ...*model.StakeAmmConfig) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *stakeAmmConfigDo) withDO(do gen.Dao) *stakeAmmConfigDo {
	s.DO = *do.(*gen.DO)
	return s
}
