// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"oshit-go/common/pkg/dal/model"
)

func newStakeLeader(db *gorm.DB, opts ...gen.DOOption) stakeLeader {
	_stakeLeader := stakeLeader{}

	_stakeLeader.stakeLeaderDo.UseDB(db, opts...)
	_stakeLeader.stakeLeaderDo.UseModel(&model.StakeLeader{})

	tableName := _stakeLeader.stakeLeaderDo.TableName()
	_stakeLeader.ALL = field.NewAsterisk(tableName)
	_stakeLeader.RecordID = field.NewString(tableName, "record_id")
	_stakeLeader.NativeAccount = field.NewString(tableName, "native_account")
	_stakeLeader.LeaderLevel = field.NewInt16(tableName, "leader_level")
	_stakeLeader.UpLeader = field.NewString(tableName, "up_leader")
	_stakeLeader.CreatedAt = field.NewTime(tableName, "created_at")
	_stakeLeader.UpdatedAt = field.NewTime(tableName, "updated_at")

	_stakeLeader.fillFieldMap()

	return _stakeLeader
}

type stakeLeader struct {
	stakeLeaderDo stakeLeaderDo

	ALL           field.Asterisk
	RecordID      field.String
	NativeAccount field.String
	LeaderLevel   field.Int16
	UpLeader      field.String
	CreatedAt     field.Time
	UpdatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (s stakeLeader) Table(newTableName string) *stakeLeader {
	s.stakeLeaderDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s stakeLeader) As(alias string) *stakeLeader {
	s.stakeLeaderDo.DO = *(s.stakeLeaderDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *stakeLeader) updateTableName(table string) *stakeLeader {
	s.ALL = field.NewAsterisk(table)
	s.RecordID = field.NewString(table, "record_id")
	s.NativeAccount = field.NewString(table, "native_account")
	s.LeaderLevel = field.NewInt16(table, "leader_level")
	s.UpLeader = field.NewString(table, "up_leader")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")

	s.fillFieldMap()

	return s
}

func (s *stakeLeader) WithContext(ctx context.Context) IStakeLeaderDo {
	return s.stakeLeaderDo.WithContext(ctx)
}

func (s stakeLeader) TableName() string { return s.stakeLeaderDo.TableName() }

func (s stakeLeader) Alias() string { return s.stakeLeaderDo.Alias() }

func (s stakeLeader) Columns(cols ...field.Expr) gen.Columns { return s.stakeLeaderDo.Columns(cols...) }

func (s *stakeLeader) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *stakeLeader) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 6)
	s.fieldMap["record_id"] = s.RecordID
	s.fieldMap["native_account"] = s.NativeAccount
	s.fieldMap["leader_level"] = s.LeaderLevel
	s.fieldMap["up_leader"] = s.UpLeader
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
}

func (s stakeLeader) clone(db *gorm.DB) stakeLeader {
	s.stakeLeaderDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s stakeLeader) replaceDB(db *gorm.DB) stakeLeader {
	s.stakeLeaderDo.ReplaceDB(db)
	return s
}

type stakeLeaderDo struct{ gen.DO }

type IStakeLeaderDo interface {
	gen.SubQuery
	Debug() IStakeLeaderDo
	WithContext(ctx context.Context) IStakeLeaderDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IStakeLeaderDo
	WriteDB() IStakeLeaderDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IStakeLeaderDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IStakeLeaderDo
	Not(conds ...gen.Condition) IStakeLeaderDo
	Or(conds ...gen.Condition) IStakeLeaderDo
	Select(conds ...field.Expr) IStakeLeaderDo
	Where(conds ...gen.Condition) IStakeLeaderDo
	Order(conds ...field.Expr) IStakeLeaderDo
	Distinct(cols ...field.Expr) IStakeLeaderDo
	Omit(cols ...field.Expr) IStakeLeaderDo
	Join(table schema.Tabler, on ...field.Expr) IStakeLeaderDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IStakeLeaderDo
	RightJoin(table schema.Tabler, on ...field.Expr) IStakeLeaderDo
	Group(cols ...field.Expr) IStakeLeaderDo
	Having(conds ...gen.Condition) IStakeLeaderDo
	Limit(limit int) IStakeLeaderDo
	Offset(offset int) IStakeLeaderDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IStakeLeaderDo
	Unscoped() IStakeLeaderDo
	Create(values ...*model.StakeLeader) error
	CreateInBatches(values []*model.StakeLeader, batchSize int) error
	Save(values ...*model.StakeLeader) error
	First() (*model.StakeLeader, error)
	Take() (*model.StakeLeader, error)
	Last() (*model.StakeLeader, error)
	Find() ([]*model.StakeLeader, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.StakeLeader, err error)
	FindInBatches(result *[]*model.StakeLeader, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.StakeLeader) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IStakeLeaderDo
	Assign(attrs ...field.AssignExpr) IStakeLeaderDo
	Joins(fields ...field.RelationField) IStakeLeaderDo
	Preload(fields ...field.RelationField) IStakeLeaderDo
	FirstOrInit() (*model.StakeLeader, error)
	FirstOrCreate() (*model.StakeLeader, error)
	FindByPage(offset int, limit int) (result []*model.StakeLeader, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IStakeLeaderDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s stakeLeaderDo) Debug() IStakeLeaderDo {
	return s.withDO(s.DO.Debug())
}

func (s stakeLeaderDo) WithContext(ctx context.Context) IStakeLeaderDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s stakeLeaderDo) ReadDB() IStakeLeaderDo {
	return s.Clauses(dbresolver.Read)
}

func (s stakeLeaderDo) WriteDB() IStakeLeaderDo {
	return s.Clauses(dbresolver.Write)
}

func (s stakeLeaderDo) Session(config *gorm.Session) IStakeLeaderDo {
	return s.withDO(s.DO.Session(config))
}

func (s stakeLeaderDo) Clauses(conds ...clause.Expression) IStakeLeaderDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s stakeLeaderDo) Returning(value interface{}, columns ...string) IStakeLeaderDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s stakeLeaderDo) Not(conds ...gen.Condition) IStakeLeaderDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s stakeLeaderDo) Or(conds ...gen.Condition) IStakeLeaderDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s stakeLeaderDo) Select(conds ...field.Expr) IStakeLeaderDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s stakeLeaderDo) Where(conds ...gen.Condition) IStakeLeaderDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s stakeLeaderDo) Order(conds ...field.Expr) IStakeLeaderDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s stakeLeaderDo) Distinct(cols ...field.Expr) IStakeLeaderDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s stakeLeaderDo) Omit(cols ...field.Expr) IStakeLeaderDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s stakeLeaderDo) Join(table schema.Tabler, on ...field.Expr) IStakeLeaderDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s stakeLeaderDo) LeftJoin(table schema.Tabler, on ...field.Expr) IStakeLeaderDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s stakeLeaderDo) RightJoin(table schema.Tabler, on ...field.Expr) IStakeLeaderDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s stakeLeaderDo) Group(cols ...field.Expr) IStakeLeaderDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s stakeLeaderDo) Having(conds ...gen.Condition) IStakeLeaderDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s stakeLeaderDo) Limit(limit int) IStakeLeaderDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s stakeLeaderDo) Offset(offset int) IStakeLeaderDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s stakeLeaderDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IStakeLeaderDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s stakeLeaderDo) Unscoped() IStakeLeaderDo {
	return s.withDO(s.DO.Unscoped())
}

func (s stakeLeaderDo) Create(values ...*model.StakeLeader) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s stakeLeaderDo) CreateInBatches(values []*model.StakeLeader, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s stakeLeaderDo) Save(values ...*model.StakeLeader) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s stakeLeaderDo) First() (*model.StakeLeader, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.StakeLeader), nil
	}
}

func (s stakeLeaderDo) Take() (*model.StakeLeader, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.StakeLeader), nil
	}
}

func (s stakeLeaderDo) Last() (*model.StakeLeader, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.StakeLeader), nil
	}
}

func (s stakeLeaderDo) Find() ([]*model.StakeLeader, error) {
	result, err := s.DO.Find()
	return result.([]*model.StakeLeader), err
}

func (s stakeLeaderDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.StakeLeader, err error) {
	buf := make([]*model.StakeLeader, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s stakeLeaderDo) FindInBatches(result *[]*model.StakeLeader, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s stakeLeaderDo) Attrs(attrs ...field.AssignExpr) IStakeLeaderDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s stakeLeaderDo) Assign(attrs ...field.AssignExpr) IStakeLeaderDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s stakeLeaderDo) Joins(fields ...field.RelationField) IStakeLeaderDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s stakeLeaderDo) Preload(fields ...field.RelationField) IStakeLeaderDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s stakeLeaderDo) FirstOrInit() (*model.StakeLeader, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.StakeLeader), nil
	}
}

func (s stakeLeaderDo) FirstOrCreate() (*model.StakeLeader, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.StakeLeader), nil
	}
}

func (s stakeLeaderDo) FindByPage(offset int, limit int) (result []*model.StakeLeader, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s stakeLeaderDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s stakeLeaderDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s stakeLeaderDo) Delete(models ...*model.StakeLeader) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *stakeLeaderDo) withDO(do gen.Dao) *stakeLeaderDo {
	s.DO = *do.(*gen.DO)
	return s
}
