// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"oshit-go/common/pkg/dal/model"
)

func newStakeReward(db *gorm.DB, opts ...gen.DOOption) stakeReward {
	_stakeReward := stakeReward{}

	_stakeReward.stakeRewardDo.UseDB(db, opts...)
	_stakeReward.stakeRewardDo.UseModel(&model.StakeReward{})

	tableName := _stakeReward.stakeRewardDo.TableName()
	_stakeReward.ALL = field.NewAsterisk(tableName)
	_stakeReward.RecordID = field.NewString(tableName, "record_id")
	_stakeReward.GroupID = field.NewString(tableName, "group_id")
	_stakeReward.NativeAccount = field.NewString(tableName, "native_account")
	_stakeReward.StarLevel = field.NewInt32(tableName, "star_level")
	_stakeReward.Base = field.NewFloat64(tableName, "base")
	_stakeReward.Rate = field.NewFloat64(tableName, "rate")
	_stakeReward.RewardAmount = field.NewFloat64(tableName, "reward_amount")
	_stakeReward.StakeType = field.NewInt32(tableName, "stake_type")
	_stakeReward.RewardType = field.NewInt32(tableName, "reward_type")
	_stakeReward.RewardState = field.NewInt32(tableName, "reward_state")
	_stakeReward.Starred = field.NewBool(tableName, "starred")
	_stakeReward.TxID = field.NewString(tableName, "tx_id")
	_stakeReward.Pending = field.NewBool(tableName, "pending")
	_stakeReward.SnapDay = field.NewTime(tableName, "snap_day")
	_stakeReward.CreatedAt = field.NewTime(tableName, "created_at")
	_stakeReward.UpdatedAt = field.NewTime(tableName, "updated_at")

	_stakeReward.fillFieldMap()

	return _stakeReward
}

type stakeReward struct {
	stakeRewardDo stakeRewardDo

	ALL           field.Asterisk
	RecordID      field.String
	GroupID       field.String
	NativeAccount field.String
	StarLevel     field.Int32
	Base          field.Float64
	Rate          field.Float64
	RewardAmount  field.Float64
	StakeType     field.Int32
	RewardType    field.Int32
	RewardState   field.Int32
	Starred       field.Bool
	TxID          field.String
	Pending       field.Bool
	SnapDay       field.Time
	CreatedAt     field.Time
	UpdatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (s stakeReward) Table(newTableName string) *stakeReward {
	s.stakeRewardDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s stakeReward) As(alias string) *stakeReward {
	s.stakeRewardDo.DO = *(s.stakeRewardDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *stakeReward) updateTableName(table string) *stakeReward {
	s.ALL = field.NewAsterisk(table)
	s.RecordID = field.NewString(table, "record_id")
	s.GroupID = field.NewString(table, "group_id")
	s.NativeAccount = field.NewString(table, "native_account")
	s.StarLevel = field.NewInt32(table, "star_level")
	s.Base = field.NewFloat64(table, "base")
	s.Rate = field.NewFloat64(table, "rate")
	s.RewardAmount = field.NewFloat64(table, "reward_amount")
	s.StakeType = field.NewInt32(table, "stake_type")
	s.RewardType = field.NewInt32(table, "reward_type")
	s.RewardState = field.NewInt32(table, "reward_state")
	s.Starred = field.NewBool(table, "starred")
	s.TxID = field.NewString(table, "tx_id")
	s.Pending = field.NewBool(table, "pending")
	s.SnapDay = field.NewTime(table, "snap_day")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")

	s.fillFieldMap()

	return s
}

func (s *stakeReward) WithContext(ctx context.Context) IStakeRewardDo {
	return s.stakeRewardDo.WithContext(ctx)
}

func (s stakeReward) TableName() string { return s.stakeRewardDo.TableName() }

func (s stakeReward) Alias() string { return s.stakeRewardDo.Alias() }

func (s stakeReward) Columns(cols ...field.Expr) gen.Columns { return s.stakeRewardDo.Columns(cols...) }

func (s *stakeReward) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *stakeReward) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 16)
	s.fieldMap["record_id"] = s.RecordID
	s.fieldMap["group_id"] = s.GroupID
	s.fieldMap["native_account"] = s.NativeAccount
	s.fieldMap["star_level"] = s.StarLevel
	s.fieldMap["base"] = s.Base
	s.fieldMap["rate"] = s.Rate
	s.fieldMap["reward_amount"] = s.RewardAmount
	s.fieldMap["stake_type"] = s.StakeType
	s.fieldMap["reward_type"] = s.RewardType
	s.fieldMap["reward_state"] = s.RewardState
	s.fieldMap["starred"] = s.Starred
	s.fieldMap["tx_id"] = s.TxID
	s.fieldMap["pending"] = s.Pending
	s.fieldMap["snap_day"] = s.SnapDay
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
}

func (s stakeReward) clone(db *gorm.DB) stakeReward {
	s.stakeRewardDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s stakeReward) replaceDB(db *gorm.DB) stakeReward {
	s.stakeRewardDo.ReplaceDB(db)
	return s
}

type stakeRewardDo struct{ gen.DO }

type IStakeRewardDo interface {
	gen.SubQuery
	Debug() IStakeRewardDo
	WithContext(ctx context.Context) IStakeRewardDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IStakeRewardDo
	WriteDB() IStakeRewardDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IStakeRewardDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IStakeRewardDo
	Not(conds ...gen.Condition) IStakeRewardDo
	Or(conds ...gen.Condition) IStakeRewardDo
	Select(conds ...field.Expr) IStakeRewardDo
	Where(conds ...gen.Condition) IStakeRewardDo
	Order(conds ...field.Expr) IStakeRewardDo
	Distinct(cols ...field.Expr) IStakeRewardDo
	Omit(cols ...field.Expr) IStakeRewardDo
	Join(table schema.Tabler, on ...field.Expr) IStakeRewardDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IStakeRewardDo
	RightJoin(table schema.Tabler, on ...field.Expr) IStakeRewardDo
	Group(cols ...field.Expr) IStakeRewardDo
	Having(conds ...gen.Condition) IStakeRewardDo
	Limit(limit int) IStakeRewardDo
	Offset(offset int) IStakeRewardDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IStakeRewardDo
	Unscoped() IStakeRewardDo
	Create(values ...*model.StakeReward) error
	CreateInBatches(values []*model.StakeReward, batchSize int) error
	Save(values ...*model.StakeReward) error
	First() (*model.StakeReward, error)
	Take() (*model.StakeReward, error)
	Last() (*model.StakeReward, error)
	Find() ([]*model.StakeReward, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.StakeReward, err error)
	FindInBatches(result *[]*model.StakeReward, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.StakeReward) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IStakeRewardDo
	Assign(attrs ...field.AssignExpr) IStakeRewardDo
	Joins(fields ...field.RelationField) IStakeRewardDo
	Preload(fields ...field.RelationField) IStakeRewardDo
	FirstOrInit() (*model.StakeReward, error)
	FirstOrCreate() (*model.StakeReward, error)
	FindByPage(offset int, limit int) (result []*model.StakeReward, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IStakeRewardDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s stakeRewardDo) Debug() IStakeRewardDo {
	return s.withDO(s.DO.Debug())
}

func (s stakeRewardDo) WithContext(ctx context.Context) IStakeRewardDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s stakeRewardDo) ReadDB() IStakeRewardDo {
	return s.Clauses(dbresolver.Read)
}

func (s stakeRewardDo) WriteDB() IStakeRewardDo {
	return s.Clauses(dbresolver.Write)
}

func (s stakeRewardDo) Session(config *gorm.Session) IStakeRewardDo {
	return s.withDO(s.DO.Session(config))
}

func (s stakeRewardDo) Clauses(conds ...clause.Expression) IStakeRewardDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s stakeRewardDo) Returning(value interface{}, columns ...string) IStakeRewardDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s stakeRewardDo) Not(conds ...gen.Condition) IStakeRewardDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s stakeRewardDo) Or(conds ...gen.Condition) IStakeRewardDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s stakeRewardDo) Select(conds ...field.Expr) IStakeRewardDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s stakeRewardDo) Where(conds ...gen.Condition) IStakeRewardDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s stakeRewardDo) Order(conds ...field.Expr) IStakeRewardDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s stakeRewardDo) Distinct(cols ...field.Expr) IStakeRewardDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s stakeRewardDo) Omit(cols ...field.Expr) IStakeRewardDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s stakeRewardDo) Join(table schema.Tabler, on ...field.Expr) IStakeRewardDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s stakeRewardDo) LeftJoin(table schema.Tabler, on ...field.Expr) IStakeRewardDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s stakeRewardDo) RightJoin(table schema.Tabler, on ...field.Expr) IStakeRewardDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s stakeRewardDo) Group(cols ...field.Expr) IStakeRewardDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s stakeRewardDo) Having(conds ...gen.Condition) IStakeRewardDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s stakeRewardDo) Limit(limit int) IStakeRewardDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s stakeRewardDo) Offset(offset int) IStakeRewardDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s stakeRewardDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IStakeRewardDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s stakeRewardDo) Unscoped() IStakeRewardDo {
	return s.withDO(s.DO.Unscoped())
}

func (s stakeRewardDo) Create(values ...*model.StakeReward) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s stakeRewardDo) CreateInBatches(values []*model.StakeReward, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s stakeRewardDo) Save(values ...*model.StakeReward) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s stakeRewardDo) First() (*model.StakeReward, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.StakeReward), nil
	}
}

func (s stakeRewardDo) Take() (*model.StakeReward, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.StakeReward), nil
	}
}

func (s stakeRewardDo) Last() (*model.StakeReward, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.StakeReward), nil
	}
}

func (s stakeRewardDo) Find() ([]*model.StakeReward, error) {
	result, err := s.DO.Find()
	return result.([]*model.StakeReward), err
}

func (s stakeRewardDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.StakeReward, err error) {
	buf := make([]*model.StakeReward, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s stakeRewardDo) FindInBatches(result *[]*model.StakeReward, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s stakeRewardDo) Attrs(attrs ...field.AssignExpr) IStakeRewardDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s stakeRewardDo) Assign(attrs ...field.AssignExpr) IStakeRewardDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s stakeRewardDo) Joins(fields ...field.RelationField) IStakeRewardDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s stakeRewardDo) Preload(fields ...field.RelationField) IStakeRewardDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s stakeRewardDo) FirstOrInit() (*model.StakeReward, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.StakeReward), nil
	}
}

func (s stakeRewardDo) FirstOrCreate() (*model.StakeReward, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.StakeReward), nil
	}
}

func (s stakeRewardDo) FindByPage(offset int, limit int) (result []*model.StakeReward, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s stakeRewardDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s stakeRewardDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s stakeRewardDo) Delete(models ...*model.StakeReward) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *stakeRewardDo) withDO(do gen.Dao) *stakeRewardDo {
	s.DO = *do.(*gen.DO)
	return s
}
