// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"oshit-go/common/pkg/dal/model"
)

func newStakeSnapShot(db *gorm.DB, opts ...gen.DOOption) stakeSnapShot {
	_stakeSnapShot := stakeSnapShot{}

	_stakeSnapShot.stakeSnapShotDo.UseDB(db, opts...)
	_stakeSnapShot.stakeSnapShotDo.UseModel(&model.StakeSnapShot{})

	tableName := _stakeSnapShot.stakeSnapShotDo.TableName()
	_stakeSnapShot.ALL = field.NewAsterisk(tableName)
	_stakeSnapShot.RecordID = field.NewString(tableName, "record_id")
	_stakeSnapShot.NativeAccount = field.NewString(tableName, "native_account")
	_stakeSnapShot.Amount = field.NewFloat64(tableName, "amount")
	_stakeSnapShot.StakeType = field.NewInt32(tableName, "stake_type")
	_stakeSnapShot.SnapDay = field.NewTime(tableName, "snap_day")
	_stakeSnapShot.CreatedAt = field.NewTime(tableName, "created_at")
	_stakeSnapShot.UpdatedAt = field.NewTime(tableName, "updated_at")

	_stakeSnapShot.fillFieldMap()

	return _stakeSnapShot
}

type stakeSnapShot struct {
	stakeSnapShotDo stakeSnapShotDo

	ALL           field.Asterisk
	RecordID      field.String
	NativeAccount field.String
	Amount        field.Float64
	StakeType     field.Int32
	SnapDay       field.Time
	CreatedAt     field.Time
	UpdatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (s stakeSnapShot) Table(newTableName string) *stakeSnapShot {
	s.stakeSnapShotDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s stakeSnapShot) As(alias string) *stakeSnapShot {
	s.stakeSnapShotDo.DO = *(s.stakeSnapShotDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *stakeSnapShot) updateTableName(table string) *stakeSnapShot {
	s.ALL = field.NewAsterisk(table)
	s.RecordID = field.NewString(table, "record_id")
	s.NativeAccount = field.NewString(table, "native_account")
	s.Amount = field.NewFloat64(table, "amount")
	s.StakeType = field.NewInt32(table, "stake_type")
	s.SnapDay = field.NewTime(table, "snap_day")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")

	s.fillFieldMap()

	return s
}

func (s *stakeSnapShot) WithContext(ctx context.Context) IStakeSnapShotDo {
	return s.stakeSnapShotDo.WithContext(ctx)
}

func (s stakeSnapShot) TableName() string { return s.stakeSnapShotDo.TableName() }

func (s stakeSnapShot) Alias() string { return s.stakeSnapShotDo.Alias() }

func (s stakeSnapShot) Columns(cols ...field.Expr) gen.Columns {
	return s.stakeSnapShotDo.Columns(cols...)
}

func (s *stakeSnapShot) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *stakeSnapShot) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 7)
	s.fieldMap["record_id"] = s.RecordID
	s.fieldMap["native_account"] = s.NativeAccount
	s.fieldMap["amount"] = s.Amount
	s.fieldMap["stake_type"] = s.StakeType
	s.fieldMap["snap_day"] = s.SnapDay
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
}

func (s stakeSnapShot) clone(db *gorm.DB) stakeSnapShot {
	s.stakeSnapShotDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s stakeSnapShot) replaceDB(db *gorm.DB) stakeSnapShot {
	s.stakeSnapShotDo.ReplaceDB(db)
	return s
}

type stakeSnapShotDo struct{ gen.DO }

type IStakeSnapShotDo interface {
	gen.SubQuery
	Debug() IStakeSnapShotDo
	WithContext(ctx context.Context) IStakeSnapShotDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IStakeSnapShotDo
	WriteDB() IStakeSnapShotDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IStakeSnapShotDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IStakeSnapShotDo
	Not(conds ...gen.Condition) IStakeSnapShotDo
	Or(conds ...gen.Condition) IStakeSnapShotDo
	Select(conds ...field.Expr) IStakeSnapShotDo
	Where(conds ...gen.Condition) IStakeSnapShotDo
	Order(conds ...field.Expr) IStakeSnapShotDo
	Distinct(cols ...field.Expr) IStakeSnapShotDo
	Omit(cols ...field.Expr) IStakeSnapShotDo
	Join(table schema.Tabler, on ...field.Expr) IStakeSnapShotDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IStakeSnapShotDo
	RightJoin(table schema.Tabler, on ...field.Expr) IStakeSnapShotDo
	Group(cols ...field.Expr) IStakeSnapShotDo
	Having(conds ...gen.Condition) IStakeSnapShotDo
	Limit(limit int) IStakeSnapShotDo
	Offset(offset int) IStakeSnapShotDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IStakeSnapShotDo
	Unscoped() IStakeSnapShotDo
	Create(values ...*model.StakeSnapShot) error
	CreateInBatches(values []*model.StakeSnapShot, batchSize int) error
	Save(values ...*model.StakeSnapShot) error
	First() (*model.StakeSnapShot, error)
	Take() (*model.StakeSnapShot, error)
	Last() (*model.StakeSnapShot, error)
	Find() ([]*model.StakeSnapShot, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.StakeSnapShot, err error)
	FindInBatches(result *[]*model.StakeSnapShot, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.StakeSnapShot) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IStakeSnapShotDo
	Assign(attrs ...field.AssignExpr) IStakeSnapShotDo
	Joins(fields ...field.RelationField) IStakeSnapShotDo
	Preload(fields ...field.RelationField) IStakeSnapShotDo
	FirstOrInit() (*model.StakeSnapShot, error)
	FirstOrCreate() (*model.StakeSnapShot, error)
	FindByPage(offset int, limit int) (result []*model.StakeSnapShot, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IStakeSnapShotDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s stakeSnapShotDo) Debug() IStakeSnapShotDo {
	return s.withDO(s.DO.Debug())
}

func (s stakeSnapShotDo) WithContext(ctx context.Context) IStakeSnapShotDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s stakeSnapShotDo) ReadDB() IStakeSnapShotDo {
	return s.Clauses(dbresolver.Read)
}

func (s stakeSnapShotDo) WriteDB() IStakeSnapShotDo {
	return s.Clauses(dbresolver.Write)
}

func (s stakeSnapShotDo) Session(config *gorm.Session) IStakeSnapShotDo {
	return s.withDO(s.DO.Session(config))
}

func (s stakeSnapShotDo) Clauses(conds ...clause.Expression) IStakeSnapShotDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s stakeSnapShotDo) Returning(value interface{}, columns ...string) IStakeSnapShotDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s stakeSnapShotDo) Not(conds ...gen.Condition) IStakeSnapShotDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s stakeSnapShotDo) Or(conds ...gen.Condition) IStakeSnapShotDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s stakeSnapShotDo) Select(conds ...field.Expr) IStakeSnapShotDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s stakeSnapShotDo) Where(conds ...gen.Condition) IStakeSnapShotDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s stakeSnapShotDo) Order(conds ...field.Expr) IStakeSnapShotDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s stakeSnapShotDo) Distinct(cols ...field.Expr) IStakeSnapShotDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s stakeSnapShotDo) Omit(cols ...field.Expr) IStakeSnapShotDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s stakeSnapShotDo) Join(table schema.Tabler, on ...field.Expr) IStakeSnapShotDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s stakeSnapShotDo) LeftJoin(table schema.Tabler, on ...field.Expr) IStakeSnapShotDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s stakeSnapShotDo) RightJoin(table schema.Tabler, on ...field.Expr) IStakeSnapShotDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s stakeSnapShotDo) Group(cols ...field.Expr) IStakeSnapShotDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s stakeSnapShotDo) Having(conds ...gen.Condition) IStakeSnapShotDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s stakeSnapShotDo) Limit(limit int) IStakeSnapShotDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s stakeSnapShotDo) Offset(offset int) IStakeSnapShotDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s stakeSnapShotDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IStakeSnapShotDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s stakeSnapShotDo) Unscoped() IStakeSnapShotDo {
	return s.withDO(s.DO.Unscoped())
}

func (s stakeSnapShotDo) Create(values ...*model.StakeSnapShot) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s stakeSnapShotDo) CreateInBatches(values []*model.StakeSnapShot, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s stakeSnapShotDo) Save(values ...*model.StakeSnapShot) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s stakeSnapShotDo) First() (*model.StakeSnapShot, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.StakeSnapShot), nil
	}
}

func (s stakeSnapShotDo) Take() (*model.StakeSnapShot, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.StakeSnapShot), nil
	}
}

func (s stakeSnapShotDo) Last() (*model.StakeSnapShot, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.StakeSnapShot), nil
	}
}

func (s stakeSnapShotDo) Find() ([]*model.StakeSnapShot, error) {
	result, err := s.DO.Find()
	return result.([]*model.StakeSnapShot), err
}

func (s stakeSnapShotDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.StakeSnapShot, err error) {
	buf := make([]*model.StakeSnapShot, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s stakeSnapShotDo) FindInBatches(result *[]*model.StakeSnapShot, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s stakeSnapShotDo) Attrs(attrs ...field.AssignExpr) IStakeSnapShotDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s stakeSnapShotDo) Assign(attrs ...field.AssignExpr) IStakeSnapShotDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s stakeSnapShotDo) Joins(fields ...field.RelationField) IStakeSnapShotDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s stakeSnapShotDo) Preload(fields ...field.RelationField) IStakeSnapShotDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s stakeSnapShotDo) FirstOrInit() (*model.StakeSnapShot, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.StakeSnapShot), nil
	}
}

func (s stakeSnapShotDo) FirstOrCreate() (*model.StakeSnapShot, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.StakeSnapShot), nil
	}
}

func (s stakeSnapShotDo) FindByPage(offset int, limit int) (result []*model.StakeSnapShot, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s stakeSnapShotDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s stakeSnapShotDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s stakeSnapShotDo) Delete(models ...*model.StakeSnapShot) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *stakeSnapShotDo) withDO(do gen.Dao) *stakeSnapShotDo {
	s.DO = *do.(*gen.DO)
	return s
}
