// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"oshit-go/common/pkg/dal/model"
)

func newStakeLeaderRewardClaim(db *gorm.DB, opts ...gen.DOOption) stakeLeaderRewardClaim {
	_stakeLeaderRewardClaim := stakeLeaderRewardClaim{}

	_stakeLeaderRewardClaim.stakeLeaderRewardClaimDo.UseDB(db, opts...)
	_stakeLeaderRewardClaim.stakeLeaderRewardClaimDo.UseModel(&model.StakeLeaderRewardClaim{})

	tableName := _stakeLeaderRewardClaim.stakeLeaderRewardClaimDo.TableName()
	_stakeLeaderRewardClaim.ALL = field.NewAsterisk(tableName)
	_stakeLeaderRewardClaim.RecordID = field.NewString(tableName, "record_id")
	_stakeLeaderRewardClaim.NativeAccount = field.NewString(tableName, "native_account")
	_stakeLeaderRewardClaim.RewardIds = field.NewString(tableName, "reward_ids")
	_stakeLeaderRewardClaim.TxID = field.NewString(tableName, "tx_id")
	_stakeLeaderRewardClaim.TxState = field.NewInt32(tableName, "tx_state")
	_stakeLeaderRewardClaim.CreatedAt = field.NewTime(tableName, "created_at")
	_stakeLeaderRewardClaim.UpdatedAt = field.NewTime(tableName, "updated_at")

	_stakeLeaderRewardClaim.fillFieldMap()

	return _stakeLeaderRewardClaim
}

type stakeLeaderRewardClaim struct {
	stakeLeaderRewardClaimDo stakeLeaderRewardClaimDo

	ALL           field.Asterisk
	RecordID      field.String
	NativeAccount field.String
	RewardIds     field.String
	TxID          field.String
	TxState       field.Int32
	CreatedAt     field.Time
	UpdatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (s stakeLeaderRewardClaim) Table(newTableName string) *stakeLeaderRewardClaim {
	s.stakeLeaderRewardClaimDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s stakeLeaderRewardClaim) As(alias string) *stakeLeaderRewardClaim {
	s.stakeLeaderRewardClaimDo.DO = *(s.stakeLeaderRewardClaimDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *stakeLeaderRewardClaim) updateTableName(table string) *stakeLeaderRewardClaim {
	s.ALL = field.NewAsterisk(table)
	s.RecordID = field.NewString(table, "record_id")
	s.NativeAccount = field.NewString(table, "native_account")
	s.RewardIds = field.NewString(table, "reward_ids")
	s.TxID = field.NewString(table, "tx_id")
	s.TxState = field.NewInt32(table, "tx_state")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")

	s.fillFieldMap()

	return s
}

func (s *stakeLeaderRewardClaim) WithContext(ctx context.Context) IStakeLeaderRewardClaimDo {
	return s.stakeLeaderRewardClaimDo.WithContext(ctx)
}

func (s stakeLeaderRewardClaim) TableName() string { return s.stakeLeaderRewardClaimDo.TableName() }

func (s stakeLeaderRewardClaim) Alias() string { return s.stakeLeaderRewardClaimDo.Alias() }

func (s stakeLeaderRewardClaim) Columns(cols ...field.Expr) gen.Columns {
	return s.stakeLeaderRewardClaimDo.Columns(cols...)
}

func (s *stakeLeaderRewardClaim) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *stakeLeaderRewardClaim) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 7)
	s.fieldMap["record_id"] = s.RecordID
	s.fieldMap["native_account"] = s.NativeAccount
	s.fieldMap["reward_ids"] = s.RewardIds
	s.fieldMap["tx_id"] = s.TxID
	s.fieldMap["tx_state"] = s.TxState
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
}

func (s stakeLeaderRewardClaim) clone(db *gorm.DB) stakeLeaderRewardClaim {
	s.stakeLeaderRewardClaimDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s stakeLeaderRewardClaim) replaceDB(db *gorm.DB) stakeLeaderRewardClaim {
	s.stakeLeaderRewardClaimDo.ReplaceDB(db)
	return s
}

type stakeLeaderRewardClaimDo struct{ gen.DO }

type IStakeLeaderRewardClaimDo interface {
	gen.SubQuery
	Debug() IStakeLeaderRewardClaimDo
	WithContext(ctx context.Context) IStakeLeaderRewardClaimDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IStakeLeaderRewardClaimDo
	WriteDB() IStakeLeaderRewardClaimDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IStakeLeaderRewardClaimDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IStakeLeaderRewardClaimDo
	Not(conds ...gen.Condition) IStakeLeaderRewardClaimDo
	Or(conds ...gen.Condition) IStakeLeaderRewardClaimDo
	Select(conds ...field.Expr) IStakeLeaderRewardClaimDo
	Where(conds ...gen.Condition) IStakeLeaderRewardClaimDo
	Order(conds ...field.Expr) IStakeLeaderRewardClaimDo
	Distinct(cols ...field.Expr) IStakeLeaderRewardClaimDo
	Omit(cols ...field.Expr) IStakeLeaderRewardClaimDo
	Join(table schema.Tabler, on ...field.Expr) IStakeLeaderRewardClaimDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IStakeLeaderRewardClaimDo
	RightJoin(table schema.Tabler, on ...field.Expr) IStakeLeaderRewardClaimDo
	Group(cols ...field.Expr) IStakeLeaderRewardClaimDo
	Having(conds ...gen.Condition) IStakeLeaderRewardClaimDo
	Limit(limit int) IStakeLeaderRewardClaimDo
	Offset(offset int) IStakeLeaderRewardClaimDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IStakeLeaderRewardClaimDo
	Unscoped() IStakeLeaderRewardClaimDo
	Create(values ...*model.StakeLeaderRewardClaim) error
	CreateInBatches(values []*model.StakeLeaderRewardClaim, batchSize int) error
	Save(values ...*model.StakeLeaderRewardClaim) error
	First() (*model.StakeLeaderRewardClaim, error)
	Take() (*model.StakeLeaderRewardClaim, error)
	Last() (*model.StakeLeaderRewardClaim, error)
	Find() ([]*model.StakeLeaderRewardClaim, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.StakeLeaderRewardClaim, err error)
	FindInBatches(result *[]*model.StakeLeaderRewardClaim, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.StakeLeaderRewardClaim) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IStakeLeaderRewardClaimDo
	Assign(attrs ...field.AssignExpr) IStakeLeaderRewardClaimDo
	Joins(fields ...field.RelationField) IStakeLeaderRewardClaimDo
	Preload(fields ...field.RelationField) IStakeLeaderRewardClaimDo
	FirstOrInit() (*model.StakeLeaderRewardClaim, error)
	FirstOrCreate() (*model.StakeLeaderRewardClaim, error)
	FindByPage(offset int, limit int) (result []*model.StakeLeaderRewardClaim, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IStakeLeaderRewardClaimDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s stakeLeaderRewardClaimDo) Debug() IStakeLeaderRewardClaimDo {
	return s.withDO(s.DO.Debug())
}

func (s stakeLeaderRewardClaimDo) WithContext(ctx context.Context) IStakeLeaderRewardClaimDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s stakeLeaderRewardClaimDo) ReadDB() IStakeLeaderRewardClaimDo {
	return s.Clauses(dbresolver.Read)
}

func (s stakeLeaderRewardClaimDo) WriteDB() IStakeLeaderRewardClaimDo {
	return s.Clauses(dbresolver.Write)
}

func (s stakeLeaderRewardClaimDo) Session(config *gorm.Session) IStakeLeaderRewardClaimDo {
	return s.withDO(s.DO.Session(config))
}

func (s stakeLeaderRewardClaimDo) Clauses(conds ...clause.Expression) IStakeLeaderRewardClaimDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s stakeLeaderRewardClaimDo) Returning(value interface{}, columns ...string) IStakeLeaderRewardClaimDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s stakeLeaderRewardClaimDo) Not(conds ...gen.Condition) IStakeLeaderRewardClaimDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s stakeLeaderRewardClaimDo) Or(conds ...gen.Condition) IStakeLeaderRewardClaimDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s stakeLeaderRewardClaimDo) Select(conds ...field.Expr) IStakeLeaderRewardClaimDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s stakeLeaderRewardClaimDo) Where(conds ...gen.Condition) IStakeLeaderRewardClaimDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s stakeLeaderRewardClaimDo) Order(conds ...field.Expr) IStakeLeaderRewardClaimDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s stakeLeaderRewardClaimDo) Distinct(cols ...field.Expr) IStakeLeaderRewardClaimDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s stakeLeaderRewardClaimDo) Omit(cols ...field.Expr) IStakeLeaderRewardClaimDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s stakeLeaderRewardClaimDo) Join(table schema.Tabler, on ...field.Expr) IStakeLeaderRewardClaimDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s stakeLeaderRewardClaimDo) LeftJoin(table schema.Tabler, on ...field.Expr) IStakeLeaderRewardClaimDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s stakeLeaderRewardClaimDo) RightJoin(table schema.Tabler, on ...field.Expr) IStakeLeaderRewardClaimDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s stakeLeaderRewardClaimDo) Group(cols ...field.Expr) IStakeLeaderRewardClaimDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s stakeLeaderRewardClaimDo) Having(conds ...gen.Condition) IStakeLeaderRewardClaimDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s stakeLeaderRewardClaimDo) Limit(limit int) IStakeLeaderRewardClaimDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s stakeLeaderRewardClaimDo) Offset(offset int) IStakeLeaderRewardClaimDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s stakeLeaderRewardClaimDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IStakeLeaderRewardClaimDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s stakeLeaderRewardClaimDo) Unscoped() IStakeLeaderRewardClaimDo {
	return s.withDO(s.DO.Unscoped())
}

func (s stakeLeaderRewardClaimDo) Create(values ...*model.StakeLeaderRewardClaim) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s stakeLeaderRewardClaimDo) CreateInBatches(values []*model.StakeLeaderRewardClaim, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s stakeLeaderRewardClaimDo) Save(values ...*model.StakeLeaderRewardClaim) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s stakeLeaderRewardClaimDo) First() (*model.StakeLeaderRewardClaim, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.StakeLeaderRewardClaim), nil
	}
}

func (s stakeLeaderRewardClaimDo) Take() (*model.StakeLeaderRewardClaim, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.StakeLeaderRewardClaim), nil
	}
}

func (s stakeLeaderRewardClaimDo) Last() (*model.StakeLeaderRewardClaim, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.StakeLeaderRewardClaim), nil
	}
}

func (s stakeLeaderRewardClaimDo) Find() ([]*model.StakeLeaderRewardClaim, error) {
	result, err := s.DO.Find()
	return result.([]*model.StakeLeaderRewardClaim), err
}

func (s stakeLeaderRewardClaimDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.StakeLeaderRewardClaim, err error) {
	buf := make([]*model.StakeLeaderRewardClaim, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s stakeLeaderRewardClaimDo) FindInBatches(result *[]*model.StakeLeaderRewardClaim, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s stakeLeaderRewardClaimDo) Attrs(attrs ...field.AssignExpr) IStakeLeaderRewardClaimDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s stakeLeaderRewardClaimDo) Assign(attrs ...field.AssignExpr) IStakeLeaderRewardClaimDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s stakeLeaderRewardClaimDo) Joins(fields ...field.RelationField) IStakeLeaderRewardClaimDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s stakeLeaderRewardClaimDo) Preload(fields ...field.RelationField) IStakeLeaderRewardClaimDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s stakeLeaderRewardClaimDo) FirstOrInit() (*model.StakeLeaderRewardClaim, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.StakeLeaderRewardClaim), nil
	}
}

func (s stakeLeaderRewardClaimDo) FirstOrCreate() (*model.StakeLeaderRewardClaim, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.StakeLeaderRewardClaim), nil
	}
}

func (s stakeLeaderRewardClaimDo) FindByPage(offset int, limit int) (result []*model.StakeLeaderRewardClaim, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s stakeLeaderRewardClaimDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s stakeLeaderRewardClaimDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s stakeLeaderRewardClaimDo) Delete(models ...*model.StakeLeaderRewardClaim) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *stakeLeaderRewardClaimDo) withDO(do gen.Dao) *stakeLeaderRewardClaimDo {
	s.DO = *do.(*gen.DO)
	return s
}
