// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"oshit-go/common/pkg/dal/model"
)

func newTakeTokenConfig(db *gorm.DB, opts ...gen.DOOption) takeTokenConfig {
	_takeTokenConfig := takeTokenConfig{}

	_takeTokenConfig.takeTokenConfigDo.UseDB(db, opts...)
	_takeTokenConfig.takeTokenConfigDo.UseModel(&model.TakeTokenConfig{})

	tableName := _takeTokenConfig.takeTokenConfigDo.TableName()
	_takeTokenConfig.ALL = field.NewAsterisk(tableName)
	_takeTokenConfig.RecordID = field.NewString(tableName, "record_id")
	_takeTokenConfig.InviteCode = field.NewString(tableName, "invite_code")
	_takeTokenConfig.RewardAccount = field.NewString(tableName, "reward_account")
	_takeTokenConfig.CostAccount = field.NewString(tableName, "cost_account")
	_takeTokenConfig.Amount = field.NewFloat64(tableName, "amount")
	_takeTokenConfig.InviteAmount = field.NewFloat64(tableName, "invite_amount")
	_takeTokenConfig.CostFeeRate = field.NewFloat64(tableName, "cost_fee_rate")
	_takeTokenConfig.MaxCostFee = field.NewFloat64(tableName, "max_cost_fee")
	_takeTokenConfig.IsDefault = field.NewBool(tableName, "is_default")
	_takeTokenConfig.RewardInviter = field.NewBool(tableName, "reward_inviter")
	_takeTokenConfig.Invited = field.NewBool(tableName, "invited")
	_takeTokenConfig.CreatedAt = field.NewTime(tableName, "created_at")
	_takeTokenConfig.UpdatedAt = field.NewTime(tableName, "updated_at")

	_takeTokenConfig.fillFieldMap()

	return _takeTokenConfig
}

type takeTokenConfig struct {
	takeTokenConfigDo takeTokenConfigDo

	ALL           field.Asterisk
	RecordID      field.String
	InviteCode    field.String
	RewardAccount field.String
	CostAccount   field.String
	Amount        field.Float64
	InviteAmount  field.Float64
	CostFeeRate   field.Float64
	MaxCostFee    field.Float64
	IsDefault     field.Bool
	RewardInviter field.Bool
	Invited       field.Bool
	CreatedAt     field.Time
	UpdatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (t takeTokenConfig) Table(newTableName string) *takeTokenConfig {
	t.takeTokenConfigDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t takeTokenConfig) As(alias string) *takeTokenConfig {
	t.takeTokenConfigDo.DO = *(t.takeTokenConfigDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *takeTokenConfig) updateTableName(table string) *takeTokenConfig {
	t.ALL = field.NewAsterisk(table)
	t.RecordID = field.NewString(table, "record_id")
	t.InviteCode = field.NewString(table, "invite_code")
	t.RewardAccount = field.NewString(table, "reward_account")
	t.CostAccount = field.NewString(table, "cost_account")
	t.Amount = field.NewFloat64(table, "amount")
	t.InviteAmount = field.NewFloat64(table, "invite_amount")
	t.CostFeeRate = field.NewFloat64(table, "cost_fee_rate")
	t.MaxCostFee = field.NewFloat64(table, "max_cost_fee")
	t.IsDefault = field.NewBool(table, "is_default")
	t.RewardInviter = field.NewBool(table, "reward_inviter")
	t.Invited = field.NewBool(table, "invited")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")

	t.fillFieldMap()

	return t
}

func (t *takeTokenConfig) WithContext(ctx context.Context) ITakeTokenConfigDo {
	return t.takeTokenConfigDo.WithContext(ctx)
}

func (t takeTokenConfig) TableName() string { return t.takeTokenConfigDo.TableName() }

func (t takeTokenConfig) Alias() string { return t.takeTokenConfigDo.Alias() }

func (t takeTokenConfig) Columns(cols ...field.Expr) gen.Columns {
	return t.takeTokenConfigDo.Columns(cols...)
}

func (t *takeTokenConfig) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *takeTokenConfig) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 13)
	t.fieldMap["record_id"] = t.RecordID
	t.fieldMap["invite_code"] = t.InviteCode
	t.fieldMap["reward_account"] = t.RewardAccount
	t.fieldMap["cost_account"] = t.CostAccount
	t.fieldMap["amount"] = t.Amount
	t.fieldMap["invite_amount"] = t.InviteAmount
	t.fieldMap["cost_fee_rate"] = t.CostFeeRate
	t.fieldMap["max_cost_fee"] = t.MaxCostFee
	t.fieldMap["is_default"] = t.IsDefault
	t.fieldMap["reward_inviter"] = t.RewardInviter
	t.fieldMap["invited"] = t.Invited
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
}

func (t takeTokenConfig) clone(db *gorm.DB) takeTokenConfig {
	t.takeTokenConfigDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t takeTokenConfig) replaceDB(db *gorm.DB) takeTokenConfig {
	t.takeTokenConfigDo.ReplaceDB(db)
	return t
}

type takeTokenConfigDo struct{ gen.DO }

type ITakeTokenConfigDo interface {
	gen.SubQuery
	Debug() ITakeTokenConfigDo
	WithContext(ctx context.Context) ITakeTokenConfigDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITakeTokenConfigDo
	WriteDB() ITakeTokenConfigDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITakeTokenConfigDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITakeTokenConfigDo
	Not(conds ...gen.Condition) ITakeTokenConfigDo
	Or(conds ...gen.Condition) ITakeTokenConfigDo
	Select(conds ...field.Expr) ITakeTokenConfigDo
	Where(conds ...gen.Condition) ITakeTokenConfigDo
	Order(conds ...field.Expr) ITakeTokenConfigDo
	Distinct(cols ...field.Expr) ITakeTokenConfigDo
	Omit(cols ...field.Expr) ITakeTokenConfigDo
	Join(table schema.Tabler, on ...field.Expr) ITakeTokenConfigDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITakeTokenConfigDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITakeTokenConfigDo
	Group(cols ...field.Expr) ITakeTokenConfigDo
	Having(conds ...gen.Condition) ITakeTokenConfigDo
	Limit(limit int) ITakeTokenConfigDo
	Offset(offset int) ITakeTokenConfigDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITakeTokenConfigDo
	Unscoped() ITakeTokenConfigDo
	Create(values ...*model.TakeTokenConfig) error
	CreateInBatches(values []*model.TakeTokenConfig, batchSize int) error
	Save(values ...*model.TakeTokenConfig) error
	First() (*model.TakeTokenConfig, error)
	Take() (*model.TakeTokenConfig, error)
	Last() (*model.TakeTokenConfig, error)
	Find() ([]*model.TakeTokenConfig, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TakeTokenConfig, err error)
	FindInBatches(result *[]*model.TakeTokenConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TakeTokenConfig) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITakeTokenConfigDo
	Assign(attrs ...field.AssignExpr) ITakeTokenConfigDo
	Joins(fields ...field.RelationField) ITakeTokenConfigDo
	Preload(fields ...field.RelationField) ITakeTokenConfigDo
	FirstOrInit() (*model.TakeTokenConfig, error)
	FirstOrCreate() (*model.TakeTokenConfig, error)
	FindByPage(offset int, limit int) (result []*model.TakeTokenConfig, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITakeTokenConfigDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t takeTokenConfigDo) Debug() ITakeTokenConfigDo {
	return t.withDO(t.DO.Debug())
}

func (t takeTokenConfigDo) WithContext(ctx context.Context) ITakeTokenConfigDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t takeTokenConfigDo) ReadDB() ITakeTokenConfigDo {
	return t.Clauses(dbresolver.Read)
}

func (t takeTokenConfigDo) WriteDB() ITakeTokenConfigDo {
	return t.Clauses(dbresolver.Write)
}

func (t takeTokenConfigDo) Session(config *gorm.Session) ITakeTokenConfigDo {
	return t.withDO(t.DO.Session(config))
}

func (t takeTokenConfigDo) Clauses(conds ...clause.Expression) ITakeTokenConfigDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t takeTokenConfigDo) Returning(value interface{}, columns ...string) ITakeTokenConfigDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t takeTokenConfigDo) Not(conds ...gen.Condition) ITakeTokenConfigDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t takeTokenConfigDo) Or(conds ...gen.Condition) ITakeTokenConfigDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t takeTokenConfigDo) Select(conds ...field.Expr) ITakeTokenConfigDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t takeTokenConfigDo) Where(conds ...gen.Condition) ITakeTokenConfigDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t takeTokenConfigDo) Order(conds ...field.Expr) ITakeTokenConfigDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t takeTokenConfigDo) Distinct(cols ...field.Expr) ITakeTokenConfigDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t takeTokenConfigDo) Omit(cols ...field.Expr) ITakeTokenConfigDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t takeTokenConfigDo) Join(table schema.Tabler, on ...field.Expr) ITakeTokenConfigDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t takeTokenConfigDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITakeTokenConfigDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t takeTokenConfigDo) RightJoin(table schema.Tabler, on ...field.Expr) ITakeTokenConfigDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t takeTokenConfigDo) Group(cols ...field.Expr) ITakeTokenConfigDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t takeTokenConfigDo) Having(conds ...gen.Condition) ITakeTokenConfigDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t takeTokenConfigDo) Limit(limit int) ITakeTokenConfigDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t takeTokenConfigDo) Offset(offset int) ITakeTokenConfigDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t takeTokenConfigDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITakeTokenConfigDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t takeTokenConfigDo) Unscoped() ITakeTokenConfigDo {
	return t.withDO(t.DO.Unscoped())
}

func (t takeTokenConfigDo) Create(values ...*model.TakeTokenConfig) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t takeTokenConfigDo) CreateInBatches(values []*model.TakeTokenConfig, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t takeTokenConfigDo) Save(values ...*model.TakeTokenConfig) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t takeTokenConfigDo) First() (*model.TakeTokenConfig, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TakeTokenConfig), nil
	}
}

func (t takeTokenConfigDo) Take() (*model.TakeTokenConfig, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TakeTokenConfig), nil
	}
}

func (t takeTokenConfigDo) Last() (*model.TakeTokenConfig, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TakeTokenConfig), nil
	}
}

func (t takeTokenConfigDo) Find() ([]*model.TakeTokenConfig, error) {
	result, err := t.DO.Find()
	return result.([]*model.TakeTokenConfig), err
}

func (t takeTokenConfigDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TakeTokenConfig, err error) {
	buf := make([]*model.TakeTokenConfig, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t takeTokenConfigDo) FindInBatches(result *[]*model.TakeTokenConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t takeTokenConfigDo) Attrs(attrs ...field.AssignExpr) ITakeTokenConfigDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t takeTokenConfigDo) Assign(attrs ...field.AssignExpr) ITakeTokenConfigDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t takeTokenConfigDo) Joins(fields ...field.RelationField) ITakeTokenConfigDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t takeTokenConfigDo) Preload(fields ...field.RelationField) ITakeTokenConfigDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t takeTokenConfigDo) FirstOrInit() (*model.TakeTokenConfig, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TakeTokenConfig), nil
	}
}

func (t takeTokenConfigDo) FirstOrCreate() (*model.TakeTokenConfig, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TakeTokenConfig), nil
	}
}

func (t takeTokenConfigDo) FindByPage(offset int, limit int) (result []*model.TakeTokenConfig, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t takeTokenConfigDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t takeTokenConfigDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t takeTokenConfigDo) Delete(models ...*model.TakeTokenConfig) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *takeTokenConfigDo) withDO(do gen.Dao) *takeTokenConfigDo {
	t.DO = *do.(*gen.DO)
	return t
}
