// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"oshit-go/common/pkg/dal/model"
)

func newUserDailyExchangeQuota(db *gorm.DB, opts ...gen.DOOption) userDailyExchangeQuota {
	_userDailyExchangeQuota := userDailyExchangeQuota{}

	_userDailyExchangeQuota.userDailyExchangeQuotaDo.UseDB(db, opts...)
	_userDailyExchangeQuota.userDailyExchangeQuotaDo.UseModel(&model.UserDailyExchangeQuota{})

	tableName := _userDailyExchangeQuota.userDailyExchangeQuotaDo.TableName()
	_userDailyExchangeQuota.ALL = field.NewAsterisk(tableName)
	_userDailyExchangeQuota.ID = field.NewInt64(tableName, "id")
	_userDailyExchangeQuota.UserID = field.NewString(tableName, "user_id")
	_userDailyExchangeQuota.QuotaDate = field.NewTime(tableName, "quota_date")
	_userDailyExchangeQuota.MaxQuota = field.NewFloat64(tableName, "max_quota")
	_userDailyExchangeQuota.FrozenQuota = field.NewFloat64(tableName, "frozen_quota")
	_userDailyExchangeQuota.AvailableQuota = field.NewFloat64(tableName, "available_quota")
	_userDailyExchangeQuota.CreatedAt = field.NewTime(tableName, "created_at")
	_userDailyExchangeQuota.UpdatedAt = field.NewTime(tableName, "updated_at")

	_userDailyExchangeQuota.fillFieldMap()

	return _userDailyExchangeQuota
}

type userDailyExchangeQuota struct {
	userDailyExchangeQuotaDo userDailyExchangeQuotaDo

	ALL            field.Asterisk
	ID             field.Int64
	UserID         field.String
	QuotaDate      field.Time
	MaxQuota       field.Float64
	FrozenQuota    field.Float64
	AvailableQuota field.Float64
	CreatedAt      field.Time
	UpdatedAt      field.Time

	fieldMap map[string]field.Expr
}

func (u userDailyExchangeQuota) Table(newTableName string) *userDailyExchangeQuota {
	u.userDailyExchangeQuotaDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userDailyExchangeQuota) As(alias string) *userDailyExchangeQuota {
	u.userDailyExchangeQuotaDo.DO = *(u.userDailyExchangeQuotaDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userDailyExchangeQuota) updateTableName(table string) *userDailyExchangeQuota {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewInt64(table, "id")
	u.UserID = field.NewString(table, "user_id")
	u.QuotaDate = field.NewTime(table, "quota_date")
	u.MaxQuota = field.NewFloat64(table, "max_quota")
	u.FrozenQuota = field.NewFloat64(table, "frozen_quota")
	u.AvailableQuota = field.NewFloat64(table, "available_quota")
	u.CreatedAt = field.NewTime(table, "created_at")
	u.UpdatedAt = field.NewTime(table, "updated_at")

	u.fillFieldMap()

	return u
}

func (u *userDailyExchangeQuota) WithContext(ctx context.Context) IUserDailyExchangeQuotaDo {
	return u.userDailyExchangeQuotaDo.WithContext(ctx)
}

func (u userDailyExchangeQuota) TableName() string { return u.userDailyExchangeQuotaDo.TableName() }

func (u userDailyExchangeQuota) Alias() string { return u.userDailyExchangeQuotaDo.Alias() }

func (u userDailyExchangeQuota) Columns(cols ...field.Expr) gen.Columns {
	return u.userDailyExchangeQuotaDo.Columns(cols...)
}

func (u *userDailyExchangeQuota) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userDailyExchangeQuota) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 8)
	u.fieldMap["id"] = u.ID
	u.fieldMap["user_id"] = u.UserID
	u.fieldMap["quota_date"] = u.QuotaDate
	u.fieldMap["max_quota"] = u.MaxQuota
	u.fieldMap["frozen_quota"] = u.FrozenQuota
	u.fieldMap["available_quota"] = u.AvailableQuota
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["updated_at"] = u.UpdatedAt
}

func (u userDailyExchangeQuota) clone(db *gorm.DB) userDailyExchangeQuota {
	u.userDailyExchangeQuotaDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userDailyExchangeQuota) replaceDB(db *gorm.DB) userDailyExchangeQuota {
	u.userDailyExchangeQuotaDo.ReplaceDB(db)
	return u
}

type userDailyExchangeQuotaDo struct{ gen.DO }

type IUserDailyExchangeQuotaDo interface {
	gen.SubQuery
	Debug() IUserDailyExchangeQuotaDo
	WithContext(ctx context.Context) IUserDailyExchangeQuotaDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUserDailyExchangeQuotaDo
	WriteDB() IUserDailyExchangeQuotaDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUserDailyExchangeQuotaDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUserDailyExchangeQuotaDo
	Not(conds ...gen.Condition) IUserDailyExchangeQuotaDo
	Or(conds ...gen.Condition) IUserDailyExchangeQuotaDo
	Select(conds ...field.Expr) IUserDailyExchangeQuotaDo
	Where(conds ...gen.Condition) IUserDailyExchangeQuotaDo
	Order(conds ...field.Expr) IUserDailyExchangeQuotaDo
	Distinct(cols ...field.Expr) IUserDailyExchangeQuotaDo
	Omit(cols ...field.Expr) IUserDailyExchangeQuotaDo
	Join(table schema.Tabler, on ...field.Expr) IUserDailyExchangeQuotaDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUserDailyExchangeQuotaDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUserDailyExchangeQuotaDo
	Group(cols ...field.Expr) IUserDailyExchangeQuotaDo
	Having(conds ...gen.Condition) IUserDailyExchangeQuotaDo
	Limit(limit int) IUserDailyExchangeQuotaDo
	Offset(offset int) IUserDailyExchangeQuotaDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUserDailyExchangeQuotaDo
	Unscoped() IUserDailyExchangeQuotaDo
	Create(values ...*model.UserDailyExchangeQuota) error
	CreateInBatches(values []*model.UserDailyExchangeQuota, batchSize int) error
	Save(values ...*model.UserDailyExchangeQuota) error
	First() (*model.UserDailyExchangeQuota, error)
	Take() (*model.UserDailyExchangeQuota, error)
	Last() (*model.UserDailyExchangeQuota, error)
	Find() ([]*model.UserDailyExchangeQuota, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserDailyExchangeQuota, err error)
	FindInBatches(result *[]*model.UserDailyExchangeQuota, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.UserDailyExchangeQuota) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUserDailyExchangeQuotaDo
	Assign(attrs ...field.AssignExpr) IUserDailyExchangeQuotaDo
	Joins(fields ...field.RelationField) IUserDailyExchangeQuotaDo
	Preload(fields ...field.RelationField) IUserDailyExchangeQuotaDo
	FirstOrInit() (*model.UserDailyExchangeQuota, error)
	FirstOrCreate() (*model.UserDailyExchangeQuota, error)
	FindByPage(offset int, limit int) (result []*model.UserDailyExchangeQuota, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUserDailyExchangeQuotaDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u userDailyExchangeQuotaDo) Debug() IUserDailyExchangeQuotaDo {
	return u.withDO(u.DO.Debug())
}

func (u userDailyExchangeQuotaDo) WithContext(ctx context.Context) IUserDailyExchangeQuotaDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userDailyExchangeQuotaDo) ReadDB() IUserDailyExchangeQuotaDo {
	return u.Clauses(dbresolver.Read)
}

func (u userDailyExchangeQuotaDo) WriteDB() IUserDailyExchangeQuotaDo {
	return u.Clauses(dbresolver.Write)
}

func (u userDailyExchangeQuotaDo) Session(config *gorm.Session) IUserDailyExchangeQuotaDo {
	return u.withDO(u.DO.Session(config))
}

func (u userDailyExchangeQuotaDo) Clauses(conds ...clause.Expression) IUserDailyExchangeQuotaDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userDailyExchangeQuotaDo) Returning(value interface{}, columns ...string) IUserDailyExchangeQuotaDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userDailyExchangeQuotaDo) Not(conds ...gen.Condition) IUserDailyExchangeQuotaDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userDailyExchangeQuotaDo) Or(conds ...gen.Condition) IUserDailyExchangeQuotaDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userDailyExchangeQuotaDo) Select(conds ...field.Expr) IUserDailyExchangeQuotaDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userDailyExchangeQuotaDo) Where(conds ...gen.Condition) IUserDailyExchangeQuotaDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userDailyExchangeQuotaDo) Order(conds ...field.Expr) IUserDailyExchangeQuotaDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userDailyExchangeQuotaDo) Distinct(cols ...field.Expr) IUserDailyExchangeQuotaDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userDailyExchangeQuotaDo) Omit(cols ...field.Expr) IUserDailyExchangeQuotaDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userDailyExchangeQuotaDo) Join(table schema.Tabler, on ...field.Expr) IUserDailyExchangeQuotaDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userDailyExchangeQuotaDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUserDailyExchangeQuotaDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userDailyExchangeQuotaDo) RightJoin(table schema.Tabler, on ...field.Expr) IUserDailyExchangeQuotaDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userDailyExchangeQuotaDo) Group(cols ...field.Expr) IUserDailyExchangeQuotaDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userDailyExchangeQuotaDo) Having(conds ...gen.Condition) IUserDailyExchangeQuotaDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userDailyExchangeQuotaDo) Limit(limit int) IUserDailyExchangeQuotaDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userDailyExchangeQuotaDo) Offset(offset int) IUserDailyExchangeQuotaDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userDailyExchangeQuotaDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUserDailyExchangeQuotaDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userDailyExchangeQuotaDo) Unscoped() IUserDailyExchangeQuotaDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userDailyExchangeQuotaDo) Create(values ...*model.UserDailyExchangeQuota) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userDailyExchangeQuotaDo) CreateInBatches(values []*model.UserDailyExchangeQuota, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userDailyExchangeQuotaDo) Save(values ...*model.UserDailyExchangeQuota) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userDailyExchangeQuotaDo) First() (*model.UserDailyExchangeQuota, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserDailyExchangeQuota), nil
	}
}

func (u userDailyExchangeQuotaDo) Take() (*model.UserDailyExchangeQuota, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserDailyExchangeQuota), nil
	}
}

func (u userDailyExchangeQuotaDo) Last() (*model.UserDailyExchangeQuota, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserDailyExchangeQuota), nil
	}
}

func (u userDailyExchangeQuotaDo) Find() ([]*model.UserDailyExchangeQuota, error) {
	result, err := u.DO.Find()
	return result.([]*model.UserDailyExchangeQuota), err
}

func (u userDailyExchangeQuotaDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserDailyExchangeQuota, err error) {
	buf := make([]*model.UserDailyExchangeQuota, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userDailyExchangeQuotaDo) FindInBatches(result *[]*model.UserDailyExchangeQuota, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userDailyExchangeQuotaDo) Attrs(attrs ...field.AssignExpr) IUserDailyExchangeQuotaDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userDailyExchangeQuotaDo) Assign(attrs ...field.AssignExpr) IUserDailyExchangeQuotaDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userDailyExchangeQuotaDo) Joins(fields ...field.RelationField) IUserDailyExchangeQuotaDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userDailyExchangeQuotaDo) Preload(fields ...field.RelationField) IUserDailyExchangeQuotaDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userDailyExchangeQuotaDo) FirstOrInit() (*model.UserDailyExchangeQuota, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserDailyExchangeQuota), nil
	}
}

func (u userDailyExchangeQuotaDo) FirstOrCreate() (*model.UserDailyExchangeQuota, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserDailyExchangeQuota), nil
	}
}

func (u userDailyExchangeQuotaDo) FindByPage(offset int, limit int) (result []*model.UserDailyExchangeQuota, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userDailyExchangeQuotaDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userDailyExchangeQuotaDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userDailyExchangeQuotaDo) Delete(models ...*model.UserDailyExchangeQuota) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userDailyExchangeQuotaDo) withDO(do gen.Dao) *userDailyExchangeQuotaDo {
	u.DO = *do.(*gen.DO)
	return u
}
