// account.proto
syntax = "proto3";

package account; // 包名，在Go中会作为生成代码的包名

option go_package = ".;account"; // 非常重要！指定生成Go代码的导入路径和包别名

// 定义请求和响应消息
message GetUserRequest {
  int64 user_id = 1;
}

message User {
  int64 id = 1;
  string username = 2;
  string email = 3;
}

message CreateUserRequest {
  string username = 1;
  string email = 2;
  string password = 3;
}

message ValidateTokenRequest {
  string token = 1;
}

// 定义服务接口
service AccountService {
  rpc GetUser (GetUserRequest) returns (User) {}
  rpc CreateUser (CreateUserRequest) returns (User) {}
  rpc ValidateToken (ValidateTokenRequest) returns (User) {}
}