syntax = "proto3";

package base;

option go_package = ".;base";

// ---- 共享消息 ----

message FeeDetail {
  uint64 low     = 1;
  uint64 medium  = 2;
  uint64 high    = 3;
  uint64 extreme = 4;
}

// ---- Fee ----

message GetFeeToleranceReq {}
message GetFeeToleranceRsp {
  double max_fee_less = 1;
  uint64 max_fee      = 2;
}

message GetPriorityFeeReq {}
message GetPriorityFeeRsp {
  FeeDetail per_compute_unit = 1;
  FeeDetail per_transaction  = 2;
}

message GetInstUnitsReq {}
message GetInstUnitsRsp {
  uint64 mini_rent          = 1;
  uint64 associated_account = 2;
  uint64 transfer_checked   = 3;
  uint64 memo               = 4;
}

// ---- Price ----

message GetTokenQuoteSOLPriceReq {}
message GetTokenQuoteUSDTPriceReq {}
message GetUSDTQuoteSOLPriceReq {}
message PriceQuoteRsp {
  double price = 1;
}

// ---- Tx ----

message SendTransactionReq {
  string encoded_tx  = 1;
  string service     = 2;
  string sub_service = 3;
}
message SendTransactionRsp {
  string record_id = 1;
  string tx_id     = 2;
}

// ---- Service ----

service BaseService {
  rpc GetFeeTolerance        (GetFeeToleranceReq)        returns (GetFeeToleranceRsp)        {}
  rpc GetPriorityFee         (GetPriorityFeeReq)         returns (GetPriorityFeeRsp)         {}
  rpc GetInstUnits           (GetInstUnitsReq)           returns (GetInstUnitsRsp)           {}
  rpc GetTokenQuoteSOLPrice  (GetTokenQuoteSOLPriceReq)  returns (PriceQuoteRsp)             {}
  rpc GetTokenQuoteUSDTPrice (GetTokenQuoteUSDTPriceReq) returns (PriceQuoteRsp)             {}
  rpc GetUSDTQuoteSOLPrice   (GetUSDTQuoteSOLPriceReq)   returns (PriceQuoteRsp)             {}
  rpc SendTransaction (SendTransactionReq) returns (SendTransactionRsp) {}
}
