// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"oshit-go/app/exchange/dal/model"
)

func newTradeOrder(db *gorm.DB, opts ...gen.DOOption) tradeOrder {
	_tradeOrder := tradeOrder{}

	_tradeOrder.tradeOrderDo.UseDB(db, opts...)
	_tradeOrder.tradeOrderDo.UseModel(&model.TradeOrder{})

	tableName := _tradeOrder.tradeOrderDo.TableName()
	_tradeOrder.ALL = field.NewAsterisk(tableName)
	_tradeOrder.ID = field.NewInt64(tableName, "id")
	_tradeOrder.UserID = field.NewInt64(tableName, "user_id")
	_tradeOrder.OrderNo = field.NewString(tableName, "order_no")
	_tradeOrder.Amount = field.NewFloat64(tableName, "amount")
	_tradeOrder.Status = field.NewInt16(tableName, "status")
	_tradeOrder.CreatedAt = field.NewTime(tableName, "created_at")
	_tradeOrder.UpdatedAt = field.NewTime(tableName, "updated_at")

	_tradeOrder.fillFieldMap()

	return _tradeOrder
}

type tradeOrder struct {
	tradeOrderDo tradeOrderDo

	ALL       field.Asterisk
	ID        field.Int64   // 自增主键
	UserID    field.Int64   // 关联account.t_user_info的id
	OrderNo   field.String  // 订单编号（唯一）
	Amount    field.Float64 // 订单金额（保留2位小数）
	Status    field.Int16   // 订单状态：0-待支付 1-已支付 2-已取消 3-已完成
	CreatedAt field.Time    // 创建时间
	UpdatedAt field.Time    // 更新时间

	fieldMap map[string]field.Expr
}

func (t tradeOrder) Table(newTableName string) *tradeOrder {
	t.tradeOrderDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tradeOrder) As(alias string) *tradeOrder {
	t.tradeOrderDo.DO = *(t.tradeOrderDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tradeOrder) updateTableName(table string) *tradeOrder {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.UserID = field.NewInt64(table, "user_id")
	t.OrderNo = field.NewString(table, "order_no")
	t.Amount = field.NewFloat64(table, "amount")
	t.Status = field.NewInt16(table, "status")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")

	t.fillFieldMap()

	return t
}

func (t *tradeOrder) WithContext(ctx context.Context) ITradeOrderDo {
	return t.tradeOrderDo.WithContext(ctx)
}

func (t tradeOrder) TableName() string { return t.tradeOrderDo.TableName() }

func (t tradeOrder) Alias() string { return t.tradeOrderDo.Alias() }

func (t tradeOrder) Columns(cols ...field.Expr) gen.Columns { return t.tradeOrderDo.Columns(cols...) }

func (t *tradeOrder) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tradeOrder) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 7)
	t.fieldMap["id"] = t.ID
	t.fieldMap["user_id"] = t.UserID
	t.fieldMap["order_no"] = t.OrderNo
	t.fieldMap["amount"] = t.Amount
	t.fieldMap["status"] = t.Status
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
}

func (t tradeOrder) clone(db *gorm.DB) tradeOrder {
	t.tradeOrderDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tradeOrder) replaceDB(db *gorm.DB) tradeOrder {
	t.tradeOrderDo.ReplaceDB(db)
	return t
}

type tradeOrderDo struct{ gen.DO }

type ITradeOrderDo interface {
	gen.SubQuery
	Debug() ITradeOrderDo
	WithContext(ctx context.Context) ITradeOrderDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITradeOrderDo
	WriteDB() ITradeOrderDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITradeOrderDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITradeOrderDo
	Not(conds ...gen.Condition) ITradeOrderDo
	Or(conds ...gen.Condition) ITradeOrderDo
	Select(conds ...field.Expr) ITradeOrderDo
	Where(conds ...gen.Condition) ITradeOrderDo
	Order(conds ...field.Expr) ITradeOrderDo
	Distinct(cols ...field.Expr) ITradeOrderDo
	Omit(cols ...field.Expr) ITradeOrderDo
	Join(table schema.Tabler, on ...field.Expr) ITradeOrderDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITradeOrderDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITradeOrderDo
	Group(cols ...field.Expr) ITradeOrderDo
	Having(conds ...gen.Condition) ITradeOrderDo
	Limit(limit int) ITradeOrderDo
	Offset(offset int) ITradeOrderDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITradeOrderDo
	Unscoped() ITradeOrderDo
	Create(values ...*model.TradeOrder) error
	CreateInBatches(values []*model.TradeOrder, batchSize int) error
	Save(values ...*model.TradeOrder) error
	First() (*model.TradeOrder, error)
	Take() (*model.TradeOrder, error)
	Last() (*model.TradeOrder, error)
	Find() ([]*model.TradeOrder, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TradeOrder, err error)
	FindInBatches(result *[]*model.TradeOrder, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TradeOrder) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITradeOrderDo
	Assign(attrs ...field.AssignExpr) ITradeOrderDo
	Joins(fields ...field.RelationField) ITradeOrderDo
	Preload(fields ...field.RelationField) ITradeOrderDo
	FirstOrInit() (*model.TradeOrder, error)
	FirstOrCreate() (*model.TradeOrder, error)
	FindByPage(offset int, limit int) (result []*model.TradeOrder, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITradeOrderDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tradeOrderDo) Debug() ITradeOrderDo {
	return t.withDO(t.DO.Debug())
}

func (t tradeOrderDo) WithContext(ctx context.Context) ITradeOrderDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tradeOrderDo) ReadDB() ITradeOrderDo {
	return t.Clauses(dbresolver.Read)
}

func (t tradeOrderDo) WriteDB() ITradeOrderDo {
	return t.Clauses(dbresolver.Write)
}

func (t tradeOrderDo) Session(config *gorm.Session) ITradeOrderDo {
	return t.withDO(t.DO.Session(config))
}

func (t tradeOrderDo) Clauses(conds ...clause.Expression) ITradeOrderDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tradeOrderDo) Returning(value interface{}, columns ...string) ITradeOrderDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tradeOrderDo) Not(conds ...gen.Condition) ITradeOrderDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tradeOrderDo) Or(conds ...gen.Condition) ITradeOrderDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tradeOrderDo) Select(conds ...field.Expr) ITradeOrderDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tradeOrderDo) Where(conds ...gen.Condition) ITradeOrderDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tradeOrderDo) Order(conds ...field.Expr) ITradeOrderDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tradeOrderDo) Distinct(cols ...field.Expr) ITradeOrderDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tradeOrderDo) Omit(cols ...field.Expr) ITradeOrderDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tradeOrderDo) Join(table schema.Tabler, on ...field.Expr) ITradeOrderDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tradeOrderDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITradeOrderDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tradeOrderDo) RightJoin(table schema.Tabler, on ...field.Expr) ITradeOrderDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tradeOrderDo) Group(cols ...field.Expr) ITradeOrderDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tradeOrderDo) Having(conds ...gen.Condition) ITradeOrderDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tradeOrderDo) Limit(limit int) ITradeOrderDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tradeOrderDo) Offset(offset int) ITradeOrderDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tradeOrderDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITradeOrderDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tradeOrderDo) Unscoped() ITradeOrderDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tradeOrderDo) Create(values ...*model.TradeOrder) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tradeOrderDo) CreateInBatches(values []*model.TradeOrder, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tradeOrderDo) Save(values ...*model.TradeOrder) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tradeOrderDo) First() (*model.TradeOrder, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TradeOrder), nil
	}
}

func (t tradeOrderDo) Take() (*model.TradeOrder, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TradeOrder), nil
	}
}

func (t tradeOrderDo) Last() (*model.TradeOrder, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TradeOrder), nil
	}
}

func (t tradeOrderDo) Find() ([]*model.TradeOrder, error) {
	result, err := t.DO.Find()
	return result.([]*model.TradeOrder), err
}

func (t tradeOrderDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TradeOrder, err error) {
	buf := make([]*model.TradeOrder, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tradeOrderDo) FindInBatches(result *[]*model.TradeOrder, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tradeOrderDo) Attrs(attrs ...field.AssignExpr) ITradeOrderDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tradeOrderDo) Assign(attrs ...field.AssignExpr) ITradeOrderDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tradeOrderDo) Joins(fields ...field.RelationField) ITradeOrderDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tradeOrderDo) Preload(fields ...field.RelationField) ITradeOrderDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tradeOrderDo) FirstOrInit() (*model.TradeOrder, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TradeOrder), nil
	}
}

func (t tradeOrderDo) FirstOrCreate() (*model.TradeOrder, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TradeOrder), nil
	}
}

func (t tradeOrderDo) FindByPage(offset int, limit int) (result []*model.TradeOrder, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tradeOrderDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tradeOrderDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tradeOrderDo) Delete(models ...*model.TradeOrder) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tradeOrderDo) withDO(do gen.Dao) *tradeOrderDo {
	t.DO = *do.(*gen.DO)
	return t
}
