app:
  name: "reward-api"
  port: 1200

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "oshit_db"
  sslmode: "disable"

redis:
  addr: "localhost"
  port: 6379
  password: ""
  db: 0

kafka:
  brokers:
    - "localhost:9092"
  consumer:
    group_id: "reward-service"
    topics:
      - "ServiceTransaction"

nacos:
  host: "127.0.0.1"
  username: "nacos"
  password: "lJPQwjjO9k"
  subscribe_configs:
    base_runtime:
      data_id: "base-runtime.yaml"
      group: "oshit-go"
    reward_runtime:
      data_id: "reward-runtime.yaml"
      group: "oshit-go"
