// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                   = new(Query)
	AwsConfig           *awsConfig
	ChainConfig         *chainConfig
	FeeStatistics       *feeStatistics
	FeeTolerance        *feeTolerance
	InviteRelation      *inviteRelation
	NativeAccountInfo   *nativeAccountInfo
	QnFee               *qnFee
	ServiceInfo         *serviceInfo
	ServiceTx           *serviceTx
	SystemConfig        *systemConfig
	TokenConfig         *tokenConfig
	UserWalletRpcConfig *userWalletRpcConfig
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	AwsConfig = &Q.AwsConfig
	ChainConfig = &Q.ChainConfig
	FeeStatistics = &Q.FeeStatistics
	FeeTolerance = &Q.FeeTolerance
	InviteRelation = &Q.InviteRelation
	NativeAccountInfo = &Q.NativeAccountInfo
	QnFee = &Q.QnFee
	ServiceInfo = &Q.ServiceInfo
	ServiceTx = &Q.ServiceTx
	SystemConfig = &Q.SystemConfig
	TokenConfig = &Q.TokenConfig
	UserWalletRpcConfig = &Q.UserWalletRpcConfig
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                  db,
		AwsConfig:           newAwsConfig(db, opts...),
		ChainConfig:         newChainConfig(db, opts...),
		FeeStatistics:       newFeeStatistics(db, opts...),
		FeeTolerance:        newFeeTolerance(db, opts...),
		InviteRelation:      newInviteRelation(db, opts...),
		NativeAccountInfo:   newNativeAccountInfo(db, opts...),
		QnFee:               newQnFee(db, opts...),
		ServiceInfo:         newServiceInfo(db, opts...),
		ServiceTx:           newServiceTx(db, opts...),
		SystemConfig:        newSystemConfig(db, opts...),
		TokenConfig:         newTokenConfig(db, opts...),
		UserWalletRpcConfig: newUserWalletRpcConfig(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	AwsConfig           awsConfig
	ChainConfig         chainConfig
	FeeStatistics       feeStatistics
	FeeTolerance        feeTolerance
	InviteRelation      inviteRelation
	NativeAccountInfo   nativeAccountInfo
	QnFee               qnFee
	ServiceInfo         serviceInfo
	ServiceTx           serviceTx
	SystemConfig        systemConfig
	TokenConfig         tokenConfig
	UserWalletRpcConfig userWalletRpcConfig
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                  db,
		AwsConfig:           q.AwsConfig.clone(db),
		ChainConfig:         q.ChainConfig.clone(db),
		FeeStatistics:       q.FeeStatistics.clone(db),
		FeeTolerance:        q.FeeTolerance.clone(db),
		InviteRelation:      q.InviteRelation.clone(db),
		NativeAccountInfo:   q.NativeAccountInfo.clone(db),
		QnFee:               q.QnFee.clone(db),
		ServiceInfo:         q.ServiceInfo.clone(db),
		ServiceTx:           q.ServiceTx.clone(db),
		SystemConfig:        q.SystemConfig.clone(db),
		TokenConfig:         q.TokenConfig.clone(db),
		UserWalletRpcConfig: q.UserWalletRpcConfig.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                  db,
		AwsConfig:           q.AwsConfig.replaceDB(db),
		ChainConfig:         q.ChainConfig.replaceDB(db),
		FeeStatistics:       q.FeeStatistics.replaceDB(db),
		FeeTolerance:        q.FeeTolerance.replaceDB(db),
		InviteRelation:      q.InviteRelation.replaceDB(db),
		NativeAccountInfo:   q.NativeAccountInfo.replaceDB(db),
		QnFee:               q.QnFee.replaceDB(db),
		ServiceInfo:         q.ServiceInfo.replaceDB(db),
		ServiceTx:           q.ServiceTx.replaceDB(db),
		SystemConfig:        q.SystemConfig.replaceDB(db),
		TokenConfig:         q.TokenConfig.replaceDB(db),
		UserWalletRpcConfig: q.UserWalletRpcConfig.replaceDB(db),
	}
}

type queryCtx struct {
	AwsConfig           IAwsConfigDo
	ChainConfig         IChainConfigDo
	FeeStatistics       IFeeStatisticsDo
	FeeTolerance        IFeeToleranceDo
	InviteRelation      IInviteRelationDo
	NativeAccountInfo   INativeAccountInfoDo
	QnFee               IQnFeeDo
	ServiceInfo         IServiceInfoDo
	ServiceTx           IServiceTxDo
	SystemConfig        ISystemConfigDo
	TokenConfig         ITokenConfigDo
	UserWalletRpcConfig IUserWalletRpcConfigDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		AwsConfig:           q.AwsConfig.WithContext(ctx),
		ChainConfig:         q.ChainConfig.WithContext(ctx),
		FeeStatistics:       q.FeeStatistics.WithContext(ctx),
		FeeTolerance:        q.FeeTolerance.WithContext(ctx),
		InviteRelation:      q.InviteRelation.WithContext(ctx),
		NativeAccountInfo:   q.NativeAccountInfo.WithContext(ctx),
		QnFee:               q.QnFee.WithContext(ctx),
		ServiceInfo:         q.ServiceInfo.WithContext(ctx),
		ServiceTx:           q.ServiceTx.WithContext(ctx),
		SystemConfig:        q.SystemConfig.WithContext(ctx),
		TokenConfig:         q.TokenConfig.WithContext(ctx),
		UserWalletRpcConfig: q.UserWalletRpcConfig.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
