// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"oshit-go/app/base/dal/model"
)

func newQnFee(db *gorm.DB, opts ...gen.DOOption) qnFee {
	_qnFee := qnFee{}

	_qnFee.qnFeeDo.UseDB(db, opts...)
	_qnFee.qnFeeDo.UseModel(&model.QnFee{})

	tableName := _qnFee.qnFeeDo.TableName()
	_qnFee.ALL = field.NewAsterisk(tableName)
	_qnFee.ID = field.NewInt32(tableName, "id")
	_qnFee.Slot = field.NewInt64(tableName, "slot")
	_qnFee.LowAvg = field.NewFloat64(tableName, "low_avg")
	_qnFee.MediumAvg = field.NewFloat64(tableName, "medium_avg")
	_qnFee.HighAvg = field.NewFloat64(tableName, "high_avg")
	_qnFee.CreatedAt = field.NewTime(tableName, "created_at")
	_qnFee.UpdatedAt = field.NewTime(tableName, "updated_at")

	_qnFee.fillFieldMap()

	return _qnFee
}

type qnFee struct {
	qnFeeDo qnFeeDo

	ALL       field.Asterisk
	ID        field.Int32
	Slot      field.Int64
	LowAvg    field.Float64
	MediumAvg field.Float64
	HighAvg   field.Float64
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (q qnFee) Table(newTableName string) *qnFee {
	q.qnFeeDo.UseTable(newTableName)
	return q.updateTableName(newTableName)
}

func (q qnFee) As(alias string) *qnFee {
	q.qnFeeDo.DO = *(q.qnFeeDo.As(alias).(*gen.DO))
	return q.updateTableName(alias)
}

func (q *qnFee) updateTableName(table string) *qnFee {
	q.ALL = field.NewAsterisk(table)
	q.ID = field.NewInt32(table, "id")
	q.Slot = field.NewInt64(table, "slot")
	q.LowAvg = field.NewFloat64(table, "low_avg")
	q.MediumAvg = field.NewFloat64(table, "medium_avg")
	q.HighAvg = field.NewFloat64(table, "high_avg")
	q.CreatedAt = field.NewTime(table, "created_at")
	q.UpdatedAt = field.NewTime(table, "updated_at")

	q.fillFieldMap()

	return q
}

func (q *qnFee) WithContext(ctx context.Context) IQnFeeDo { return q.qnFeeDo.WithContext(ctx) }

func (q qnFee) TableName() string { return q.qnFeeDo.TableName() }

func (q qnFee) Alias() string { return q.qnFeeDo.Alias() }

func (q qnFee) Columns(cols ...field.Expr) gen.Columns { return q.qnFeeDo.Columns(cols...) }

func (q *qnFee) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := q.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (q *qnFee) fillFieldMap() {
	q.fieldMap = make(map[string]field.Expr, 7)
	q.fieldMap["id"] = q.ID
	q.fieldMap["slot"] = q.Slot
	q.fieldMap["low_avg"] = q.LowAvg
	q.fieldMap["medium_avg"] = q.MediumAvg
	q.fieldMap["high_avg"] = q.HighAvg
	q.fieldMap["created_at"] = q.CreatedAt
	q.fieldMap["updated_at"] = q.UpdatedAt
}

func (q qnFee) clone(db *gorm.DB) qnFee {
	q.qnFeeDo.ReplaceConnPool(db.Statement.ConnPool)
	return q
}

func (q qnFee) replaceDB(db *gorm.DB) qnFee {
	q.qnFeeDo.ReplaceDB(db)
	return q
}

type qnFeeDo struct{ gen.DO }

type IQnFeeDo interface {
	gen.SubQuery
	Debug() IQnFeeDo
	WithContext(ctx context.Context) IQnFeeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IQnFeeDo
	WriteDB() IQnFeeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IQnFeeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IQnFeeDo
	Not(conds ...gen.Condition) IQnFeeDo
	Or(conds ...gen.Condition) IQnFeeDo
	Select(conds ...field.Expr) IQnFeeDo
	Where(conds ...gen.Condition) IQnFeeDo
	Order(conds ...field.Expr) IQnFeeDo
	Distinct(cols ...field.Expr) IQnFeeDo
	Omit(cols ...field.Expr) IQnFeeDo
	Join(table schema.Tabler, on ...field.Expr) IQnFeeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IQnFeeDo
	RightJoin(table schema.Tabler, on ...field.Expr) IQnFeeDo
	Group(cols ...field.Expr) IQnFeeDo
	Having(conds ...gen.Condition) IQnFeeDo
	Limit(limit int) IQnFeeDo
	Offset(offset int) IQnFeeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IQnFeeDo
	Unscoped() IQnFeeDo
	Create(values ...*model.QnFee) error
	CreateInBatches(values []*model.QnFee, batchSize int) error
	Save(values ...*model.QnFee) error
	First() (*model.QnFee, error)
	Take() (*model.QnFee, error)
	Last() (*model.QnFee, error)
	Find() ([]*model.QnFee, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.QnFee, err error)
	FindInBatches(result *[]*model.QnFee, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.QnFee) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IQnFeeDo
	Assign(attrs ...field.AssignExpr) IQnFeeDo
	Joins(fields ...field.RelationField) IQnFeeDo
	Preload(fields ...field.RelationField) IQnFeeDo
	FirstOrInit() (*model.QnFee, error)
	FirstOrCreate() (*model.QnFee, error)
	FindByPage(offset int, limit int) (result []*model.QnFee, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IQnFeeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (q qnFeeDo) Debug() IQnFeeDo {
	return q.withDO(q.DO.Debug())
}

func (q qnFeeDo) WithContext(ctx context.Context) IQnFeeDo {
	return q.withDO(q.DO.WithContext(ctx))
}

func (q qnFeeDo) ReadDB() IQnFeeDo {
	return q.Clauses(dbresolver.Read)
}

func (q qnFeeDo) WriteDB() IQnFeeDo {
	return q.Clauses(dbresolver.Write)
}

func (q qnFeeDo) Session(config *gorm.Session) IQnFeeDo {
	return q.withDO(q.DO.Session(config))
}

func (q qnFeeDo) Clauses(conds ...clause.Expression) IQnFeeDo {
	return q.withDO(q.DO.Clauses(conds...))
}

func (q qnFeeDo) Returning(value interface{}, columns ...string) IQnFeeDo {
	return q.withDO(q.DO.Returning(value, columns...))
}

func (q qnFeeDo) Not(conds ...gen.Condition) IQnFeeDo {
	return q.withDO(q.DO.Not(conds...))
}

func (q qnFeeDo) Or(conds ...gen.Condition) IQnFeeDo {
	return q.withDO(q.DO.Or(conds...))
}

func (q qnFeeDo) Select(conds ...field.Expr) IQnFeeDo {
	return q.withDO(q.DO.Select(conds...))
}

func (q qnFeeDo) Where(conds ...gen.Condition) IQnFeeDo {
	return q.withDO(q.DO.Where(conds...))
}

func (q qnFeeDo) Order(conds ...field.Expr) IQnFeeDo {
	return q.withDO(q.DO.Order(conds...))
}

func (q qnFeeDo) Distinct(cols ...field.Expr) IQnFeeDo {
	return q.withDO(q.DO.Distinct(cols...))
}

func (q qnFeeDo) Omit(cols ...field.Expr) IQnFeeDo {
	return q.withDO(q.DO.Omit(cols...))
}

func (q qnFeeDo) Join(table schema.Tabler, on ...field.Expr) IQnFeeDo {
	return q.withDO(q.DO.Join(table, on...))
}

func (q qnFeeDo) LeftJoin(table schema.Tabler, on ...field.Expr) IQnFeeDo {
	return q.withDO(q.DO.LeftJoin(table, on...))
}

func (q qnFeeDo) RightJoin(table schema.Tabler, on ...field.Expr) IQnFeeDo {
	return q.withDO(q.DO.RightJoin(table, on...))
}

func (q qnFeeDo) Group(cols ...field.Expr) IQnFeeDo {
	return q.withDO(q.DO.Group(cols...))
}

func (q qnFeeDo) Having(conds ...gen.Condition) IQnFeeDo {
	return q.withDO(q.DO.Having(conds...))
}

func (q qnFeeDo) Limit(limit int) IQnFeeDo {
	return q.withDO(q.DO.Limit(limit))
}

func (q qnFeeDo) Offset(offset int) IQnFeeDo {
	return q.withDO(q.DO.Offset(offset))
}

func (q qnFeeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IQnFeeDo {
	return q.withDO(q.DO.Scopes(funcs...))
}

func (q qnFeeDo) Unscoped() IQnFeeDo {
	return q.withDO(q.DO.Unscoped())
}

func (q qnFeeDo) Create(values ...*model.QnFee) error {
	if len(values) == 0 {
		return nil
	}
	return q.DO.Create(values)
}

func (q qnFeeDo) CreateInBatches(values []*model.QnFee, batchSize int) error {
	return q.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (q qnFeeDo) Save(values ...*model.QnFee) error {
	if len(values) == 0 {
		return nil
	}
	return q.DO.Save(values)
}

func (q qnFeeDo) First() (*model.QnFee, error) {
	if result, err := q.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.QnFee), nil
	}
}

func (q qnFeeDo) Take() (*model.QnFee, error) {
	if result, err := q.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.QnFee), nil
	}
}

func (q qnFeeDo) Last() (*model.QnFee, error) {
	if result, err := q.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.QnFee), nil
	}
}

func (q qnFeeDo) Find() ([]*model.QnFee, error) {
	result, err := q.DO.Find()
	return result.([]*model.QnFee), err
}

func (q qnFeeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.QnFee, err error) {
	buf := make([]*model.QnFee, 0, batchSize)
	err = q.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (q qnFeeDo) FindInBatches(result *[]*model.QnFee, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return q.DO.FindInBatches(result, batchSize, fc)
}

func (q qnFeeDo) Attrs(attrs ...field.AssignExpr) IQnFeeDo {
	return q.withDO(q.DO.Attrs(attrs...))
}

func (q qnFeeDo) Assign(attrs ...field.AssignExpr) IQnFeeDo {
	return q.withDO(q.DO.Assign(attrs...))
}

func (q qnFeeDo) Joins(fields ...field.RelationField) IQnFeeDo {
	for _, _f := range fields {
		q = *q.withDO(q.DO.Joins(_f))
	}
	return &q
}

func (q qnFeeDo) Preload(fields ...field.RelationField) IQnFeeDo {
	for _, _f := range fields {
		q = *q.withDO(q.DO.Preload(_f))
	}
	return &q
}

func (q qnFeeDo) FirstOrInit() (*model.QnFee, error) {
	if result, err := q.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.QnFee), nil
	}
}

func (q qnFeeDo) FirstOrCreate() (*model.QnFee, error) {
	if result, err := q.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.QnFee), nil
	}
}

func (q qnFeeDo) FindByPage(offset int, limit int) (result []*model.QnFee, count int64, err error) {
	result, err = q.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = q.Offset(-1).Limit(-1).Count()
	return
}

func (q qnFeeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = q.Count()
	if err != nil {
		return
	}

	err = q.Offset(offset).Limit(limit).Scan(result)
	return
}

func (q qnFeeDo) Scan(result interface{}) (err error) {
	return q.DO.Scan(result)
}

func (q qnFeeDo) Delete(models ...*model.QnFee) (result gen.ResultInfo, err error) {
	return q.DO.Delete(models)
}

func (q *qnFeeDo) withDO(do gen.Dao) *qnFeeDo {
	q.DO = *do.(*gen.DO)
	return q
}
