// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"oshit-go/app/base/dal/model"
)

func newFeeStatistics(db *gorm.DB, opts ...gen.DOOption) feeStatistics {
	_feeStatistics := feeStatistics{}

	_feeStatistics.feeStatisticsDo.UseDB(db, opts...)
	_feeStatistics.feeStatisticsDo.UseModel(&model.FeeStatistics{})

	tableName := _feeStatistics.feeStatisticsDo.TableName()
	_feeStatistics.ALL = field.NewAsterisk(tableName)
	_feeStatistics.RecordID = field.NewString(tableName, "record_id")
	_feeStatistics.Slot = field.NewInt64(tableName, "slot")
	_feeStatistics.TransactionIndex = field.NewInt32(tableName, "transaction_index")
	_feeStatistics.BlockHash = field.NewString(tableName, "block_hash")
	_feeStatistics.TransactionID = field.NewString(tableName, "transaction_id")
	_feeStatistics.ComputeUnitPrice = field.NewFloat64(tableName, "compute_unit_price")
	_feeStatistics.ComputeUnitLimit = field.NewFloat64(tableName, "compute_unit_limit")
	_feeStatistics.UnitsConsumed = field.NewFloat64(tableName, "units_consumed")
	_feeStatistics.Fee = field.NewFloat64(tableName, "fee")
	_feeStatistics.CreatedAt = field.NewTime(tableName, "created_at")
	_feeStatistics.UpdatedAt = field.NewTime(tableName, "updated_at")

	_feeStatistics.fillFieldMap()

	return _feeStatistics
}

type feeStatistics struct {
	feeStatisticsDo feeStatisticsDo

	ALL              field.Asterisk
	RecordID         field.String
	Slot             field.Int64
	TransactionIndex field.Int32
	BlockHash        field.String
	TransactionID    field.String
	ComputeUnitPrice field.Float64
	ComputeUnitLimit field.Float64
	UnitsConsumed    field.Float64
	Fee              field.Float64
	CreatedAt        field.Time
	UpdatedAt        field.Time

	fieldMap map[string]field.Expr
}

func (f feeStatistics) Table(newTableName string) *feeStatistics {
	f.feeStatisticsDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f feeStatistics) As(alias string) *feeStatistics {
	f.feeStatisticsDo.DO = *(f.feeStatisticsDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *feeStatistics) updateTableName(table string) *feeStatistics {
	f.ALL = field.NewAsterisk(table)
	f.RecordID = field.NewString(table, "record_id")
	f.Slot = field.NewInt64(table, "slot")
	f.TransactionIndex = field.NewInt32(table, "transaction_index")
	f.BlockHash = field.NewString(table, "block_hash")
	f.TransactionID = field.NewString(table, "transaction_id")
	f.ComputeUnitPrice = field.NewFloat64(table, "compute_unit_price")
	f.ComputeUnitLimit = field.NewFloat64(table, "compute_unit_limit")
	f.UnitsConsumed = field.NewFloat64(table, "units_consumed")
	f.Fee = field.NewFloat64(table, "fee")
	f.CreatedAt = field.NewTime(table, "created_at")
	f.UpdatedAt = field.NewTime(table, "updated_at")

	f.fillFieldMap()

	return f
}

func (f *feeStatistics) WithContext(ctx context.Context) IFeeStatisticsDo {
	return f.feeStatisticsDo.WithContext(ctx)
}

func (f feeStatistics) TableName() string { return f.feeStatisticsDo.TableName() }

func (f feeStatistics) Alias() string { return f.feeStatisticsDo.Alias() }

func (f feeStatistics) Columns(cols ...field.Expr) gen.Columns {
	return f.feeStatisticsDo.Columns(cols...)
}

func (f *feeStatistics) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *feeStatistics) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 11)
	f.fieldMap["record_id"] = f.RecordID
	f.fieldMap["slot"] = f.Slot
	f.fieldMap["transaction_index"] = f.TransactionIndex
	f.fieldMap["block_hash"] = f.BlockHash
	f.fieldMap["transaction_id"] = f.TransactionID
	f.fieldMap["compute_unit_price"] = f.ComputeUnitPrice
	f.fieldMap["compute_unit_limit"] = f.ComputeUnitLimit
	f.fieldMap["units_consumed"] = f.UnitsConsumed
	f.fieldMap["fee"] = f.Fee
	f.fieldMap["created_at"] = f.CreatedAt
	f.fieldMap["updated_at"] = f.UpdatedAt
}

func (f feeStatistics) clone(db *gorm.DB) feeStatistics {
	f.feeStatisticsDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f feeStatistics) replaceDB(db *gorm.DB) feeStatistics {
	f.feeStatisticsDo.ReplaceDB(db)
	return f
}

type feeStatisticsDo struct{ gen.DO }

type IFeeStatisticsDo interface {
	gen.SubQuery
	Debug() IFeeStatisticsDo
	WithContext(ctx context.Context) IFeeStatisticsDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IFeeStatisticsDo
	WriteDB() IFeeStatisticsDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IFeeStatisticsDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IFeeStatisticsDo
	Not(conds ...gen.Condition) IFeeStatisticsDo
	Or(conds ...gen.Condition) IFeeStatisticsDo
	Select(conds ...field.Expr) IFeeStatisticsDo
	Where(conds ...gen.Condition) IFeeStatisticsDo
	Order(conds ...field.Expr) IFeeStatisticsDo
	Distinct(cols ...field.Expr) IFeeStatisticsDo
	Omit(cols ...field.Expr) IFeeStatisticsDo
	Join(table schema.Tabler, on ...field.Expr) IFeeStatisticsDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IFeeStatisticsDo
	RightJoin(table schema.Tabler, on ...field.Expr) IFeeStatisticsDo
	Group(cols ...field.Expr) IFeeStatisticsDo
	Having(conds ...gen.Condition) IFeeStatisticsDo
	Limit(limit int) IFeeStatisticsDo
	Offset(offset int) IFeeStatisticsDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IFeeStatisticsDo
	Unscoped() IFeeStatisticsDo
	Create(values ...*model.FeeStatistics) error
	CreateInBatches(values []*model.FeeStatistics, batchSize int) error
	Save(values ...*model.FeeStatistics) error
	First() (*model.FeeStatistics, error)
	Take() (*model.FeeStatistics, error)
	Last() (*model.FeeStatistics, error)
	Find() ([]*model.FeeStatistics, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FeeStatistics, err error)
	FindInBatches(result *[]*model.FeeStatistics, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.FeeStatistics) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IFeeStatisticsDo
	Assign(attrs ...field.AssignExpr) IFeeStatisticsDo
	Joins(fields ...field.RelationField) IFeeStatisticsDo
	Preload(fields ...field.RelationField) IFeeStatisticsDo
	FirstOrInit() (*model.FeeStatistics, error)
	FirstOrCreate() (*model.FeeStatistics, error)
	FindByPage(offset int, limit int) (result []*model.FeeStatistics, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IFeeStatisticsDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (f feeStatisticsDo) Debug() IFeeStatisticsDo {
	return f.withDO(f.DO.Debug())
}

func (f feeStatisticsDo) WithContext(ctx context.Context) IFeeStatisticsDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f feeStatisticsDo) ReadDB() IFeeStatisticsDo {
	return f.Clauses(dbresolver.Read)
}

func (f feeStatisticsDo) WriteDB() IFeeStatisticsDo {
	return f.Clauses(dbresolver.Write)
}

func (f feeStatisticsDo) Session(config *gorm.Session) IFeeStatisticsDo {
	return f.withDO(f.DO.Session(config))
}

func (f feeStatisticsDo) Clauses(conds ...clause.Expression) IFeeStatisticsDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f feeStatisticsDo) Returning(value interface{}, columns ...string) IFeeStatisticsDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f feeStatisticsDo) Not(conds ...gen.Condition) IFeeStatisticsDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f feeStatisticsDo) Or(conds ...gen.Condition) IFeeStatisticsDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f feeStatisticsDo) Select(conds ...field.Expr) IFeeStatisticsDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f feeStatisticsDo) Where(conds ...gen.Condition) IFeeStatisticsDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f feeStatisticsDo) Order(conds ...field.Expr) IFeeStatisticsDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f feeStatisticsDo) Distinct(cols ...field.Expr) IFeeStatisticsDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f feeStatisticsDo) Omit(cols ...field.Expr) IFeeStatisticsDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f feeStatisticsDo) Join(table schema.Tabler, on ...field.Expr) IFeeStatisticsDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f feeStatisticsDo) LeftJoin(table schema.Tabler, on ...field.Expr) IFeeStatisticsDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f feeStatisticsDo) RightJoin(table schema.Tabler, on ...field.Expr) IFeeStatisticsDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f feeStatisticsDo) Group(cols ...field.Expr) IFeeStatisticsDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f feeStatisticsDo) Having(conds ...gen.Condition) IFeeStatisticsDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f feeStatisticsDo) Limit(limit int) IFeeStatisticsDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f feeStatisticsDo) Offset(offset int) IFeeStatisticsDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f feeStatisticsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IFeeStatisticsDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f feeStatisticsDo) Unscoped() IFeeStatisticsDo {
	return f.withDO(f.DO.Unscoped())
}

func (f feeStatisticsDo) Create(values ...*model.FeeStatistics) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f feeStatisticsDo) CreateInBatches(values []*model.FeeStatistics, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f feeStatisticsDo) Save(values ...*model.FeeStatistics) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f feeStatisticsDo) First() (*model.FeeStatistics, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.FeeStatistics), nil
	}
}

func (f feeStatisticsDo) Take() (*model.FeeStatistics, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.FeeStatistics), nil
	}
}

func (f feeStatisticsDo) Last() (*model.FeeStatistics, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.FeeStatistics), nil
	}
}

func (f feeStatisticsDo) Find() ([]*model.FeeStatistics, error) {
	result, err := f.DO.Find()
	return result.([]*model.FeeStatistics), err
}

func (f feeStatisticsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FeeStatistics, err error) {
	buf := make([]*model.FeeStatistics, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f feeStatisticsDo) FindInBatches(result *[]*model.FeeStatistics, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f feeStatisticsDo) Attrs(attrs ...field.AssignExpr) IFeeStatisticsDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f feeStatisticsDo) Assign(attrs ...field.AssignExpr) IFeeStatisticsDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f feeStatisticsDo) Joins(fields ...field.RelationField) IFeeStatisticsDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f feeStatisticsDo) Preload(fields ...field.RelationField) IFeeStatisticsDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f feeStatisticsDo) FirstOrInit() (*model.FeeStatistics, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.FeeStatistics), nil
	}
}

func (f feeStatisticsDo) FirstOrCreate() (*model.FeeStatistics, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.FeeStatistics), nil
	}
}

func (f feeStatisticsDo) FindByPage(offset int, limit int) (result []*model.FeeStatistics, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f feeStatisticsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f feeStatisticsDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f feeStatisticsDo) Delete(models ...*model.FeeStatistics) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *feeStatisticsDo) withDO(do gen.Dao) *feeStatisticsDo {
	f.DO = *do.(*gen.DO)
	return f
}
