// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"oshit-go/app/base/dal/model"
)

func newNativeAccountInfo(db *gorm.DB, opts ...gen.DOOption) nativeAccountInfo {
	_nativeAccountInfo := nativeAccountInfo{}

	_nativeAccountInfo.nativeAccountInfoDo.UseDB(db, opts...)
	_nativeAccountInfo.nativeAccountInfoDo.UseModel(&model.NativeAccountInfo{})

	tableName := _nativeAccountInfo.nativeAccountInfoDo.TableName()
	_nativeAccountInfo.ALL = field.NewAsterisk(tableName)
	_nativeAccountInfo.RecordID = field.NewString(tableName, "record_id")
	_nativeAccountInfo.NativeAccount = field.NewString(tableName, "native_account")
	_nativeAccountInfo.TokenAccount = field.NewString(tableName, "token_account")
	_nativeAccountInfo.InviteCode = field.NewString(tableName, "invite_code")
	_nativeAccountInfo.CreatedAt = field.NewTime(tableName, "created_at")
	_nativeAccountInfo.UpdatedAt = field.NewTime(tableName, "updated_at")

	_nativeAccountInfo.fillFieldMap()

	return _nativeAccountInfo
}

type nativeAccountInfo struct {
	nativeAccountInfoDo nativeAccountInfoDo

	ALL           field.Asterisk
	RecordID      field.String
	NativeAccount field.String
	TokenAccount  field.String
	InviteCode    field.String
	CreatedAt     field.Time
	UpdatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (n nativeAccountInfo) Table(newTableName string) *nativeAccountInfo {
	n.nativeAccountInfoDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n nativeAccountInfo) As(alias string) *nativeAccountInfo {
	n.nativeAccountInfoDo.DO = *(n.nativeAccountInfoDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *nativeAccountInfo) updateTableName(table string) *nativeAccountInfo {
	n.ALL = field.NewAsterisk(table)
	n.RecordID = field.NewString(table, "record_id")
	n.NativeAccount = field.NewString(table, "native_account")
	n.TokenAccount = field.NewString(table, "token_account")
	n.InviteCode = field.NewString(table, "invite_code")
	n.CreatedAt = field.NewTime(table, "created_at")
	n.UpdatedAt = field.NewTime(table, "updated_at")

	n.fillFieldMap()

	return n
}

func (n *nativeAccountInfo) WithContext(ctx context.Context) INativeAccountInfoDo {
	return n.nativeAccountInfoDo.WithContext(ctx)
}

func (n nativeAccountInfo) TableName() string { return n.nativeAccountInfoDo.TableName() }

func (n nativeAccountInfo) Alias() string { return n.nativeAccountInfoDo.Alias() }

func (n nativeAccountInfo) Columns(cols ...field.Expr) gen.Columns {
	return n.nativeAccountInfoDo.Columns(cols...)
}

func (n *nativeAccountInfo) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *nativeAccountInfo) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 6)
	n.fieldMap["record_id"] = n.RecordID
	n.fieldMap["native_account"] = n.NativeAccount
	n.fieldMap["token_account"] = n.TokenAccount
	n.fieldMap["invite_code"] = n.InviteCode
	n.fieldMap["created_at"] = n.CreatedAt
	n.fieldMap["updated_at"] = n.UpdatedAt
}

func (n nativeAccountInfo) clone(db *gorm.DB) nativeAccountInfo {
	n.nativeAccountInfoDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n nativeAccountInfo) replaceDB(db *gorm.DB) nativeAccountInfo {
	n.nativeAccountInfoDo.ReplaceDB(db)
	return n
}

type nativeAccountInfoDo struct{ gen.DO }

type INativeAccountInfoDo interface {
	gen.SubQuery
	Debug() INativeAccountInfoDo
	WithContext(ctx context.Context) INativeAccountInfoDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() INativeAccountInfoDo
	WriteDB() INativeAccountInfoDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) INativeAccountInfoDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) INativeAccountInfoDo
	Not(conds ...gen.Condition) INativeAccountInfoDo
	Or(conds ...gen.Condition) INativeAccountInfoDo
	Select(conds ...field.Expr) INativeAccountInfoDo
	Where(conds ...gen.Condition) INativeAccountInfoDo
	Order(conds ...field.Expr) INativeAccountInfoDo
	Distinct(cols ...field.Expr) INativeAccountInfoDo
	Omit(cols ...field.Expr) INativeAccountInfoDo
	Join(table schema.Tabler, on ...field.Expr) INativeAccountInfoDo
	LeftJoin(table schema.Tabler, on ...field.Expr) INativeAccountInfoDo
	RightJoin(table schema.Tabler, on ...field.Expr) INativeAccountInfoDo
	Group(cols ...field.Expr) INativeAccountInfoDo
	Having(conds ...gen.Condition) INativeAccountInfoDo
	Limit(limit int) INativeAccountInfoDo
	Offset(offset int) INativeAccountInfoDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) INativeAccountInfoDo
	Unscoped() INativeAccountInfoDo
	Create(values ...*model.NativeAccountInfo) error
	CreateInBatches(values []*model.NativeAccountInfo, batchSize int) error
	Save(values ...*model.NativeAccountInfo) error
	First() (*model.NativeAccountInfo, error)
	Take() (*model.NativeAccountInfo, error)
	Last() (*model.NativeAccountInfo, error)
	Find() ([]*model.NativeAccountInfo, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NativeAccountInfo, err error)
	FindInBatches(result *[]*model.NativeAccountInfo, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.NativeAccountInfo) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) INativeAccountInfoDo
	Assign(attrs ...field.AssignExpr) INativeAccountInfoDo
	Joins(fields ...field.RelationField) INativeAccountInfoDo
	Preload(fields ...field.RelationField) INativeAccountInfoDo
	FirstOrInit() (*model.NativeAccountInfo, error)
	FirstOrCreate() (*model.NativeAccountInfo, error)
	FindByPage(offset int, limit int) (result []*model.NativeAccountInfo, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) INativeAccountInfoDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (n nativeAccountInfoDo) Debug() INativeAccountInfoDo {
	return n.withDO(n.DO.Debug())
}

func (n nativeAccountInfoDo) WithContext(ctx context.Context) INativeAccountInfoDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n nativeAccountInfoDo) ReadDB() INativeAccountInfoDo {
	return n.Clauses(dbresolver.Read)
}

func (n nativeAccountInfoDo) WriteDB() INativeAccountInfoDo {
	return n.Clauses(dbresolver.Write)
}

func (n nativeAccountInfoDo) Session(config *gorm.Session) INativeAccountInfoDo {
	return n.withDO(n.DO.Session(config))
}

func (n nativeAccountInfoDo) Clauses(conds ...clause.Expression) INativeAccountInfoDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n nativeAccountInfoDo) Returning(value interface{}, columns ...string) INativeAccountInfoDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n nativeAccountInfoDo) Not(conds ...gen.Condition) INativeAccountInfoDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n nativeAccountInfoDo) Or(conds ...gen.Condition) INativeAccountInfoDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n nativeAccountInfoDo) Select(conds ...field.Expr) INativeAccountInfoDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n nativeAccountInfoDo) Where(conds ...gen.Condition) INativeAccountInfoDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n nativeAccountInfoDo) Order(conds ...field.Expr) INativeAccountInfoDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n nativeAccountInfoDo) Distinct(cols ...field.Expr) INativeAccountInfoDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n nativeAccountInfoDo) Omit(cols ...field.Expr) INativeAccountInfoDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n nativeAccountInfoDo) Join(table schema.Tabler, on ...field.Expr) INativeAccountInfoDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n nativeAccountInfoDo) LeftJoin(table schema.Tabler, on ...field.Expr) INativeAccountInfoDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n nativeAccountInfoDo) RightJoin(table schema.Tabler, on ...field.Expr) INativeAccountInfoDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n nativeAccountInfoDo) Group(cols ...field.Expr) INativeAccountInfoDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n nativeAccountInfoDo) Having(conds ...gen.Condition) INativeAccountInfoDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n nativeAccountInfoDo) Limit(limit int) INativeAccountInfoDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n nativeAccountInfoDo) Offset(offset int) INativeAccountInfoDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n nativeAccountInfoDo) Scopes(funcs ...func(gen.Dao) gen.Dao) INativeAccountInfoDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n nativeAccountInfoDo) Unscoped() INativeAccountInfoDo {
	return n.withDO(n.DO.Unscoped())
}

func (n nativeAccountInfoDo) Create(values ...*model.NativeAccountInfo) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n nativeAccountInfoDo) CreateInBatches(values []*model.NativeAccountInfo, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n nativeAccountInfoDo) Save(values ...*model.NativeAccountInfo) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n nativeAccountInfoDo) First() (*model.NativeAccountInfo, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.NativeAccountInfo), nil
	}
}

func (n nativeAccountInfoDo) Take() (*model.NativeAccountInfo, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.NativeAccountInfo), nil
	}
}

func (n nativeAccountInfoDo) Last() (*model.NativeAccountInfo, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.NativeAccountInfo), nil
	}
}

func (n nativeAccountInfoDo) Find() ([]*model.NativeAccountInfo, error) {
	result, err := n.DO.Find()
	return result.([]*model.NativeAccountInfo), err
}

func (n nativeAccountInfoDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NativeAccountInfo, err error) {
	buf := make([]*model.NativeAccountInfo, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n nativeAccountInfoDo) FindInBatches(result *[]*model.NativeAccountInfo, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n nativeAccountInfoDo) Attrs(attrs ...field.AssignExpr) INativeAccountInfoDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n nativeAccountInfoDo) Assign(attrs ...field.AssignExpr) INativeAccountInfoDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n nativeAccountInfoDo) Joins(fields ...field.RelationField) INativeAccountInfoDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n nativeAccountInfoDo) Preload(fields ...field.RelationField) INativeAccountInfoDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n nativeAccountInfoDo) FirstOrInit() (*model.NativeAccountInfo, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.NativeAccountInfo), nil
	}
}

func (n nativeAccountInfoDo) FirstOrCreate() (*model.NativeAccountInfo, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.NativeAccountInfo), nil
	}
}

func (n nativeAccountInfoDo) FindByPage(offset int, limit int) (result []*model.NativeAccountInfo, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n nativeAccountInfoDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n nativeAccountInfoDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n nativeAccountInfoDo) Delete(models ...*model.NativeAccountInfo) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *nativeAccountInfoDo) withDO(do gen.Dao) *nativeAccountInfoDo {
	n.DO = *do.(*gen.DO)
	return n
}
